/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/apple-watch-se-3.jpeg";
import img2 from "@/images/products/apple-watch-se-3/02-apple-watch-se-3-midnight-1873.jpeg";
import img3 from "@/images/products/apple-watch-se-3/03-apple-watch-se-3-midnight889.jpeg";
import img4 from "@/images/products/apple-watch-se-3/04-apple-watch-se-3-starlight-1772.jpeg";

export const appleWatchSe3: ProductDetail = {
  breadcrumb: [
    { label: "Watches", slug: "watch" },
    { label: "Smart Watch", slug: "smart-watch" },
    { label: "Apple", slug: "apple-watch" },
  ],
  gallery: [img1, img2, img3, img4],
  inStock: true,

  highlights: [
    "S10 chip with 64‑bit dual core processor",
    "Always-On Retina display with OLED and LTPO",
    "All‑day battery life, up to 18 hours of normal use",
    "Up to 80% charge in about 45 minutes",
  ],

  colors: [
    { name: "Midnight", hex: "#4C4D4F", image: img2 },
    { name: "Starlight", hex: "#FAF7F2", image: img1 },
  ],

  options: [
    { label: "Dial Size", values: ["40mm", "44mm"] },
    { label: "Strap Size", values: ["M/L", "S/M"] },
  ],

  emi: { months: 6, perMonth: 6500 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["Apple"] },
        { label: "Model Name", value: ["Watch SE 3"] },
        { label: "MPN/ Part No", value: ["MEHC4X/A", "MEH34X/A", "MEHG4X/A", "MEHN4X/A"] },
      ],
    },
    {
      title: "Main Features",
      rows: [
        { label: "CPU", value: ["S10 chip with 64‑bit dual core processor", "4‑core Neural Engine"] },
        { label: "Storage", value: ["64GB capacity"] },
        { label: "Sensors", value: ["Second-generation optical heart sensor", "Temperature sensor1", "Compass", "Always-on altimeter", "High-g accelerometer", "High dynamic range gyroscope", "Ambient light sensor"] },
        { label: "Operating System", value: ["watchOS", "watchOS is the world’s most advanced wearable operating system, with apps and features designed to keep you active, healthy, safe, and connected."] },
        { label: "Battery", value: ["Built‑in rechargeable lithium‑ion battery"] },
        { label: "Battery Life", value: ["All‑day battery life, up to 18 hours of normal use", "Up to 32 hours in Low Power Mode"] },
        { label: "Charging", value: ["Up to 80% charge in about 45 minutes", "15 minutes for up to 8 hours of normal use", "8 minutes for up to 8 hours of sleep tracking"] },
        { label: "Others", value: ["Controls: Digital Crown with haptic feedback", "Side button", "Double tap and wrist flick gestures", "Siri with on‑device processing"] },
      ],
    },
    {
      title: "Display",
      rows: [
        { label: "Dial Shape", value: ["Round"] },
        { label: "Dial Size", value: ["977 sq mm display area", "Fits 140–245mm wrists"] },
        { label: "Technology", value: ["Always-On Retina display with OLED and LTPO"] },
        { label: "Resolution", value: ["Tough Ion-X front glass with 4x crack resistance5", "Up to 1000 nits peak brightness", "2 nits minimum brightness", "326 pixels per inch"] },
        { label: "Pixel Density", value: ["368 by 448 pixels"] },
      ],
    },
    {
      title: "Connectivity",
      rows: [
        { label: "Wi-Fi", value: ["Wi-Fi 4 (802.11n)", "Support for 2.4GHz Wi-Fi networks"] },
        { label: "Bluetooth", value: ["Bluetooth 5.3"] },
        { label: "GPS", value: ["L1 GPS, GNSS, Galileo, and QZSS", "5G and LTE"] },
        { label: "Others", value: ["Audio: Speaker", "Microphone", "Media playback", "Apple Pay", "GymKit", "Support for Apple Watch For Your Kids", "International roaming"] },
      ],
    },
    {
      title: "Physical Dimension",
      rows: [
        { label: "Water Rating", value: ["Water resistance 50m (swimproof)"] },
        { label: "Dimensions", value: ["Height: 44mm", "Width: 38mm", "Depth: 10.7mm"] },
        { label: "Weight", value: ["Weight (GPS): 32.9 grams", "Weight (GPS + Cellular): 33.0 grams"] },
        { label: "Color", value: ["Starlight, Midnight"] },
      ],
    },
  ],

  description: {
    title: "Apple Watch SE 3",
    blocks: [
      {
        heading: "Design and Comfort",
        paragraphs: [
          "The Apple Watch SE 3 comes in two sizes, 40mm and 44mm, designed to fit comfortably on every wrist. Its lightweight build makes it easy to wear all day, while the Ion-X front glass offers four times better crack resistance than before. The slim 10.7mm profile feels premium yet never bulky, making the Apple Watch SE 3 the kind of smartwatch you forget you are wearing until you need it.",
        ],
      },
      {
        heading: "Display Experience",
        paragraphs: [
          "The Always-On Retina display brings sharp details and vivid colors to everything you do. With OLED and LTPO technology, brightness reaches up to 1000 nits, so even under direct sunlight, you can see every notification, workout stat, or map direction clearly. At night, the screen dims to as low as 2 nits for comfort. The Apple Watch SE 3 makes checking the time during an outdoor run or reading a text message in bed equally effortless.",
        ],
      },
      {
        heading: "Performance and Power",
        paragraphs: [
          "Powered by the S10 chip with a 64-bit dual-core processor, the Apple Watch SE 3 runs apps smoothly and responds instantly. It is built with a 4-core Neural Engine for smarter processing on device, so Siri, fitness tracking, and apps feel quick and reliable. With fast charging, you can reach 80% in about 45 minutes. For daily use, the Apple Watch SE 3 lasts up to 18 hours, and Low Power Mode stretches it up to 32 hours. For a busy day at work, a workout, and a night of sleep tracking, this watch is always ready.",
        ],
      },
      {
        heading: "Health and Fitness Tracking",
        paragraphs: [
          "Staying active and healthy is easier with the Apple Watch SE 3 on your wrist. It includes a second-generation optical heart sensor, a temperature sensor, an always-on altimeter, and a high-dynamic-range gyroscope. The Apple Watch SE 3 tracks your workouts with accuracy, whether you are running, cycling, or swimming, since it is water-resistant up to 50 meters. Sleep tracking gives you insights into your rest, while daily activity rings motivate you to close your goals. For anyone focused on health, the Apple Watch SE 3 is a reliable fitness partner.",
        ],
      },
      {
        heading: "Safety and Connectivity",
        paragraphs: [
          "The Apple Watch SE 3 is more than a smartwatch; it is a safety tool. With LTE and GPS options, you stay connected even when your iPhone is not nearby. It supports Wi-Fi, Bluetooth 5.3, and international roaming for travel. Apple Pay makes payments quick and secure, while features like fall detection and emergency SOS add peace of mind. Siri works directly on the watch for faster responses without sending everything online. The Apple Watch SE 3 helps you stay safe, connected, and in control at all times.",
        ],
      },
      {
        heading: "Battery and Charging",
        paragraphs: [
          "A smartwatch should work as hard as you do, and the Apple Watch SE 3 delivers exactly that. The built-in rechargeable lithium-ion battery supports up to 18 hours of normal use, covering your day from morning workouts to evening relaxation. With low power mode, the watch battery extends up to 32 hours, perfect for travel or long days away from a charger. Just 15 minutes of charging provides enough power for hours of regular use, while 8 minutes can handle a full night of sleep tracking. With the Apple Watch SE 3, charging is quick and effortless.",
        ],
      },
      {
        heading: "Buying the Apple Watch SE 3 (GPS) Aluminum Case from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
