/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/apple-watch-series-11.jpeg";
import img2 from "@/images/products/apple-watch-series-11/02-apple-watch-series-11-silver-1763.jpeg";
import img3 from "@/images/products/apple-watch-series-11/03-apple-watch-series-11-silver345.jpeg";
import img4 from "@/images/products/apple-watch-series-11/04-apple-watch-series-11-rose-gold698.jpeg";
import img5 from "@/images/products/apple-watch-series-11/05-apple-watch-series-11-jet-black534.jpeg";
import img6 from "@/images/products/apple-watch-series-11/06-apple-watch-series-11-jet-black894.jpeg";
import img7 from "@/images/products/apple-watch-series-11/07-apple-watch-series-11-spacr-grey554.jpeg";
import img8 from "@/images/products/apple-watch-series-11/08-apple-watch-series-11-space-gray817.jpeg";

export const appleWatchSeries11: ProductDetail = {
  breadcrumb: [
    { label: "Watches", slug: "watch" },
    { label: "Smart Watch", slug: "smart-watch" },
    { label: "Apple", slug: "apple-watch" },
  ],
  gallery: [img1, img2, img3, img4, img5, img6, img7, img8],
  inStock: true,

  highlights: [
    "S10 chip with 64‑bit dual-core processor",
    "Always‑On Retina display with Aluminum Case",
    "All‑day battery life, up to 24 hours of normal use",
    "Up to 80% charge in about 30 minutes",
  ],

  colors: [
    { name: "Silver", hex: "#ededed", image: img2 },
    { name: "Rose Gold", hex: "#b76e79", image: img1 },
    { name: "Jet Black", hex: "#0a0a0a", image: img5 },
    { name: "Space Gray", hex: "#a7adba", image: img7 },
  ],

  options: [
    { label: "Dial Size", values: ["42mm", "46mm"] },
    { label: "Strap Size", values: ["S/M", "M/L"] },
  ],

  emi: { months: 12, perMonth: 4500 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["Apple"] },
        { label: "Model Name", value: ["Watch Series 11"] },
        { label: "MPN/ Part No", value: ["MEU04X/A", "MEU64X/A", "MEQT4X/A", "MEQW4X/A", "MEV64X/A", "MEV94X/A", "MEUW4X/A", "MEU44X/A", "MEU74X/A", "MEQU4X/A", "MEV74X/A", "MEVA4X/A", "MEUX4X/A", "MEV44X/A"] },
      ],
    },
    {
      title: "Main Features",
      rows: [
        { label: "CPU", value: ["S10 chip with 64‑bit dual-core processor", "4‑core Neural Engine"] },
        { label: "Storage", value: ["64GB capacity"] },
        { label: "Sensors", value: ["Electrical heart sensor", "Third‑generation optical heart sensor", "Blood oxygen sensor1", "Temperature sensor2", "Compass", "Always‑on altimeter", "High‑g accelerometer", "High dynamic range gyroscope", "Ambient light sensor", "Depth gauge to 6 meters", "Water temperature sensor"] },
        { label: "Operating System", value: ["watchOS", "watchOS is the world’s most advanced wearable operating system, with apps and features designed to keep you active, healthy, safe, and connected."] },
        { label: "Battery", value: ["Built‑in rechargeable lithium‑ion battery"] },
        { label: "Battery Life", value: ["All‑day battery life, up to 24 hours of normal use", "Up to 38 hours in Low Power Mode"] },
        { label: "Charging", value: ["Fast‑charge capable", "Up to 80% charge in about 30 minutes", "15 minutes for up to 8 hours of normal use", "5 minutes for up to 8 hours of sleep tracking"] },
        { label: "Special Features", value: ["Audio: Speaker", "Microphone", "Media playback"] },
        { label: "Others", value: ["Digital Crown with haptic feedback", "Side button", "Double tap and wrist flick gestures", "Siri with on‑device processing"] },
      ],
    },
    {
      title: "Display",
      rows: [
        { label: "Dial Shape", value: ["Round"] },
        { label: "Dial Size", value: ["Fits 140–245mm wrists"] },
        { label: "Technology", value: ["Always‑On Retina display with wide‑angle OLEDs and LTPO3"] },
        { label: "Resolution", value: ["Ion‑X front glass with 2x scratch resistance (aluminum cases)8", "Sapphire front crystal (titanium cases)", "Up to 2000 nits peak brightness", "1 nit minimum brightness", "326 pixels per inch"] },
        { label: "Pixel Density", value: ["416 by 496 pixels", "1220 sq mm display area"] },
      ],
    },
    {
      title: "Connectivity",
      rows: [
        { label: "Wi-Fi", value: ["Wi-Fi 4 (802.11n)", "Support for 2.4GHz and 5GHz Wi-Fi networks"] },
        { label: "Bluetooth", value: ["Bluetooth 5.3"] },
        { label: "GPS", value: ["L1 GPS, GLONASS, Galileo, QZSS, and BeiDou", "5G and LTE"] },
        { label: "Others", value: ["Second-generation Ultra Wideband chip", "Apple Pay", "GymKit", "Support for Apple Watch For Your Kids", "International roaming"] },
      ],
    },
    {
      title: "Physical Dimension",
      rows: [
        { label: "Water Rating", value: ["Water resistance 50m (swimproof)14", "Dust resistance IP6X"] },
        { label: "Dimensions", value: ["Height: 46mm", "Width: 39mm", "Depth: 9.7mm"] },
        { label: "Weight", value: ["Weight (aluminum, GPS): 37.8 grams", "Weight (aluminum, GPS + Cellular): 36.9 grams", "Weight (titanium): 43.1 grams"] },
        { label: "Color", value: ["Rose Gold, Silver, Space Gray, Jet Black"] },
      ],
    },
  ],

  description: {
    title: "Apple Watch Series 11",
    blocks: [
      {
        paragraphs: [
          "The Apple Watch Series 11 is the most powerful, intelligent, and fitness-forward smartwatch Apple has ever built. With its stunning Always-On Retina display, lightning-fast S10 chip, advanced health sensors, and up to 38 hours of battery life in Low Power Mode, the Series 11 isn’t just a watch—it’s your health companion, workout partner, and personal assistant, all on your wrist.",
        ],
      },
      {
        heading: "Key Features of Apple Watch Series 11",
        paragraphs: [
          "At the heart of the Apple Watch Series 11 is the ultra-efficient S10 chip—a 64-bit dual-core processor built to handle everything from high-intensity workouts to Siri requests without a hiccup. Paired with a 4-core Neural Engine, it brings lightning-fast performance and seamless multitasking to your wrist like never before. Whether you're tracking your run, streaming music, or responding to texts, everything feels effortless. With up to 2000 nits peak brightness, the Always-On Retina OLED display is easy to see even in direct sunlight. It’s also energy efficient, thanks to LTPO technology. Covered with Ion-X front glass on the aluminum model, it's now 2x more scratch-resistant, giving you the durability you need without sacrificing clarity.",
        ],
      },
      {
        heading: "Revolutionary Health Tracking",
        paragraphs: [
          "Apple continues to lead the way in wearable health technology. With the electrical heart sensor, third-generation optical heart sensor, blood oxygen sensor, and an innovative temperature sensor, the Series 11 helps you monitor your overall health 24/7. It also supports advanced sleep tracking, cycle tracking, and real-time alerts for irregular heart rhythms or unusually high/low heart rates. The aluminum case fits wrists from 140mm to 245mm and is incredibly lightweight at just 37.8 grams. Despite its slim 9.7mm profile, the display offers an impressive 1220 sq mm display area with a crisp 416 x 496 pixel resolution—that’s 326 pixels per inch for stunning clarity.",
        ],
      },
      {
        heading: "Stay Safe with Smart Sensor",
        paragraphs: [
          "From a high-G accelerometer that can detect car crashes or falls to a high-dynamic range gyroscope and ambient light sensor, this watch helps keep you safe in unpredictable moments. The Depth Gauge and Water Temperature Sensor make it ideal for swimmers and divers alike, offering real-time data underwater up to 6 meters deep.",
        ],
      },
      {
        heading: "All-Day Battery, Fast Charging",
        paragraphs: [
          "The Apple Watch Series 11 features an improved battery that keeps up with your active lifestyle. It delivers up to 24 hours of standard use, or an impressive 38 hours in Low Power Mode. When you need a quick top-up, just 15 minutes of charging gives you up to 8 hours of normal use, and 5 minutes is enough for a full night’s sleep tracking.",
        ],
      },
      {
        heading: "Smart Connectivity for a Smarter You",
        paragraphs: [
          "Stay connected wherever you go with support for Wi-Fi 4 (802.11n), Bluetooth 5.3, and GPS with multi-band support (L1 GPS, GLONASS, Galileo, QZSS, and BeiDou). Plus, features like Apple Pay, Siri with on-device processing, and second-generation Ultra Wideband make your Apple Watch feel less like a wearable and more like a wearable computer. Travelers will love the support for international roaming, ensuring you’re connected even when abroad. And for families, Apple Watch for Kids lets you stay in touch with your children even if they don’t have an iPhone.",
        ],
      },
      {
        heading: "Rugged, Swimproof, and Dust-Resistant",
        paragraphs: [
          "Designed for adventure, the Apple Watch Series 11 (GPS) Aluminum Case is swimproof up to 50 meters and certified IP6X dust resistant. Whether you're hiking a dusty trail or swimming laps, it’s built to keep going as long as you do.",
        ],
      },
      {
        heading: "Buying the Apple Watch Series 11 (GPS) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
