/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/bearbrick-audio-portable-bluetooth-speaker.jpeg";
import img2 from "@/images/products/bearbrick-audio-portable-bluetooth-speaker/02-bearbrick-audio-portable-bluetooth-speaker-white-1.jpeg";
import img3 from "@/images/products/bearbrick-audio-portable-bluetooth-speaker/03-bearbrick-audio-portable-bluetooth-speaker-white-2.jpeg";
import img4 from "@/images/products/bearbrick-audio-portable-bluetooth-speaker/04-bearbrick-audio-portable-bluetooth-speaker-black.jpeg";
import img5 from "@/images/products/bearbrick-audio-portable-bluetooth-speaker/05-bearbrick-audio-portable-bluetooth-speaker-black-1.jpeg";
import img6 from "@/images/products/bearbrick-audio-portable-bluetooth-speaker/06-bearbrick-audio-portable-bluetooth-speaker-black-2.jpeg";

export const bearbrickAudioPortableBluetoothSpeaker: ProductDetail = {
  breadcrumb: [
    { label: "Headphone & Speaker", slug: "headphone-speaker" },
    { label: "Speaker", slug: "speakers" },
    { label: "BE@RBRICK", slug: "bearbrick-speaker" },
  ],
  gallery: [img1, img2, img3, img4, img5, img6],
  inStock: true,

  highlights: [
    "Six hours of portable playtime.",
    "Core Release introduces a pared-back.",
    "Stereo pairing when you want to fill the room.",
    "Minimalist aesthetic designed to blend effortlessly into any interior.",
  ],

  colors: [
    { name: "Core White", hex: "#D9D9D9", image: img1 },
    { name: "Core Black", hex: "#373737", image: img4 },
  ],

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["BE@RBRICK"] },
        { label: "Model Name", value: ["Audio"] },
        { label: "MPN/ Part No", value: ["BB4U2", "BB4T2"] },
      ],
    },
    {
      title: "Main Features",
      rows: [
        { label: "Bluetooth Version", value: ["5.0"] },
        { label: "Bluetooth Profiles", value: ["A2DP v1.3, AVRCP v1.6"] },
        { label: "Bluetooth Transmitter Power", value: ["2400MHz-2483.5MHz"] },
        { label: "Driver Unit", value: ["2 x 20mm tweeter", "2 x 40mm mid/bass driver"] },
        { label: "Frequency Response", value: ["90Hz-20kHz"] },
        { label: "Battery Type", value: ["Li-ion 10.36 Wh"] },
        { label: "Charging Type", value: ["USB-C cable"] },
        { label: "Battery charge time", value: ["1.5 hours"] },
        { label: "Music play time", value: ["up to 6 hours"] },
        { label: "Signal / Noise Ratio", value: [">80dB"] },
        { label: "Output power (W)", value: ["2x10W RMS"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["5.2 x 11 x 2.7 inch"] },
        { label: "Weight", value: ["870g"] },
        { label: "Colors", value: ["Core White, Core Black"] },
      ],
    },
  ],

  description: {
    title: "BE@RBRICK Audio Portable Bluetooth Speaker",
    blocks: [
      {
        paragraphs: [
          "Bring style and sound together with the BEARBRICK Audio Portable Bluetooth Speaker, a unique blend of iconic design and powerful audio performance. Whether you're relaxing at home or heading out, this premium portable speaker delivers rich, immersive sound while standing out as a stylish statement piece. Designed for music lovers who value both aesthetics and performance, it’s the perfect companion for everyday listening.",
        ],
      },
      {
        heading: "Powerful Stereo Sound with Dual Drivers",
        paragraphs: [
          "Experience impressive audio quality with 2 x 20mm tweeters and 2 x 40mm mid/bass drivers, delivering balanced highs, clear vocals, and deep bass. With 2x10W RMS output power and a wide frequency response of 90Hz–20kHz, this Bluetooth speaker ensures a dynamic and immersive sound experience for all your favorite music genres.",
        ],
      },
      {
        heading: "Seamless Bluetooth 5.0 Connectivity",
        paragraphs: [
          "Equipped with Bluetooth 5.0, the BEARBRICK Audio Speaker offers fast, stable, and energy-efficient wireless connectivity. Supporting A2DP v1.3 and AVRCP v1.6 profiles, it ensures smooth streaming and easy control of your music directly from your smartphone or tablet.",
        ],
      },
      {
        heading: "Portable Design with Iconic Style",
        paragraphs: [
          "This speaker is more than just audio—it’s a design statement. With its unique BEARBRICK-inspired look, it adds a modern and artistic touch to your space. Despite its solid build (870g), the compact size (5.2 x 11 x 2.7 inches) makes it easy to carry wherever you go.",
        ],
      },
      {
        heading: "Long-Lasting Battery with Fast Charging",
        paragraphs: [
          "Powered by a 10.36 Wh Li-ion battery, this speaker offers up to 6 hours of music playtime on a single charge. The USB-C fast charging feature fully recharges the device in just 1.5 hours, keeping your music going with minimal downtime. With a signal-to-noise ratio of over 80dB, this speaker delivers clean and distortion-free sound, ensuring every beat and note is heard clearly—even at higher volumes.",
        ],
      },
      {
        heading: "Premium Build & Color Options",
        paragraphs: [
          "Available in Core White and Core Black, the BEARBRICK Audio Portable Bluetooth Speaker complements any setup, whether modern or minimal. Its premium construction ensures durability while maintaining a sleek and stylish appearance.",
        ],
      },
      {
        heading: "Buying the BE@RBRICK Audio Portable Bluetooth Speaker from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
