/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/belkin-sheerforce-clear-case-for-iphone-air.jpeg";
import img2 from "@/images/products/belkin-sheerforce-clear-case-for-iphone-air/02-belkin-sheerforce-clear-case-for-iphone-air19.jpeg";
import img3 from "@/images/products/belkin-sheerforce-clear-case-for-iphone-air/03-belkin-sheerforce-clear-case-for-iphone-air-2352.jpeg";
import img4 from "@/images/products/belkin-sheerforce-clear-case-for-iphone-air/04-belkin-sheerforce-clear-case-for-iphone-air-3615.jpeg";

export const belkinSheerforceClearCaseForIphoneAir: ProductDetail = {
  breadcrumb: ["Cases & Protectors", "Apple", "iPhone Air"],
  gallery: [img1, img2, img3, img4],
  inStock: true,

  highlights: [
    "Up to 13ft/4m drop protection",
    "Compatible with wireless charging accessories",
    "Anti-yellowing‡ materials help the case stay clear",
    "Anti-scratch film",
  ],

  colors: [
    { name: "Clear", hex: "#CDCCCD", image: img1 },
  ],

  specs: [
    {
      title: "Product Specifications",
      rows: [
        { label: "Compatible Devices", value: ["iPhone Air"] },
        { label: "Color", value: ["Clear"] },
        { label: "Fast Charging", value: ["Yes"] },
        { label: "MagSafe Compatibility", value: ["Yes"] },
        { label: "Special Feature", value: ["Up to 13ft/4m drop protection.", "Compatible with wireless charging accessories.", "Anti-yellowing‡ materials help the case stay clear.", "Anti-scratch film.", "Touch-sensitive Camera Control button for fully responsive experience.", "Raised edges protect screen and camera lenses.", "Super thin and lightweight, maintains original iPhone experience.", "Side grooves for easy grip.", "Polished buttons for protection and tactile response.", "Product made with recycled material."] },
      ],
    },
  ],

  description: {
    title: "Belkin SheerForce Clear Case for iPhone Air",
    blocks: [
      {
        paragraphs: [
          "The Belkin SheerForce Clear Case for iPhone Air is designed to protect your phone while keeping its original look on full display. Built with Belkin’s trusted quality, this slim clear case delivers everyday drop protection without adding bulk. It’s the ideal choice for users who want reliable defense, long-lasting clarity, and a clean, modern finish.",
        ],
      },
      {
        heading: "Key Features of Belkin SheerForce Clear Case",
        paragraphs: [
          "The Belkin SheerForce Clear Case offers a smooth yet secure grip, making it comfortable to hold for long periods. Its flexible construction allows easy installation and removal, while the slim profile keeps your phone pocket-friendly. The case also supports wireless charging, so you can power up your iPhone Air without removing it. Made from high-quality transparent materials, the Belkin SheerForce Clear Case is engineered to resist yellowing and maintain clarity over time. It allows the natural color and design of your iPhone Air to shine through while shielding it from scratches, scuffs, and daily wear. The ultra-clear finish keeps your phone looking new, even with regular use. Despite its lightweight and slim profile, the SheerForce Clear Case offers strong everyday protection. Shock-absorbing construction helps reduce the impact of accidental drops, while reinforced edges add extra durability where it matters most. Raised bezels around the screen and camera help prevent surface scratches when your phone is placed face-down or on flat surfaces. This case is precisely molded to fit the iPhone Air perfectly, ensuring smooth access to all buttons, ports, and speakers. The responsive button covers provide a comfortable press, while accurate cutouts allow hassle-free charging and audio use. The snug fit keeps the case securely in place without feeling tight or bulky. Designed specifically for the iPhone Air, this clear case is made from durable, scratch-resistant materials that balance flexibility and strength. Belkin’s attention to detail ensures long-term performance, reliable protection, and a consistently clean appearance throughout daily use.",
        ],
      },
      {
        heading: "Buying the Belkin SheerForce Clear Case for iPhone Air from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
