/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/galaxy-watch-8.jpeg";
import img2 from "@/images/products/galaxy-watch-8/02-galaxy-watch-8-graphite164.jpeg";
import img3 from "@/images/products/galaxy-watch-8/04-samsung-galaxy-watch-8-40mm809.jpeg";
import img4 from "@/images/products/galaxy-watch-8/06-galaxy-watch-8-graphite---40mm98.jpeg";

export const galaxyWatch8: ProductDetail = {
  breadcrumb: [
    { label: "Watches", slug: "watch" },
    { label: "Smart Watch", slug: "smart-watch" },
    { label: "Samsung", slug: "samsung-watch" },
  ],
  gallery: [img1, img2, img3, img4],
  inStock: true,

  highlights: [
    "Display Brightness: Up to 3000 nits",
    "Processor: 3 nm Processor, 5 Core",
    "Memory / Storage: 2 GB / 32 GB",
    "Super AMOLED Display",
  ],

  colors: [
    { name: "Graphite", hex: "#5B5A56", image: img2 },
    { name: "Silver", hex: "#ededed", image: img1 },
  ],

  options: [
    { label: "Dial Size", values: ["40mm", "44mm"] },
  ],

  emi: { months: 6, perMonth: 4583 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "CPU", value: ["1.6GHz, 1.5GHz"] },
        { label: "RAM", value: ["2 GB"] },
        { label: "Storage", value: ["32 GB"] },
        { label: "Sensors", value: ["Accelerometer, Barometer, Bioelectrical Impedance Analysis Sensor, Electrical Heart Sensor, Gyro Sensor, Geomagnetic Sensor, Infrared Temperature Sensor, Light Sensor, Optical Heart Rate Sensor"] },
        { label: "Operating System", value: ["Android Wear OS 6, One UI 8 Watch"] },
        { label: "Battery", value: ["435 mAh"] },
        { label: "Battery Life", value: ["Up to 30 hrs (*AOD On)"] },
        { label: "Special Features", value: ["Audio Playing Format: MP3, M4A, 3GA, AAC, OGG, OGA, WAV, AMR, AWB"] },
      ],
    },
    {
      title: "Display",
      rows: [
        { label: "Dial Shape", value: ["Round"] },
        { label: "Dial Size", value: ["1.5\" (37.3mm)", "Case Size : 44mm , 40 mm"] },
        { label: "Technology", value: ["Super AMOLED"] },
        { label: "Resolution", value: ["480 x 480"] },
      ],
    },
    {
      title: "Connectivity",
      rows: [
        { label: "Wi-Fi", value: ["802.11a/b/g/n 2.4GHz+5GHz"] },
        { label: "Bluetooth", value: ["Bluetooth"] },
        { label: "GPS", value: ["L1+L5 Dual-", "Frequency GPS"] },
      ],
    },
    {
      title: "Physical Dimension",
      rows: [
        { label: "Dimensions", value: ["46.0 x 43.7 x 8.6"] },
        { label: "Weight", value: ["34g"] },
        { label: "Material", value: ["Armor Aluminum"] },
        { label: "Water Rating", value: ["IP68"] },
        { label: "Color", value: ["Silver, Graphite"] },
      ],
    },
  ],

  description: {
    title: "Galaxy Watch 8",
    blocks: [
      {
        paragraphs: [
          "The Galaxy Watch 8 Smart Watch is not just a regular smartwatch; it’s a perfect combination of technology, style, and functionality. Designed for those who want to stay connected, track their health, and enjoy premium performance, this watch makes everyday life smarter and easier. With powerful hardware, advanced health monitoring, and a modern design, the Samsung Galaxy Watch 8 is built to match your lifestyle and keep you ahead of the curve. Whether you’re at work, in the gym, or exploring outdoors, this smartwatch is your all-in-one companion.",
        ],
      },
      {
        heading: "Galaxy Watch 8 Specifications",
        paragraphs: [
          "Crafted with Armor Aluminum, the Galaxy Watch 8 combines lightweight comfort with exceptional durability. At just 34g, it feels effortless on your wrist, making it ideal for daily wear, workouts, and even sleep tracking. The round dial shape gives it a classic yet modern look, perfectly balancing elegance with rugged practicality. Plus, with IP68 water resistance, the smartwatch is built to withstand sweat, splashes, and everyday adventures.",
          "RAM: 2 GB",
          "Storage: 32 GB",
          "Operating System: Android Wear OS 6 with One UI 8 Watch",
          "Battery Capacity: 435 mAh",
          "Battery Life: Up to 30 hrs (Always-On Display On)",
          "Display Shape: Round",
          "Sensors: Accelerometer, Barometer, Bioelectrical Impedance Analysis Sensor, Electrical Heart Sensor, Gyro Sensor, Geomagnetic Sensor, Infrared Temperature Sensor, Light Sensor, Optical Heart Rate Sensor",
          "Connectivity: Bluetooth / Bluetooth + LTE GPS: L1 + L5 Dual-Frequency GPS",
          "Material: Armor Aluminum",
          "Water Rating: IP68",
        ],
      },
      {
        heading: "Brilliant Display and Smooth User Experience",
        paragraphs: [
          "The Galaxy Watch 8 is equipped with a vibrant, high-quality display that delivers sharp visuals and smooth touch response. Whether you are checking notifications, browsing through apps, or tracking your workout, every detail appears crystal clear on the screen. Running on Android Wear OS 6 with Samsung’s One UI 8 Watch, the smartwatch offers an intuitive interface that feels natural and effortless to use. Switching between apps, replying to messages, or navigating settings is seamless, making the watch feel like an extension of your smartphone. This smooth experience ensures that you stay productive and connected, all from your wrist.",
        ],
      },
      {
        heading: "Powerful Performance with Ample Storage",
        paragraphs: [
          "Inside, the Galaxy Watch 8 (44mm) is powered by 2GB RAM and 32GB of internal storage, ensuring fast performance and plenty of space for your apps, music, and important files. This means you can store playlists for offline listening, download fitness apps, and even save essential documents without worrying about running out of memory. The combination of strong hardware and optimized software allows the watch to run smoothly, giving you a premium smartwatch experience that keeps up with your busy schedule. Whether you’re multitasking between fitness tracking, calls, and apps, the Galaxy Watch 8 delivers consistent and reliable performance.",
        ],
      },
      {
        heading: "Advanced Health and Fitness Tracking",
        paragraphs: [
          "Samsung continues to lead the way in health technology, and the Galaxy Watch 8 is no exception. Packed with multiple advanced sensors, it provides accurate insights into your overall health and fitness. With its accelerometer, barometer, gyro sensor, and geomagnetic sensor, it helps track physical activities with precision. The optical heart rate sensor and electrical heart sensor ensure accurate heart monitoring, while the Bioelectrical Impedance Analysis (BIA) sensor measures body composition to help you understand your fitness progress. The addition of an infrared temperature sensor takes health tracking to the next level, giving you more detailed data about your well-being. From daily activity tracking to advanced sleep and workout monitoring, the Galaxy Watch 8 ensures you have the information you need to stay healthy and motivated.",
        ],
      },
      {
        heading: "Reliable Battery Life for All-Day Power",
        paragraphs: [
          "Battery performance is one of the most important factors in a smartwatch, and the Galaxy Watch 8 (44mm) doesn’t disappoint. With its 435mAh battery, it can last up to 30 hours even with the Always-On Display enabled, so you don’t have to constantly worry about recharging. Whether you are working long hours, traveling, or tracking your fitness throughout the day, the watch provides dependable power to keep up with your routine. Designed for convenience, the Galaxy Watch 8 ensures that you stay connected and productive all day long without interruptions.",
        ],
      },
      {
        heading: "Stay Connected Anywhere You Go",
        paragraphs: [
          "With both Bluetooth and LTE connectivity options, the Galaxy Watch 8 allows you to stay connected no matter where you are. You can make calls, reply to messages, and stream music directly from your watch, even when your phone isn’t nearby. The dual-frequency GPS (L1+L5) provides precise and reliable navigation, making it an excellent companion for outdoor adventures like running, hiking, and cycling. Whether you’re navigating city streets or exploring new trails, the Galaxy Watch 8 ensures that you’re always connected and on the right path.",
        ],
      },
      {
        heading: "Seamless Integration with the Galaxy Ecosystem",
        paragraphs: [
          "The Samsung Galaxy Watch 8 (44mm) is designed to work perfectly with your Galaxy smartphone and other Samsung devices. From syncing your health data with Samsung Health to controlling smart home devices, the watch integrates seamlessly into your digital lifestyle. It also pairs effortlessly with Galaxy Buds for a complete audio experience during workouts or while traveling. This smooth ecosystem connection makes the Galaxy Watch 8 much more than just a smartwatch—it becomes an essential part of your entire Galaxy setup, giving you control, convenience, and efficiency in one device.",
        ],
      },
      {
        heading: "Buying the Galaxy Watch 8 from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
