/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/galaxy-watch-8-classic.jpeg";
import img2 from "@/images/products/galaxy-watch-8-classic/02-galaxy-watch-8-classic-black-2257.jpeg";
import img3 from "@/images/products/galaxy-watch-8-classic/03-galaxy-watch-8-classic-white550.jpeg";
import img4 from "@/images/products/galaxy-watch-8-classic/04-galaxy-watch-8-classic-white-243.jpeg";

export const galaxyWatch8Classic: ProductDetail = {
  breadcrumb: [
    { label: "Watches", slug: "watch" },
    { label: "Smart Watch", slug: "smart-watch" },
    { label: "Samsung", slug: "samsung-watch" },
  ],
  gallery: [img1, img2, img3, img4],
  inStock: true,

  highlights: [
    "Memory: 2GB RAM, 64GB Internal Memory",
    "Display: 1.34\" Super AMOLED (438 x 438p), 3000 nits",
    "Battery Capacity: 445mAh ,Usage Time: Up to 40H (AOD Off) , Up to 30H (AOD On)",
    "Processor: Exynos W1000 (3 nm, 5 Core), GPU: Mali-G68",
  ],

  colors: [
    { name: "Black", hex: "#000000", image: img1 },
    { name: "White", hex: "#ffffff", image: img3 },
  ],

  options: [
    { label: "Dial Size", values: ["46mm"] },
  ],

  emi: { months: 6, perMonth: 5917 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["Samsung"] },
        { label: "Model Name", value: ["Galaxy Watch 8 Classic"] },
      ],
    },
    {
      title: "Main Features",
      rows: [
        { label: "CPU", value: ["CPU Type: Penta-Core", "CPU Speed-1.6GHz, 1.5GHz"] },
        { label: "RAM", value: ["2GB"] },
        { label: "Storage", value: ["64GB"] },
        { label: "Sensors", value: ["Accelerometer, Barometer, Bioelectrical Impedance Analysis Sensor, Electrical Heart Sensor, Gyro Sensor, Geomagnetic Sensor, Hall Sensor, Infrared Temperature Sensor, Light Sensor, Optical Heart Rate Sensor"] },
        { label: "Operating System", value: ["Wear OS Powered by Samsung"] },
        { label: "Battery", value: ["445 mAh"] },
        { label: "Battery Life", value: ["Up to 40H (AOD Off) , Up to 30H (AOD On)"] },
        { label: "Others", value: ["Audio Playing Format: MP3, M4A, 3GA, AAC, OGG, OGA, WAV, AMR, AWB"] },
      ],
    },
    {
      title: "Display",
      rows: [
        { label: "Dial Shape", value: ["Round"] },
        { label: "Technology", value: ["Super AMOLED"] },
        { label: "Resolution", value: ["438 x 438"] },
      ],
    },
    {
      title: "Connectivity",
      rows: [
        { label: "Wi-Fi", value: ["802.11a/b/g/n 2.4GHz+5GHz802.11a/b/g/n 2.4GHz+5GHz"] },
        { label: "Bluetooth", value: ["Bluetooth v5.3"] },
        { label: "GPS", value: ["GPS, Glonass, Beidou, Galileo"] },
      ],
    },
    {
      title: "Physical Dimension",
      rows: [
        { label: "Water Rating", value: ["5 ATM"] },
        { label: "Dimensions", value: ["46.0 x 46.4 x 10.6mm"] },
        { label: "Weight", value: ["63.5g"] },
        { label: "Color", value: ["Black, White"] },
      ],
    },
  ],

  description: {
    title: "Galaxy Watch 8 Classic",
    blocks: [
      {
        paragraphs: [
          "The Galaxy Watch 8 Classic Smart Watch combines timeless design with next-generation innovation, giving you the perfect balance between classic style and advanced technology. With its premium build, stunning Super AMOLED display, powerful performance, and advanced health tracking, this smartwatch is designed to keep you connected, productive, and healthier in your everyday life. Whether you want a companion for workouts, productivity, or simply a stylish wearable, the Samsung Galaxy Watch 8 Classic is the ultimate all-rounder.",
        ],
      },
      {
        heading: "Galaxy Watch 8 Classic Specifications",
        paragraphs: [
          "Crafted with precision, the Galaxy Watch 8 Classic carries a round dial that feels both modern and timeless. Measuring 46.0 x 46.4 x 10.6mm and weighing just 63.5g, it fits comfortably on your wrist without feeling bulky. The watch is built with durable materials and offers a 5 ATM water resistance rating, making it suitable for swimming and outdoor adventures. Its rotating bezel and smooth finish give it a refined look, making it versatile enough for both casual and professional wear.",
          "CPU: Penta-Core (1.6GHz + 1.5GHz)",
          "RAM/Storage: 2GB / 64GB",
          "OS: Wear OS Powered by Samsung",
          "Battery: 445 mAh (Up to 40H AOD Off, 30H AOD On)",
          "Display: 1.5\" Super AMOLED, 438×438, Round",
          "Connectivity: Wi-Fi (2.4/5GHz), Bluetooth v5.3, GPS (GPS, Glonass, Beidou, Galileo),",
          "Sensors: Accelerometer, Barometer, Heart Rate, BIA, Gyro, Geomagnetic, Hall, Infrared Temp, Light",
          "Audio: MP3, AAC, WAV, OGG, AMR & more",
          "Build: 46.0×46.4×10.6 mm, 63.5g, Stainless Steel, 5ATM Water Resistance",
        ],
      },
      {
        heading: "Classic Design with Modern Innovation",
        paragraphs: [
          "Samsung has refined the classic rotating-bezel design in the Galaxy Watch 8 Classic, giving it a premium and elegant look that suits any occasion. Whether you’re in the boardroom, the gym, or out for a casual day, this smartwatch blends effortlessly with your style. Crafted with a stainless-steel body and featuring a round Super AMOLED display with a crisp 438 × 438 resolution, the screen is bright, vibrant, and easy to read even in direct sunlight. The always-on display (AOD) mode keeps you informed at a glance, while still optimizing battery performance.",
        ],
      },
      {
        heading: "Powerful Performance with Advanced Hardware",
        paragraphs: [
          "Powered by a penta-core CPU running at speeds of 1.6 GHz and 1.5 GHz, the Galaxy Watch 8 Classic ensures fast, smooth navigation through apps, notifications, and settings. With 2 GB of RAM and a massive 64 GB of internal storage, you’ll have plenty of space for apps, music, and even offline workouts. Whether you’re multitasking on the go or streaming your favorite playlist during a run, this smartwatch handles it all with ease and reliability.",
        ],
      },
      {
        heading: "Health and Fitness Tracking Like Never Before",
        paragraphs: [
          "The Galaxy Watch 8 Classic is loaded with an advanced suite of health and fitness sensors designed to help you take control of your wellness. It features a Bioelectrical Impedance Analysis sensor, optical and electrical heart-rate sensors, infrared temperature sensing, and a barometer—all working together to give you deep insights into your body. From monitoring your heart rate and stress levels to tracking your body composition and sleep cycles, this smartwatch acts like a personal trainer and health coach on your wrist. Whether you’re into running, cycling, or simply walking, its automatic workout detection and GPS-based tracking make it an ideal fitness companion.",
        ],
      },
      {
        heading: "Stay Connected Wherever You Go",
        paragraphs: [
          "Equipped with Bluetooth v5.3, Wi-Fi (2.4 GHz + 5 GHz) capabilities, the Galaxy Watch 8 Classic ensures you’re always connected. Make calls, reply to texts, check notifications, or even stream music—right from your wrist. The built-in GPS, Glonass, Beidou, and Galileo systems give you accurate location data for navigation and workout tracking. You can enjoy convenient Samsung Pay transactions on the go, turning your watch into a digital wallet.",
        ],
      },
      {
        heading: "Long-Lasting Battery Life for All-Day Use",
        paragraphs: [
          "Battery life is a major strength of the Galaxy Watch 8 Classic. With its 445 mAh battery, it delivers up to 40 hours of usage with the always-on display turned off, and up to 30 hours with AOD on. This means you can go about your day without constantly worrying about charging. Whether you’re attending meetings, working out, or traveling, the watch is designed to keep up with your lifestyle.",
        ],
      },
      {
        heading: "Built for Durability and Everyday Life",
        paragraphs: [
          "The Galaxy Watch 8 Classic isn’t just stylish—it’s built tough. With a 5 ATM water-resistance rating, it’s safe to use during swimming, workouts, or in the rain. Its sturdy 46.0 × 46.4 × 10.6 mm frame and 63.5 g weight give it a solid yet comfortable feel on the wrist. Samsung has ensured this smartwatch can withstand the demands of everyday life while maintaining its polished, premium look.",
        ],
      },
      {
        heading: "Smarter Everyday Features for Productivity",
        paragraphs: [
          "Beyond fitness and health, the Galaxy Watch 8 Classic is a productivity powerhouse. It supports multiple audio formats such as MP3, AAC, WAV, and more—allowing you to enjoy music directly from your watch without needing your phone. You can also control smart home devices, check your calendar, use voice assistants, and install apps from the Google Play Store thanks to its Wear OS powered by Samsung platform. Whether you’re managing work, life, or wellness, this smartwatch keeps you organized and efficient.",
        ],
      },
      {
        heading: "Buying the Galaxy Watch 8 Classic from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
