/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/galaxy-watch-7.jpeg";
import img2 from "@/images/products/galaxy-watch-7/02-samsung-galaxy-watch-7-smart-watch-1754.jpeg";
import img3 from "@/images/products/galaxy-watch-7/03-samsung-galaxy-watch-7-smart-watch-green690.jpeg";
import img4 from "@/images/products/galaxy-watch-7/04-samsung-galaxy-watch-7-smart-watch-green-1330.jpeg";
import img5 from "@/images/products/galaxy-watch-7/07-galaxy-watch-7-cream311.jpeg";

export const galaxyWatch7: ProductDetail = {
  breadcrumb: [
    { label: "Watches", slug: "watch" },
    { label: "Smart Watch", slug: "smart-watch" },
    { label: "Samsung", slug: "samsung-watch" },
  ],
  gallery: [img1, img2, img3, img4, img5],
  inStock: true,

  highlights: [
    "Display: 1.3\" (33.3mm) Super AMOLED (432 x 432)",
    "Processor: Exynos W1000 (3 nm,5 Core, 1.5GHz)",
    "Memory: 2GB RAM, 32GB Internal Memory",
    "Features: IP68, 5ATM, MIL-STD-810H compliant",
  ],

  colors: [
    { name: "Silver", hex: "#ededed", image: img1 },
    { name: "Green", hex: "#008000", image: img3 },
    { name: "Cream", hex: "#D4C9C3", image: img5 },
  ],

  options: [
    { label: "Dial Size", values: ["44mm", "40mm"] },
  ],

  emi: { months: 6, perMonth: 3750 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "CPU", value: ["CPU Speed: 1.6 GHz,1.5 GHz", "CPU Type: Penta-Core"] },
        { label: "RAM", value: ["2GB"] },
        { label: "Storage", value: ["32GB"] },
        { label: "Sensors", value: ["Accelerometer,Barometer,Bioelectrical Impedance Analysis Sensor,Electrical Heart Sensor,Gyro Sensor,Geomagnetic Sensor,Infrared Temperature Sensor,Light Sensor,Optical Heart Rate Sensor"] },
        { label: "Operating System", value: ["Wear OS Powered by Samsung"] },
        { label: "Battery", value: ["300 (mAh, Typical)"] },
        { label: "Battery Life", value: ["Usage Time (Hours, AOD Off): Up to 40", "Usage Time (Hours, AOD On): Up to 30"] },
        { label: "Others", value: ["Compatibility: Only compatible with Android OS", "Audio and Video", "Audio Playing Format", "MP3,M4A,3GA,AAC,OGG,OGA,WAV,AMR,AWB"] },
      ],
    },
    {
      title: "Display",
      rows: [
        { label: "Dial Shape", value: ["Round"] },
        { label: "Dial Size", value: ["1.3\" (33.3 mm)", "Case Size: 44mm / 40mm"] },
        { label: "Technology", value: ["Super AMOLED"] },
        { label: "Resolution", value: ["432 x 4325"] },
        { label: "Pixel Density", value: ["Color Depth (Main Display): 16M"] },
      ],
    },
    {
      title: "Connectivity",
      rows: [
        { label: "Wi-Fi", value: ["802.11a/b/g/n 2.4 GHz+5 GHz"] },
        { label: "Bluetooth", value: ["Bluetooth v5.3", "Bluetooth Profiles: A2DP,AVRCP,HFP,HSP"] },
        { label: "GPS", value: ["GPS,Glonass,Beidou,Galileo"] },
      ],
    },
    {
      title: "Physical Dimension",
      rows: [
        { label: "Dimensions", value: ["40.4 x 40.4 x 9.7"] },
        { label: "Weight", value: ["28.8g"] },
        { label: "Material", value: ["5 ATM"] },
        { label: "Color", value: ["Silver, Green"] },
      ],
    },
  ],

  description: {
    title: "Galaxy Watch 7",
    blocks: [
      {
        heading: "Galaxy Watch 7 Specifications",
        paragraphs: [
          "The 1.3-inch Super AMOLED screen on the Galaxy Watch 7 delivers brilliant clarity and vivid colors, even under direct sunlight. With a 432 x 432 resolution and 16M color depth, every detail looks crisp and lifelike. The always-on display (AOD) option keeps essential info visible without draining your battery too fast.",
          "CPU Type: Penta-Core",
          "CPU Speed: 1.6 GHz + 1.5 GHz",
          "RAM: 2GB",
          "Storage: 32GB",
          "Dial Shape: Round",
          "Display Size: 1.3\" (33.3 mm)",
          "Case Size: 44mm/ 40mm",
          "Display Technology: Super AMOLED",
          "Resolution: 432 x 4325",
          "Color Depth: 16M",
          "Operating System: Wear OS Powered by Samsung",
          "Capacity: 300mAh (Typical)",
          "Battery Life (AOD Off): Up to 40 hours",
          "Battery Life (AOD On): Up to 30 hours",
          "Charging: Fast charging supported",
          "Compatibility: Only compatible with Android OS",
          "Audio and Video Formats: MP3, M4A, 3GA, AAC, OGG, OGA, WAV, AMR, AWB",
          "Wi-Fi: 802.11 a/b/g/n (2.4 GHz + 5 GHz)",
          "Bluetooth: Version 5.3",
          "Bluetooth Profiles: A2DP, AVRCP, HFP, HSP",
          "GPS: GPS, Glonass, Beidou, Galileo",
        ],
      },
      {
        heading: "Powerful Performance with Penta-Core Processor",
        paragraphs: [
          "Powered by a Penta-Core CPU (1.6 GHz + 1.5 GHz) and 2GB of RAM, the Galaxy Watch 7 ensures smooth multitasking and rapid response times. Whether you're tracking your workout, answering messages, or checking the weather, you’ll enjoy fast, lag-free performance.",
        ],
      },
      {
        heading: "Store More With Storage",
        paragraphs: [
          "With 32GB of internal storage, you’ll have more than enough room for your favorite music, apps, and workout data. Say goodbye to limited space and hello to freedom on your wrist.",
        ],
      },
      {
        heading: "All-Day Battery Life",
        paragraphs: [
          "The 300mAh battery offers up to 40 hours of use with AOD off, and up to 30 hours with AOD on. It keeps going as long as you do — and when it’s time to recharge, it powers up quickly so you can get back to your day.",
        ],
      },
      {
        heading: "Advanced Health and Fitness Tracking",
        paragraphs: [
          "Equipped with a complete set of sensors, including an optical heart rate sensor, bioelectrical impedance analysis sensor, and infrared temperature sensor, the Galaxy Watch 7 offers 24/7 health tracking. Monitor your heart rate, sleep, body composition, stress levels, and even skin temperature, all from your wrist. Stay on course with built-in GPS, GLONASS, Beidou, and Galileo support. Whether you’re running, cycling, or hiking, your location data will be accurate and reliable in real time.",
        ],
      },
      {
        heading: "Seamless Connectivity & Smart Features",
        paragraphs: [
          "Running on Wear OS Powered by Samsung, the Galaxy Watch 7 is fully compatible with Android smartphones. Get notifications, make calls, stream music, and access your favorite apps all from your wrist. Featuring Bluetooth v5.3 and dual-band Wi-Fi (2.4 GHz + 5 GHz), the Galaxy Watch 7 ensures faster, more stable connections with your phone and other devices. Whether you're streaming a playlist or taking a call, the experience is seamless. Use tap-to-pay functionality and easy device pairing. Go wallet-free and stay secure with the power of your smartwatch.",
        ],
      },
      {
        heading: "Premium Build for Everyday Durability",
        paragraphs: [
          "With a slim profile of 40.4 x 40.4 x 9.7 mm and weighing just 28.8g, the Galaxy Watch 7 is designed for all-day comfort. Despite its light weight, it doesn’t compromise on durability built with 5 ATM water resistance, it can handle rain, splashes, and even swims. The classic 44mm round dial and smooth finish give it a modern yet timeless look, perfect for both workouts and formal events.",
        ],
      },
      {
        heading: "Buying the Galaxy Watch 7 from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
