/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/honor-magic-v3.jpeg";
import img2 from "@/images/products/honor-magic-v3/02-honor-magic-v3-green-1373.jpeg";
import img3 from "@/images/products/honor-magic-v3/03-honor-magic-v3-green-2447.jpeg";
import img4 from "@/images/products/honor-magic-v3/04-honor-magic-v3-green-3266.jpeg";
import img5 from "@/images/products/honor-magic-v3/05-honor-magic-v3-green-4289.jpeg";

export const honorMagicV3: ProductDetail = {
  breadcrumb: ["Phones", "HONOR"],
  gallery: [img1, img2, img3, img4, img5],
  inStock: true,

  highlights: [
    "Built with Special Aerospace Fiber",
    "Powerful Snapdragon 8 Gen 3 Processor",
    "5150mAh Powerful Battery",
    "Dual Display with AMOLED and OLED Display",
  ],

  colors: [
    { name: "Green", hex: "#008000", image: img1 },
  ],

  emi: { months: 12, perMonth: 15000 },

  specs: [
    {
      title: "Display",
      rows: [
        { label: "Size", value: ["Inner screen: 7.92 inches", "Outer screen: 6.43 inches"] },
        { label: "Type", value: ["Inner screen: foldable OLED", "Outer screen: OLED"] },
        { label: "Resolution", value: ["Inner screen: 2344x2156 Pixels", "Outer screen: 2376x1060 Pixels"] },
        { label: "Features", value: ["AI Defocus Display, 4320Hz PWM Flicker Free Dimming, Dynamic Dimming, Circadian Night Display, Nature Tone Display"] },
      ],
    },
    {
      title: "Processor",
      rows: [
        { label: "Chipset", value: ["Snapdragon 8 Gen 3"] },
        { label: "CPU Type", value: ["Octa-core"] },
        { label: "GPU", value: ["Adreno 750"] },
      ],
    },
    {
      title: "Memory",
      rows: [
        { label: "RAM", value: ["12GB"] },
        { label: "ROM", value: ["512GB"] },
      ],
    },
    {
      title: "Rear Camera",
      rows: [
        { label: "Resolution", value: ["40MP Ultra Wide Camera (f/2.2)", "50MP Wide Camera (f/1.6, OIS)", "50MP Telephoto Lens Camera (f/3.0, OIS)"] },
        { label: "Features", value: ["AI photography, Super Wide Angle, Aperture, Night, Portrait mode, Photo, Pro mode, Video, Panorama, Filter, Watermark, Scan Document, Super Macro, Capture smiles, Time-lapse, Timer, Movie, Slow-MO, Story"] },
        { label: "Video Recording", value: ["Support for 4K (3840×2160 pixels)"] },
      ],
    },
    {
      title: "Front Camera",
      rows: [
        { label: "Resolution", value: ["20MP Wide Camera (f/2.2) (Interior screen)", "20MP Wide Camera (f/2.2) (Exterior screen)"] },
        { label: "Features", value: ["Portrait, Filter, Watermark, Capture smiles, Mirror reflection, Timer, Night, Gesture control"] },
        { label: "Video Recording", value: ["Supported 4K (3840×2160 pixels)"] },
      ],
    },
    {
      title: "Audio",
      rows: [
        { label: "Audio Features", value: ["mp3/mp4/3gp/ogg/amr/aac/flac/wav/midi"] },
      ],
    },
    {
      title: "Network & AMP; Connectivity",
      rows: [
        { label: "SIM", value: ["SIM Card 1: Nano SIM card", "SIM Card 2: Nano SIM card / eSIM"] },
        { label: "Network", value: ["Support 5G/4G+/4G/3G/2G"] },
        { label: "Wi-Fi", value: ["2.4GHz and 5GHz"] },
        { label: "Bluetooth", value: ["Bluetooth 5.3, Support Bluetooth Low Energy, SBC, AAC, LDAC , AptX, AptX HD."] },
        { label: "GPS", value: ["Support GPS(L1+L5)"] },
        { label: "NFC", value: ["Support Reader/Writer Mode, Card Emulation Mode (SIM*, HCE)"] },
        { label: "USB", value: ["USB Type-C, USB 3.1 GEN1"] },
        { label: "OTG", value: ["Supported (maximum output current 1.5A/5V during reverse power supply)"] },
        { label: "Audio Jack", value: ["USB Type-C"] },
      ],
    },
    {
      title: "OS",
      rows: [
        { label: "Operating System", value: ["MagicOS 8.0.1 (Based on Android 14)", "User Interface: MagicOS 8.0.1"] },
      ],
    },
    {
      title: "Features",
      rows: [
        { label: "Fingerprint", value: ["Supported"] },
        { label: "Sensors", value: ["Gravity Sensor", "Barometer sensor", "Infrared Sensor", "Color temperature sensor", "Gyroscope", "Compass", "Hall sensor", "Ambient Light Sensor", "Proximity Sensor"] },
        { label: "IP Rating", value: ["IPX8"] },
      ],
    },
    {
      title: "Battery",
      rows: [
        { label: "Type", value: ["Lithium polymer battery (HONOR Third-generation Silicon-carbon Battery)", "5150mAh (typical value), 5050 mAh (rated value)"] },
        { label: "Fast Charging", value: ["Wired Charging: 66W HONOR SuperCharge", "The phone supports up to 11V/6A SuperCharge, compatible with 10V/4A and 5V/2A.", "Standard Charger: HONOR 66W SuperCharge Charger", "Wireless Charging: 50W Wireless HONOR SuperCharge"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["Height 156.6mm", "Width folded: 74.0mm unfolded: 145.3mm", "Depth Black Version: folded: 9.2mm unfolded: 4.35mm", "Other Version:- folded: 9.3mm", "unfolded: 4.4mm"] },
        { label: "Weight", value: ["Black Version: Approx. 226 g (including the battery)", "Other Version: Approx. 230 g (including the battery)"] },
      ],
    },
  ],

  description: {
    title: "HONOR Magic V3 12/512GB",
    blocks: [
      {
        paragraphs: [
          "The HONOR Magic V3 redefines what a foldable smartphone can be. Combining cutting-edge technology with sleek design, this device offers unmatched performance and versatility, making it the perfect choice for those seeking a premium, all-in-one mobile experience. Whether you’re a tech enthusiast, a professional, or someone who loves innovative gadgets, the HONOR Magic V3 has everything you need",
        ],
      },
      {
        heading: "Features of HONOR Magic V3",
        paragraphs: [
          "Stunning Display for Unmatched Visuals, Exceptional Performance with Snapdragon 8 Gen 3, Capture Every Moment with Pro-Grade Cameras, Long-Lasting Power and Rapid Charging.",
        ],
      },
      {
        heading: "Stunning Display for Unmatched Visuals",
        paragraphs: [
          "With a large 7.92-inch foldable OLED inner screen and a 6.43-inch OLED outer screen, the HONOR Magic V3 delivers stunning visuals for every task. The high-resolution displays, 2344x2156 pixels for the inner screen and 2376x1060 pixels for the outer screen, ensure crisp and vibrant images. Features like AI Defocus Display, 4320Hz PWM Flicker-Free Dimming, Dynamic Dimming, and Circadian Night Display enhance your viewing experience, providing smoother and more comfortable screen usage, even in low light. Whether you’re watching videos, browsing, or multitasking, the display adapts to your needs.",
        ],
      },
      {
        heading: "Exceptional Performance with Snapdragon 8 Gen 3",
        paragraphs: [
          "Under the hood, the HONOR Magic V3 is powered by the latest Snapdragon 8 Gen 3 chipset, coupled with an octa-core CPU and Adreno 750 GPU. This powerhouse ensures lightning-fast processing, seamless multitasking, and stunning graphics, all while keeping energy consumption in check. With 12GB of RAM and 512GB of ROM, you’ll have ample storage and smooth performance for everything from gaming to productivity.",
        ],
      },
      {
        heading: "Capture Every Moment with Pro-Grade Cameras",
        paragraphs: [
          "Photography enthusiasts will love the HONOR Magic V3’s versatile camera setup. The rear cameras include a 40MP Ultra Wide Camera, a 50MP Wide Camera, and a 50MP Telephoto Lens, all designed to capture stunning images in any lighting condition. With features like AI photography, Super Wide Angle, Night mode, and 4K video recording, your photos and videos will have professional-quality clarity. The front cameras, both 20MP, offer crystal-clear selfies and support 4K video recording, ensuring you always look your best in every shot.",
        ],
      },
      {
        heading: "Long-Lasting Power and Rapid Charging",
        paragraphs: [
          "The HONOR Magic V3 features a powerful 5150mAh battery that provides all-day usage, whether you're working, streaming, or gaming. With 66W wired HONOR SuperCharge and 50W wireless charging capabilities, you can quickly recharge your phone and get back to what matters most without waiting around. The advanced battery technology, including HONOR’s third-generation silicon-carbon battery, ensures both efficiency and longevity.",
        ],
      },
      {
        heading: "Buying the HONOR Magic V3 12/512GB from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
