/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/honor-x9d.jpeg";
import img2 from "@/images/products/honor-x9d/02-honor-x9d-brown-1614.jpeg";
import img3 from "@/images/products/honor-x9d/03-honor-x9d-brown-2997.jpeg";
import img4 from "@/images/products/honor-x9d/04-honor-x9d-black721.jpeg";
import img5 from "@/images/products/honor-x9d/05-honor-x9d-black-1197.jpeg";
import img6 from "@/images/products/honor-x9d/06-honor-x9d-black-2559.jpeg";
import img7 from "@/images/products/honor-x9d/07-honor-x9d-gold541.jpeg";
import img8 from "@/images/products/honor-x9d/08-honor-x9d-gold-1351.jpeg";
import img9 from "@/images/products/honor-x9d/09-honor-x9d-gold-2581.jpeg";

export const honorX9d: ProductDetail = {
  breadcrumb: [
    { label: "Phones", slug: "phone" },
    { label: "HONOR", slug: "honor-mobile-phone" },
  ],
  gallery: [img1, img2, img3, img4, img5, img6, img7, img8, img9],
  inStock: true,

  highlights: [
    "Display: 6.79 inches",
    "Processor: Snapdragon 6 Gen 4",
    "Camera: 108MP + 5MP + 16MP",
    "Features: Under-display optical fingerprint sensor",
  ],

  colors: [
    { name: "Reddish Brown", hex: "#CC5D49", image: img1 },
    { name: "Midnight Black", hex: "#1E2126", image: img4 },
    { name: "Sunrise Gold", hex: "#FFE292", image: img7 },
  ],

  emi: { months: 12, perMonth: 3917 },

  specs: [
    {
      title: "Display",
      rows: [
        { label: "Size", value: ["6.79 inches"] },
        { label: "Type", value: ["AMOLED"] },
        { label: "Resolution", value: ["2640*1200"] },
        { label: "Brightness", value: ["800 nits (typical) 1800 nits (HBM type) 6000 nits (APL type)"] },
        { label: "Features", value: ["100% DCI-P3,1.07 billion colors, Eye Comfort/Circadian Night Display/Dynamic Dimming/3840Hz PWM risk-free Dimming, Aluminosilicate glass."] },
      ],
    },
    {
      title: "Processor",
      rows: [
        { label: "Chipset", value: ["Snapdragon 6 Gen 4"] },
        { label: "CPU Type", value: ["Octa-core"] },
        { label: "CPU Speed", value: ["1× A720*2.3GHz + 3× A720*2.2GHz+ 4× A520*1.8GHz"] },
        { label: "GPU", value: ["Adreno A810"] },
      ],
    },
    {
      title: "Memory",
      rows: [
        { label: "RAM", value: ["12GB"] },
        { label: "ROM", value: ["256GB"] },
      ],
    },
    {
      title: "Rear Camera",
      rows: [
        { label: "Resolution", value: ["108MP + 5MP"] },
        { label: "Features", value: ["10X Digital zoom, Image Resolution: Supported 12000*9000 pixels, Video Resolution: Supported 3840*2160 pixels, Rear single LED flash, Capture Mode: Highlights Capture, Moving Photo, AI photography,Aperture, Night, Portrait(including beauty mode), Pro, Panorama, Filter,time-lapse photography,High-res,Capture smile,Slow-motion,Wide Angle, Multi-Video, Watermark, Scan Document,Timer, Stabilization Mode: OIS."] },
        { label: "Video Recording", value: ["Supported 4K pixels"] },
      ],
    },
    {
      title: "Front Camera",
      rows: [
        { label: "Resolution", value: ["16MP"] },
        { label: "Features", value: ["Image Resolution: Supported 3456x4608 pixels, Video Resolution: Support 2520x1080 pixels, Capture Mode: Portrait (including beauty mode), Moving Photo, Filter, Capture smile, Mirror reflection, Timer, Gesture control."] },
        { label: "Video Recording", value: ["Support 1080P (up to 2520x1080) video recording"] },
      ],
    },
    {
      title: "Audio",
      rows: [
        { label: "Audio Features", value: ["Sound Effect: HONOR Sound 7.3"] },
      ],
    },
    {
      title: "Network & AMP; Connectivity",
      rows: [
        { label: "SIM", value: ["2 Sim (Nano SIM card)"] },
        { label: "Network", value: ["5G:NR", "4G (LTE FDD/TDD)", "3G (WCDMA)", "2G (GSM)"] },
        { label: "Wi-Fi", value: ["Support Wi-Fi 6 (802.11 ax) and 802.11 a/b/g/n/ac", "Support 1024 QAM, 80MHz", "Support 2.4GHz and 5GHz", "Support Wi-Fi Direct & Wi-Fi Hotspot"] },
        { label: "Bluetooth", value: ["BT5.2, Support BLE, SBC,AAC,LDAC,APTX,APTX HD, AptX Adaptive"] },
        { label: "GPS", value: ["GPS/AGPS/Glonass/BeiDou/Galileo"] },
        { label: "NFC", value: ["Supported"] },
        { label: "USB", value: ["Type-C, USB 2.0"] },
        { label: "OTG", value: ["OTG (the maximum output current is 5V/1.5A)"] },
        { label: "Audio Jack", value: ["Type-C digital"] },
      ],
    },
    {
      title: "OS",
      rows: [
        { label: "Operating System", value: ["MagicOS 9.0(Android 15)"] },
      ],
    },
    {
      title: "Features",
      rows: [
        { label: "Fingerprint", value: ["Under-display optical fingerprint sensor"] },
        { label: "Sensors", value: ["Gravity Sensor", "Fingerprint Sensor", "Gyroscope", "Compass", "Acceleration Sensor", "Ambient Light Sensor", "Proximity Sensor"] },
        { label: "IP Rating", value: ["IP66 & IP68 & IP69 & IP69K"] },
      ],
    },
    {
      title: "Battery",
      rows: [
        { label: "Type", value: ["Li-ion Polymer Battery (8300 mAh)"] },
        { label: "Fast Charging", value: ["The phone supports up to 20V/3.3A super-fast charging"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["Height: 161.9mm", "Width: 76.1mm", "Depth: 7.76mm"] },
        { label: "Weight", value: ["Approx. 193g (including the battery)"] },
        { label: "Colors", value: ["Reddish Brown, Midnight Black, Sunrise Gold"] },
      ],
    },
  ],

  description: {
    title: "HONOR X9d 5G (12/256GB)",
    blocks: [
      {
        paragraphs: [
          "Meet the HONOR X9d 5G (12/256GB)—a powerful, future-ready smartphone designed for users who want premium performance, stunning visuals, and long-lasting battery life in one sleek device. Built with an immersive AMOLED display, a high-resolution 108MP camera, and an ultra-large battery, the HONOR X9d delivers a smooth and reliable experience whether you’re streaming, gaming, working, or capturing life’s moments. It’s a smart choice for anyone looking for a balanced 5G smartphone with flagship-inspired features at a competitive value.",
        ],
      },
      {
        heading: "Key Features of HONOR X9d 5G",
        paragraphs: [
          "The HONOR X9d combines a large AMOLED display with advanced eye protection, powerful Snapdragon performance, high-resolution cameras, ultra-durable design, and a huge battery. With modern connectivity options like 5G, Wi-Fi 6, and NFC, it delivers a complete smartphone experience tailored for today’s fast-paced lifestyle.",
          "Display: 6.79-inch AMOLED display",
          "Resolution: 2640 × 1200 pixels",
          "Brightness: 800 nits (typical), 1800 nits (HBM), up to 6000 nits (APL)",
          "100% DCI-P3 color gamut with 1.07 billion colors",
          "Eye Comfort, Circadian Night Display & Dynamic Dimming support",
          "3840Hz PWM risk-free dimming",
          "Durable aluminosilicate glass protection",
          "Qualcomm Snapdragon 6 Gen 4 chipset",
          "Adreno A810 GPU",
          "12GB RAM",
          "256GB internal storage",
          "Rear Camera: Dual camera setup 108MP + 5MP",
          "Front Camera: 16MP selfie camera",
          "HONOR Sound 7.3 sound effects",
          "USB Type-C digital audio (no 3.5mm jack)",
          "Dual Nano SIM support",
          "5G NR, 4G LTE (FDD/TDD), 3G WCDMA & 2G GSM",
          "Wi-Fi 6 (802.11ax), dual-band 2.4GHz & 5GHz",
          "Bluetooth 5.2 with SBC, AAC, LDAC, aptX, aptX HD & aptX Adaptive",
          "GPS, AGPS, GLONASS, BeiDou & Galileo",
          "NFC support",
          "USB Type-C (USB 2.0)",
          "OTG support (up to 5V/1.5A output)",
          "Under-display optical fingerprint sensor",
          "Gravity sensor, accelerometer, gyroscope & compass",
          "Ambient light & proximity sensors",
          "IP66, IP68, IP69 & IP69K water and dust resistance",
          "Massive 8300mAh Li-ion polymer battery",
          "Supports super-fast charging up to 20V / 3.3A",
        ],
      },
      {
        heading: "Immersive AMOLED Display with Advanced Eye Comfort",
        paragraphs: [
          "The HONOR X9d features a large 6.79-inch AMOLED display that brings content to life with rich contrast and vibrant colors. With a 2640 × 1200 resolution, everything looks sharp, detailed, and immersive—perfect for watching videos, browsing social media, or playing games. Thanks to 100% DCI-P3 color gamut and support for 1.07 billion colors, visuals appear more natural and cinematic. The display is also engineered for comfort, featuring Eye Comfort technology, Circadian Night Display, and Dynamic Dimming to reduce eye strain during extended use. With 3840Hz PWM risk-free dimming, the screen remains comfortable even at low brightness levels.",
        ],
      },
      {
        heading: "Smooth Performance Powered by Snapdragon 6 Gen 4",
        paragraphs: [
          "At the heart of the HONOR X9d is the Qualcomm Snapdragon 6 Gen 4 chipset, designed to deliver efficient performance with improved power management. Paired with the Adreno A810 GPU, the phone handles daily multitasking, gaming, and media consumption with ease. With 12GB of RAM, switching between apps feels fluid, while the 256GB of internal storage gives you plenty of space for photos, videos, apps, and documents without worrying about running out of room. Whether you’re working on the go or enjoying entertainment, the HONOR X9d keeps everything running smoothly.",
        ],
      },
      {
        heading: "108MP AI Camera for High-Resolution Photography",
        paragraphs: [
          "Capture stunning details with the 108MP dual rear camera system, supported by an additional 5MP sensor for enhanced depth and versatility. The high-resolution main camera allows you to take sharp, detailed photos that hold up even when cropped or zoomed. Advanced AI photography features help optimize scenes automatically, delivering clear shots in various lighting conditions. From everyday photos to special moments, the HONOR X9d ensures reliable image quality. On the front, the 16MP selfie camera delivers clear and natural-looking selfies, ideal for video calls and social media sharing.",
        ],
      },
      {
        heading: "Immersive Audio Experience with HONOR Sound 7.3",
        paragraphs: [
          "Audio on the HONOR X9d is enhanced with HONOR Sound 7.3, delivering clearer, more immersive sound for music, movies, and gaming. The phone uses USB Type-C digital audio, offering modern audio compatibility and cleaner sound output for supported accessories.",
        ],
      },
      {
        heading: "Next-Generation Connectivity with 5G and Wi-Fi 6",
        paragraphs: [
          "Stay connected at high speed with full 5G NR support, alongside 4G LTE, 3G, and 2G networks for wide compatibility. The HONOR X9d supports dual Nano SIM, making it ideal for users who manage work and personal numbers on one device. For wireless connectivity, Wi-Fi 6 (802.11ax) ensures faster speeds, improved stability, and better performance in crowded networks. Bluetooth 5.2 offers strong and efficient connections with support for high-quality audio codecs such as AAC, LDAC, aptX, aptX HD, and aptX Adaptive. Additional features like NFC, GPS with multiple global systems, and OTG support further enhance everyday convenience.",
        ],
      },
      {
        heading: "Secure Unlocking and Smart Sensors",
        paragraphs: [
          "Security is seamless and intuitive with the under-display optical fingerprint sensor, allowing quick and secure access to your phone. The HONOR X9d is also equipped with a full range of sensors, including accelerometer, gyroscope, compass, ambient light, and proximity sensors, ensuring accurate responsiveness across apps and features.",
        ],
      },
      {
        heading: "Exceptional Durability with Advanced IP Ratings",
        paragraphs: [
          "Built for real-world use, the HONOR X9d stands out with IP66, IP68, IP69, and IP69K ratings, offering high-level protection against dust, water, and even high-pressure water exposure. This makes it a reliable companion for users who need extra durability in challenging environments.",
        ],
      },
      {
        heading: "Massive 8300mAh Battery with Super-Fast Charging",
        paragraphs: [
          "One of the biggest highlights of the HONOR X9d is its massive 8300mAh Li-ion polymer battery, designed to last through long days of use without constant recharging. Whether you’re streaming, browsing, or gaming, this phone is built to keep up. When it’s time to recharge, super-fast charging support up to 20V / 3.3A helps you get back to full power quickly and efficiently, minimizing downtime.",
        ],
      },
      {
        heading: "Buying the HONOR X9d 5G (12/256GB) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
