/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/honor-watch-5-ultra-fluororubber-strap.jpeg";
import img2 from "@/images/products/honor-watch-5-ultra-fluororubber-strap/02-honor-watch-5-ultra-fluororubber-strap-2.jpeg";
import img3 from "@/images/products/honor-watch-5-ultra-fluororubber-strap/03-honor-watch-5-ultra-fluororubber-strap-1.jpeg";
import img4 from "@/images/products/honor-watch-5-ultra-fluororubber-strap/04-honor-watch-5-ultra-fluororubber-strap.jpeg";
import img5 from "@/images/products/honor-watch-5-ultra-fluororubber-strap/05-honor-watch-5-ultra-fluororubber-strap-4.jpeg";

export const honorWatch5UltraFluororubberStrap: ProductDetail = {
  breadcrumb: [
    { label: "Watches", slug: "watch" },
    { label: "Smart Watch", slug: "smart-watch" },
    { label: "HONOR", slug: "honor-smart-watch" },
  ],
  gallery: [img1, img2, img3, img4, img5],
  inStock: true,

  highlights: [
    "Dial Size: 1.5 inches",
    "Wrist Size: 140-210mm",
    "Technology: LTPO AMOLED",
    "Resolution: 466 x 466pixels, 310PPI",
  ],

  colors: [
    { name: "Black", hex: "#000000", image: img1 },
  ],

  emi: { months: 6, perMonth: 5500 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["HONOR"] },
        { label: "Model Name", value: ["Watch 5 Ultra"] },
      ],
    },
    {
      title: "Main Features",
      rows: [
        { label: "Sensors", value: ["Accelerometer sensor", "Gyroscope sensor", "Magnetometer sensor", "Optical heart rate sensor", "Barometer sensor", "Ambient light sensor"] },
        { label: "Operating System", value: ["Android 9.0 or later and iOS 13.0 or later"] },
        { label: "Battery", value: ["480 mAh battery"] },
        { label: "Charging", value: ["Wireless charging", "Charger Voltage and Current: 5V-9V DC / 2A"] },
        { label: "Buttons", value: ["Up button, Down button", "supports press and hold", "Up button supports the rotation of the crown"] },
        { label: "Others", value: ["Speaker: Supported", "Microphone: Supported"] },
      ],
    },
    {
      title: "Display",
      rows: [
        { label: "Dial Shape", value: ["Round"] },
        { label: "Dial Size", value: ["1.5 inches"] },
        { label: "Technology", value: ["LTPO AMOLED"] },
        { label: "Resolution", value: ["466 x 466pixels, 310PPI"] },
      ],
    },
    {
      title: "Connectivity",
      rows: [
        { label: "Bluetooth", value: ["2.4 GHz, BT 5.2, supports BLE/BR/EDR"] },
        { label: "GPS", value: ["GPS+GLONASS+GALILEO+BDS+QZSS"] },
      ],
    },
    {
      title: "Physical Dimension",
      rows: [
        { label: "Material", value: ["Titanium alloy case", "polymer fiber composite back cover.", "Strap: Fluoroelastomer strap"] },
        { label: "Water Rating", value: ["5ATM, IP68"] },
        { label: "Dimensions", value: ["46.3mm×46.3mm×11.4mm"] },
        { label: "Weight", value: ["Approximately 51.8g (without the strap)"] },
        { label: "Color", value: ["Black"] },
      ],
    },
  ],

  description: {
    title: "HONOR Watch 5 Ultra Fluororubber Strap (46mm)",
    blocks: [
      {
        paragraphs: [
          "The HONOR Watch 5 Ultra Fluororubber Strap (46mm) is a premium smartwatch built for users who want advanced health tracking, professional-grade durability, and modern smart features in one elegant wearable. Featuring a rugged titanium alloy case, a comfortable fluororubber strap, and a brilliant LTPO AMOLED display, this flagship HONOR smartwatch is designed to support fitness, productivity, and everyday convenience. Whether you're an athlete, professional, or tech enthusiast, the Watch 5 Ultra delivers a premium smartwatch experience with style and performance.",
        ],
      },
      {
        heading: "Premium Titanium Design with Durable Fluororubber Strap",
        paragraphs: [
          "Designed for active lifestyles, the HONOR Watch 5 Ultra combines a high-strength titanium alloy case with a skin-friendly fluororubber strap. The strap offers excellent flexibility, sweat resistance, and long-lasting comfort, making it ideal for workouts, outdoor adventures, and daily wear. Its lightweight design, weighing approximately 51.8g without the strap, ensures all-day comfort without compromising durability.",
        ],
      },
      {
        heading: "Stunning 1.5-Inch LTPO AMOLED Display",
        paragraphs: [
          "Enjoy crystal-clear visuals on the large 1.5-inch LTPO AMOLED display. With a sharp 466 × 466 resolution and 310 PPI pixel density, the screen delivers vibrant colors, deep blacks, and excellent visibility in various lighting conditions. The advanced LTPO technology helps optimize power consumption while maintaining a smooth and responsive user experience.",
        ],
      },
      {
        heading: "Advanced Health Monitoring and Smart Sensors",
        paragraphs: [
          "The HONOR Watch 5 Ultra is equipped with an extensive suite of intelligent sensors that help you stay informed about your health and daily activities. The optical heart rate sensor continuously tracks heart performance, while the accelerometer, gyroscope, magnetometer, barometer, and ambient light sensor provide accurate fitness, movement, and environmental data. This combination makes the smartwatch a reliable companion for wellness monitoring and activity tracking.",
        ],
      },
      {
        heading: "Accurate Multi-System GPS Tracking",
        paragraphs: [
          "For outdoor sports and navigation, the HONOR Watch 5 Ultra supports multiple global satellite systems, including GPS, GLONASS, GALILEO, BDS, and QZSS. This advanced positioning technology delivers precise route tracking and location accuracy, making it perfect for running, cycling, hiking, and other outdoor activities.",
        ],
      },
      {
        heading: "Long-Lasting Battery with Wireless Charging",
        paragraphs: [
          "Powered by a robust 480mAh battery, the HONOR Watch 5 Ultra is designed to keep up with your daily routine. The smartwatch supports convenient wireless charging, eliminating cable clutter and ensuring a hassle-free charging experience. With efficient power management, you can enjoy extended usage between charges.",
        ],
      },
      {
        heading: "Seamless Connectivity and Smart Controls",
        paragraphs: [
          "The smartwatch features Bluetooth 5.2 technology with BLE, BR, and EDR support, ensuring fast and stable connectivity with compatible Android 9.0+ and iOS 13.0+ devices. Built-in speaker and microphone support enable smart communication features, while the rotating crown and dual-button controls provide intuitive navigation through apps and settings.",
        ],
      },
      {
        heading: "Built to Withstand Everyday Challenges",
        paragraphs: [
          "Engineered for durability, the HONOR Watch 5 Ultra comes with both IP68 dust and water resistance and a 5ATM water rating. Whether you're training in the gym, caught in the rain, or exploring the outdoors, this premium smartwatch is built to handle demanding environments with confidence.",
        ],
      },
      {
        heading: "Buying the HONOR Watch 5 Ultra Fluororubber Strap (46mm) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
