/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/infinix-hot-70-6gb-128gb.jpeg";
import img2 from "@/images/products/infinix-hot-70-6gb-128gb/02-infinix-hot-70-night-pulse.jpeg";
import img3 from "@/images/products/infinix-hot-70-6gb-128gb/03-infinix-hot-70-night-pulse-1.jpeg";
import img4 from "@/images/products/infinix-hot-70-6gb-128gb/04-infinix-hot-70-night-pulse-2.jpeg";
import img5 from "@/images/brands/infinix-hot-70-8gb-128gb.jpeg";
import img6 from "@/images/products/infinix-hot-70-6gb-128gb/06-infinix-hot-70-silvet-dancer.jpeg";
import img7 from "@/images/products/infinix-hot-70-6gb-128gb/07-infinix-hot-70-silvet-dancer-1.jpeg";
import img8 from "@/images/products/infinix-hot-70-6gb-128gb/08-infinix-hot-70-silvet-dancer-2.jpeg";
import img9 from "@/images/products/infinix-hot-70-6gb-128gb/09-infinix-hot-70-thermo-orange-5.jpeg";
import img10 from "@/images/products/infinix-hot-70-6gb-128gb/10-infinix-hot-70-thermo-orange.jpeg";
import img11 from "@/images/products/infinix-hot-70-6gb-128gb/11-infinix-hot-70-thermo-orange-1.jpeg";
import img12 from "@/images/products/infinix-hot-70-6gb-128gb/12-infinix-hot-70-thermo-orange-2.jpeg";
import img13 from "@/images/products/infinix-hot-70-6gb-128gb/13-infinix-hot-70-dive-blue-4.jpg.jpeg";
import img14 from "@/images/products/infinix-hot-70-6gb-128gb/14-infinix-hot-70-dive-blue.jpeg";
import img15 from "@/images/products/infinix-hot-70-6gb-128gb/15-infinix-hot-70-dive-blue-1.jpeg";
import img16 from "@/images/products/infinix-hot-70-6gb-128gb/16-infinix-hot-70-dive-blue-2.jpeg";

export const infinixHot706gb128gb: ProductDetail = {
  breadcrumb: [
    { label: "Phones", slug: "phone" },
    { label: "Infinix", slug: "infinix-mobile-phone" },
  ],
  gallery: [img1, img2, img3, img4, img5, img6, img7, img8, img9, img10, img11, img12, img13, img14, img15, img16],
  inStock: true,

  highlights: [
    "Processor: MediaTek Helio G100 Ultimate",
    "Display: 120Hz 6.78\" HD+ LCD Ultra-Bright",
    "Battery: 6000mAh 45W",
    "Camera: 50MP + 8MP",
  ],

  colors: [
    { name: "Night Pulse", hex: "#8B8B8C", image: img1 },
    { name: "Silver Dancer", hex: "#E7E9E8", image: img5 },
    { name: "Thermo Orange", hex: "#EF995E", image: img9 },
    { name: "Dive Blue", hex: "#7C91C8", image: img13 },
  ],

  emi: { months: 6, perMonth: 4167 },

  specs: [
    {
      title: "Display",
      rows: [
        { label: "Size", value: ["6.78 inches"] },
        { label: "Type", value: ["IPS a-Si"] },
        { label: "Resolution", value: ["HD+ 720*1576"] },
        { label: "Refresh Rate", value: ["60Hz/90Hz/120Hz"] },
        { label: "Brightness", value: ["560 nits (TYP), 700 nits (HBM Brightness)"] },
        { label: "Features", value: ["Always-On Display"] },
      ],
    },
    {
      title: "Processor",
      rows: [
        { label: "Chipset", value: ["MediaTek Helio G100 Ultimate"] },
        { label: "CPU Type", value: ["Octa-core"] },
        { label: "CPU Speed", value: ["2x2.2 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55"] },
        { label: "GPU", value: ["Mali-G57 MC2"] },
      ],
    },
    {
      title: "Memory",
      rows: [
        { label: "RAM", value: ["6GB"] },
        { label: "ROM", value: ["128GB"] },
        { label: "Card Slot", value: ["2 nano SIMs + Micro SD"] },
      ],
    },
    {
      title: "Rear Camera",
      rows: [
        { label: "Resolution", value: ["50MP"] },
        { label: "Features", value: ["f/1.85, FOV 75.5°, AF supported"] },
      ],
    },
    {
      title: "Front Camera",
      rows: [
        { label: "Resolution", value: ["8MP"] },
        { label: "Features", value: ["f/2.0, FOV 77.7°, FF supported"] },
      ],
    },
    {
      title: "Network & AMP; Connectivity",
      rows: [
        { label: "SIM", value: ["2 nano SIMs"] },
        { label: "Network", value: ["4G/3G/2G"] },
        { label: "Wi-Fi", value: ["Wi-Fi 802.11 (a/b/g/n/ac)"] },
        { label: "Bluetooth", value: ["Bluetooth 5.4"] },
        { label: "GPS", value: ["Yes"] },
        { label: "NFC", value: ["Yes"] },
        { label: "USB", value: ["USB Type-C"] },
        { label: "OTG", value: ["Yes"] },
      ],
    },
    {
      title: "OS",
      rows: [
        { label: "Operating System", value: ["XOS 16, Powered by AndroidTM 16"] },
      ],
    },
    {
      title: "Features",
      rows: [
        { label: "Fingerprint", value: ["Side Fingerprint"] },
        { label: "Sensors", value: ["G-sensor", "E-Compass", "Gyroscope", "Light Sensor", "Proximity Sensor", "Motor", "Infrared Blaster"] },
        { label: "IP Rating", value: ["IP64"] },
      ],
    },
    {
      title: "Battery",
      rows: [
        { label: "Type", value: ["6000mAh"] },
        { label: "Fast Charging", value: ["45W"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["167.92mm*79.12mm*7.49mm"] },
        { label: "Weight", value: ["195g"] },
        { label: "Body Material", value: ["LCD"] },
        { label: "Colors", value: ["Night Pulse, Dive Blue, Silver Dancer, Thermo Orange"] },
      ],
    },
  ],

  description: {
    title: "Infinix Hot 70 (6/128GB)",
    blocks: [
      {
        paragraphs: [
          "The Infinix Hot 70 (6/128GB) brings together stylish design, smooth performance, and long-lasting battery life at an affordable price, making it a perfect daily driver for modern smartphone users. Built for entertainment, multitasking, and social media, this device offers great value with its large display, capable processor, and reliable camera setup.",
        ],
      },
      {
        heading: "Large 6.78\" Display with Smooth Refresh Rate",
        paragraphs: [
          "Enjoy an immersive viewing experience on the 6.78-inch IPS display with HD+ resolution. Whether you're watching videos, browsing social media, or gaming, the screen delivers vibrant visuals and comfortable brightness levels up to 700 nits (HBM). With support for 60Hz, 90Hz, and 120Hz refresh rates, you can experience smoother scrolling and responsive interactions based on your usage. The Always-On Display feature adds convenience, allowing you to check notifications, time, and essential updates without unlocking your phone.",
        ],
      },
      {
        heading: "Efficient Performance with Helio G100 Ultimate",
        paragraphs: [
          "Powered by the MediaTek Helio G100 Ultimate processor, the Infinix Hot 70 ensures smooth day-to-day performance. The octa-core CPU, paired with the Mali-G57 MC2 GPU, handles multitasking, casual gaming, and everyday apps with ease. With 6GB RAM and 128GB internal storage, you get enough space and speed to run apps and store your photos, videos, and files. Plus, the dedicated microSD card slot allows further expansion.",
        ],
      },
      {
        heading: "50MP Camera for Clear Everyday Shots",
        paragraphs: [
          "Capture your moments with the 50MP rear camera that delivers sharp and detailed photos in different lighting conditions. With autofocus support and a wide aperture, the camera performs well for daily photography. The 8MP front camera is perfect for selfies, video calls, and social media updates, ensuring decent clarity and natural colors.",
        ],
      },
      {
        heading: "Massive 6000mAh Battery with Fast Charging",
        paragraphs: [
          "Stay powered throughout the day with the large 6000mAh battery, ideal for heavy users who stream, browse, and game regularly. The 45W fast charging support ensures quick top-ups, so you spend less time charging and more time using your device.",
        ],
      },
      {
        heading: "Modern Design with Durable Build",
        paragraphs: [
          "The Infinix Hot 70 features a slim and stylish design despite its big battery, weighing just 195g. Available in trendy colors like Night Pulse, Dive Blue, Silver Dancer, and Thermo Orange, the phone stands out with a modern aesthetic. With an IP64 rating, the device offers protection against dust and splashes, making it more durable for everyday use.",
        ],
      },
      {
        heading: "Advanced Connectivity and Smart Features",
        paragraphs: [
          "Stay connected with dual SIM support, 4G connectivity, Wi-Fi, and Bluetooth 5.4 for faster and stable connections. The inclusion of NFC makes contactless payments and file sharing easier. It also features an infrared blaster, allowing you to control home appliances directly from your phone. Running on XOS 16 based on Android 16, the device offers a smooth and customizable user experience with smart features and improved performance.",
        ],
      },
      {
        heading: "Secure and Convenient Unlock",
        paragraphs: [
          "The side-mounted fingerprint sensor ensures quick and secure access to your phone, while additional sensors enhance usability and device interaction.",
        ],
      },
      {
        heading: "Buying the Infinix Hot 70 (6/128GB) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
