/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/infinix-xpad-20.jpeg";
import img2 from "@/images/products/infinix-xpad-20/02-infinix-xpad-20625.jpeg";

export const infinixXpad20: ProductDetail = {
  breadcrumb: ["Tablets", "Infinix"],
  gallery: [img1, img2],
  inStock: true,

  highlights: [
    "11\" 90Hz FHD+ Eye Care Display",
    "Helio G88 with 4G LTE Connected",
    "128GB ROM + 6GB RAM",
    "7000mAh Battery",
  ],

  colors: [
    { name: "Stellar Grey", hex: "#949697", image: img1 },
  ],

  emi: { months: 6, perMonth: 3333 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["Infinix"] },
        { label: "Model Name", value: ["Xpad 20"] },
      ],
    },
    {
      title: "Main Feature",
      rows: [
        { label: "Display Type", value: ["IPS"] },
        { label: "Size", value: ["11\""] },
        { label: "Resolution", value: ["FHD+ 1200*1920"] },
        { label: "RAM", value: ["6 GB"] },
        { label: "Storage", value: ["128 GB"] },
        { label: "Processor", value: ["CPU: Octa-core (2x2.0 GHz Cortex-A75 & 6x1.8 GHz Cortex-A55)", "GPU: Mali-G52 2EEMC2"] },
        { label: "Operating System", value: ["Android 15"] },
        { label: "Connectivity", value: ["SIM Card Slot: 1 Nano SIM + MicroSD", "WiFi"] },
        { label: "Audio", value: ["MP3, FLAC, OGG, OGA,WAV, AAC, AMR, AWB, APE, MIDI"] },
        { label: "Others", value: ["CHIPSET: MediaTek Helio G88"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Weight", value: ["498g"] },
        { label: "SIM", value: ["1 nano SIM + Micro SD"] },
        { label: "Color", value: ["Stellar Grey"] },
      ],
    },
    {
      title: "Camera",
      rows: [
        { label: "Front Camera", value: ["5MP"] },
        { label: "Rear Camera", value: ["8MP"] },
        { label: "Video", value: ["1080P 30FPS/720P 30FPS"] },
      ],
    },
    {
      title: "Battery",
      rows: [
        { label: "Capacity", value: ["7000mAh"] },
        { label: "Charging", value: ["10W"] },
      ],
    },
    {
      title: "Special Features",
      rows: [
        { label: "Sensors", value: ["G-SENSOR"] },
        { label: "Bluetooth", value: ["Bluetooth 5.2"] },
        { label: "WLAN", value: ["Wi-Fi 802.11 (a/b/g/n/ac)"] },
        { label: "GPS", value: ["YES"] },
        { label: "USB", value: ["USB TYPE-C"] },
      ],
    },
  ],

  description: {
    title: "Infinix Xpad 20",
    blocks: [
      {
        paragraphs: [
          "The Infinix Xpad 20 is the ultimate Android Tablet for anyone who needs a perfect balance of style, performance, and functionality. Built for entertainment, productivity, and learning, it combines an expansive 11-inch Full HD+ display, a powerful MediaTek Helio G88 processor, and a massive 7000mAh battery to keep up with your busy lifestyle. Whether you’re streaming high-definition movies, working on important documents, attending virtual classes, or simply browsing social media, the Infinix Xpad 20 delivers a smooth, lag-free experience every time. With its premium Stellar Grey finish and lightweight design, it’s also easy to carry anywhere, making it an ideal choice for students, professionals, and travelers alike.",
        ],
      },
      {
        heading: "Infinix Xpad 20 Specifications",
        paragraphs: [
          "Enjoy every detail with the 11-inch Full HD+ 1200×1920 IPS display that delivers vibrant colors and sharp visuals. The wide viewing angles make it perfect for watching movies, reading eBooks, or browsing the web. With its immersive screen size, you can enjoy split-screen multitasking, making it ideal for both work and play.",
          "Display: 11-inch IPS, Full HD+ (1200 × 1920 resolution)",
          "Processor: MediaTek Helio G88, Octa-core (2x2.0 GHz Cortex-A75 & 6x1.8 GHz Cortex-A55)",
          "GPU: Mali-G52 2EEMC2",
          "RAM: 6GB",
          "Storage: 128GB internal, expandable via MicroSD",
          "Operating System: Android 15",
          "Rear Camera: 8MP with 1080P 30FPS / 720P 30FPS video recording",
          "Front Camera: 5MP",
          "Battery: 7000mAh capacity with 10W charging via USB Type-C",
          "Audio Support: MP3, FLAC, OGG, OGA, WAV, AAC, AMR, AWB, APE, MIDI",
          "Connectivity: Wi-Fi 802.11 a/b/g/n/ac Bluetooth 5.2 GPS 1 Nano SIM + MicroSD slot",
          "Sensors: G-Sensor",
          "Weight: 498g",
          "Color: Stellar Grey",
        ],
      },
      {
        heading: "Smooth Performance with Octa-Core Power",
        paragraphs: [
          "At the heart of the Infinix Xpad 20 is the MediaTek Helio G88 chipset, engineered for speed, efficiency, and smooth multitasking. Its octa-core CPU, featuring two high-performance 2.0 GHz Cortex-A75 cores and six power-efficient 1.8 GHz Cortex-A55 cores, works seamlessly with the Mali-G52 GPU to handle everything from casual browsing to gaming and HD video playback. With 6GB of RAM, switching between apps is effortless, and the generous 128GB of storage ensures you have plenty of space for apps, games, photos, and files. For those who need even more room, the tablet supports MicroSD expansion, giving you complete flexibility to store your content without compromise.",
        ],
      },
      {
        heading: "Latest Android 15 for a Smarter Experience",
        paragraphs: [
          "The Infinix Xpad 20 runs on Android 15, Google’s latest operating system, designed to make your tablet faster, smarter, and more secure. Android 15 brings you improved battery efficiency, better app management, enhanced privacy controls, and a more refined user interface for an intuitive experience. It also supports the latest Android features, so you can enjoy updates to your favorite apps, smoother animations, and seamless multitasking capabilities. Whether you’re using it for work or entertainment, Android 15 ensures your tablet stays future-ready.",
        ],
      },
      {
        heading: "Long-Lasting 7000mAh Battery",
        paragraphs: [
          "One of the standout features of the Infinix Xpad 20 is its massive 7000mAh battery, which delivers hours of uninterrupted use. You can binge-watch your favorite series, attend long online classes, or work on projects without worrying about frequent charging. The tablet supports 10W charging via a USB Type-C port, ensuring convenient power-ups whenever needed. Whether you’re at home, in the office, or on the go, the Infinix Xpad 20 keeps you powered throughout the day, so your productivity and entertainment never have to stop.",
        ],
      },
      {
        heading: "Clear Camera for Video Calls and Photos",
        paragraphs: [
          "Equipped with an 8MP rear camera and a 5MP front camera, the Infinix Xpad 20 is ready for both photography and video communication. The rear camera captures clear, detailed shots of documents, landscapes, and everyday moments, while the front camera ensures crisp, well-lit video calls for work meetings, online learning, or catching up with friends and family. Supporting 1080P 30FPS and 720P 30FPS video recording, this tablet delivers smooth, high-quality visuals for both capturing and streaming.",
        ],
      },
      {
        heading: "Strong Connectivity and Modern Features",
        paragraphs: [
          "The Infinix Xpad 20 is designed to keep you connected wherever you are. With Bluetooth 5.2 for fast, stable pairing and Wi-Fi 802.11 a/b/g/n/ac for reliable internet connectivity, you can stream, download, and browse without interruptions. Built-in GPS makes it great for navigation, while the Nano SIM slot with MicroSD support gives you the option to use mobile data when Wi-Fi isn’t available. File transfers and charging are quick and efficient thanks to the USB Type-C port, making your daily workflow more convenient.",
        ],
      },
      {
        heading: "Lightweight and Stylish Design",
        paragraphs: [
          "Weighing just 498g, the Infinix Xpad 20 strikes the perfect balance between portability and a premium feel. Its slim profile and elegant Stellar Grey color give it a modern, professional look that fits into any environment — whether you’re using it at a caf&eacute;, in a meeting room, or during a commute. The lightweight design makes it comfortable to hold for extended periods, ideal for reading, gaming, or video calls without fatigue. Combined with durable build quality, it’s a tablet that’s as reliable as it is stylish.",
        ],
      },
      {
        heading: "Buying the Infinix Xpad 20 (6/128GB) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
