/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/infinix-hot-70-8gb-128gb.jpeg";
import img2 from "@/images/products/infinix-hot-70-6gb-128gb/06-infinix-hot-70-silvet-dancer.jpeg";
import img3 from "@/images/products/infinix-hot-70-6gb-128gb/07-infinix-hot-70-silvet-dancer-1.jpeg";
import img4 from "@/images/products/infinix-hot-70-6gb-128gb/08-infinix-hot-70-silvet-dancer-2.jpeg";
import img5 from "@/images/products/infinix-hot-70-8gb-128gb/05-infinix-hot-70-green.jpeg";
import img6 from "@/images/products/infinix-hot-70-8gb-128gb/06-infinix-hot-70-green-1.jpeg";
import img7 from "@/images/brands/infinix-hot-70-6gb-128gb.jpeg";
import img8 from "@/images/products/infinix-hot-70-6gb-128gb/02-infinix-hot-70-night-pulse.jpeg";
import img9 from "@/images/products/infinix-hot-70-6gb-128gb/03-infinix-hot-70-night-pulse-1.jpeg";
import img10 from "@/images/products/infinix-hot-70-6gb-128gb/04-infinix-hot-70-night-pulse-2.jpeg";
import img11 from "@/images/products/infinix-hot-70-6gb-128gb/09-infinix-hot-70-thermo-orange-5.jpeg";
import img12 from "@/images/products/infinix-hot-70-6gb-128gb/10-infinix-hot-70-thermo-orange.jpeg";
import img13 from "@/images/products/infinix-hot-70-6gb-128gb/11-infinix-hot-70-thermo-orange-1.jpeg";
import img14 from "@/images/products/infinix-hot-70-6gb-128gb/12-infinix-hot-70-thermo-orange-2.jpeg";
import img15 from "@/images/products/infinix-hot-70-8gb-128gb/15-infinix-hot-70-v.jpeg";
import img16 from "@/images/products/infinix-hot-70-8gb-128gb/16-infinix-hot-70-violet.jpeg";

export const infinixHot708gb128gb: ProductDetail = {
  breadcrumb: [
    { label: "Phones", slug: "phone" },
    { label: "Infinix", slug: "infinix-mobile-phone" },
  ],
  gallery: [img1, img2, img3, img4, img5, img6, img7, img8, img9, img10, img11, img12, img13, img14, img15, img16],
  inStock: true,

  highlights: [
    "Processor: MediaTek Helio G100 Ultimate",
    "Display: 120Hz 6.78\" HD+ LCD Ultra-Bright",
    "Battery: 6000mAh 45W",
    "Camera: 50MP + 8MP",
  ],

  colors: [
    { name: "Silver Dancer", hex: "#E7E9E8", image: img1 },
    { name: "Green Texture", hex: "#CFDDB2", image: img5 },
    { name: "Night Pulse", hex: "#8B8B8C", image: img7 },
    { name: "Thermo Orange", hex: "#EF995E", image: img11 },
    { name: "Quite Violet", hex: "#C4BCE3", image: img15 },
  ],

  emi: { months: 6, perMonth: 4333 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["Infinix"] },
        { label: "Model Name", value: ["Hot 70"] },
      ],
    },
    {
      title: "Display",
      rows: [
        { label: "Size", value: ["6.78 inches"] },
        { label: "Type", value: ["IPS a-Si"] },
        { label: "Resolution", value: ["HD+ 720*1576"] },
        { label: "Refresh Rate", value: ["60Hz/90Hz/120Hz"] },
        { label: "Brightness", value: ["560 nits (TYP), 700 nits (HBM Brightness)"] },
        { label: "Features", value: ["Always-On Display"] },
      ],
    },
    {
      title: "Processor",
      rows: [
        { label: "Chipset", value: ["MediaTek Helio G100 Ultimate"] },
        { label: "CPU Type", value: ["Octa-core"] },
        { label: "CPU Speed", value: ["2x2.2 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55"] },
        { label: "GPU", value: ["Mali-G57 MC2"] },
      ],
    },
    {
      title: "Memory",
      rows: [
        { label: "RAM", value: ["8GB"] },
        { label: "ROM", value: ["128GB"] },
        { label: "Card Slot", value: ["2 nano SIMs + Micro SD"] },
      ],
    },
    {
      title: "Rear Camera",
      rows: [
        { label: "Resolution", value: ["50MP"] },
        { label: "Features", value: ["f/1.85, FOV 75.5°, AF supported"] },
      ],
    },
    {
      title: "Front Camera",
      rows: [
        { label: "Resolution", value: ["8MP"] },
        { label: "Features", value: ["f/2.0, FOV 77.7°, FF supported"] },
      ],
    },
    {
      title: "Network & AMP; Connectivity",
      rows: [
        { label: "SIM", value: ["2 nano SIMs"] },
        { label: "Network", value: ["4G/3G/2G"] },
        { label: "Wi-Fi", value: ["Wi-Fi 802.11 (a/b/g/n/ac)"] },
        { label: "Bluetooth", value: ["Bluetooth 5.4"] },
        { label: "GPS", value: ["Yes"] },
        { label: "NFC", value: ["Yes"] },
        { label: "USB", value: ["USB Type-C"] },
        { label: "OTG", value: ["Yes"] },
      ],
    },
    {
      title: "OS",
      rows: [
        { label: "Operating System", value: ["XOS 16, Powered by AndroidTM 16"] },
      ],
    },
    {
      title: "Features",
      rows: [
        { label: "Fingerprint", value: ["Side Fingerprint"] },
        { label: "Sensors", value: ["G-sensor", "E-Compass", "Gyroscope", "Light Sensor", "Proximity Sensor", "Motor", "Infrared Blaster"] },
        { label: "IP Rating", value: ["IP64"] },
      ],
    },
    {
      title: "Battery",
      rows: [
        { label: "Type", value: ["6000mAh"] },
        { label: "Fast Charging", value: ["45W"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["167.92mm*79.12mm*7.49mm"] },
        { label: "Weight", value: ["195g"] },
        { label: "Body Material", value: ["LCD"] },
        { label: "Colors", value: ["Night Pulse, Quite Violet, Silver Dancer, Green Texture"] },
      ],
    },
  ],

  description: {
    title: "Infinix Hot 70 (8/128GB)",
    blocks: [
      {
        paragraphs: [
          "The Infinix Hot 70 (8/128GB) is a stylish and powerful smartphone designed for users who want smooth performance, long battery life, a large immersive display, and reliable gaming performance at an affordable price. Powered by the advanced MediaTek Helio G100 Ultimate processor and equipped with a massive 6000mAh battery, this Infinix smartphone delivers excellent everyday performance for gaming, streaming, browsing, photography, and multitasking. With Android 16-based XOS 16, a slim modern design, fast 45W charging, and a high-refresh-rate display, the Infinix Hot 70 offers impressive value for budget-conscious smartphone users in Bangladesh.",
        ],
      },
      {
        heading: "Large 6.78-Inch Smooth Display for Entertainment",
        paragraphs: [
          "The Infinix Hot 70 features a large 6.78-inch IPS a-Si display that provides an immersive viewing experience for watching videos, gaming, social media browsing, and online classes. The HD+ resolution ensures clear visuals, while the adaptive 60Hz, 90Hz, and 120Hz refresh rate delivers ultra-smooth scrolling and responsive touch performance. With up to 700 nits HBM brightness, the display remains visible even under bright sunlight. The inclusion of an Always-On Display feature adds convenience by allowing users to quickly check notifications, time, and battery status without fully waking the device.",
        ],
      },
      {
        heading: "Powerful MediaTek Helio G100 Ultimate Performance",
        paragraphs: [
          "The smartphone is powered by the MediaTek Helio G100 Ultimate chipset, paired with an octa-core CPU featuring 2x Cortex-A76 cores clocked at 2.2GHz and 6x Cortex-A55 efficiency cores running at 2.0GHz. This setup ensures smooth multitasking, efficient gaming performance, and responsive app handling. The Mali-G57 MC2 GPU enhances graphics performance, making the Infinix Hot 70 suitable for popular mobile games, video editing, and high-quality media playback. Whether you are gaming, streaming, or switching between multiple apps, the device offers stable and efficient performance.",
        ],
      },
      {
        heading: "8GB RAM and 128GB Storage for Everyday Convenience",
        paragraphs: [
          "With 8GB RAM, the Infinix Hot 70 delivers smooth multitasking performance, allowing users to run multiple applications simultaneously without lag. The 128GB internal storage provides enough space for apps, games, photos, videos, and important documents. The phone also supports a dedicated MicroSD card slot, making storage expansion simple for users who need additional space for media files and gaming content.",
        ],
      },
      {
        heading: "50MP AI Rear Camera for Clear Photography",
        paragraphs: [
          "The Infinix Hot 70 comes with a 50MP rear camera featuring autofocus support and an f/1.85 aperture, helping users capture bright and detailed photos in various lighting conditions. Whether taking portraits, landscapes, or everyday shots, the camera produces social-media-ready images with balanced colors and clarity. On the front, the 8MP selfie camera delivers clear selfies and supports smooth video calling for online meetings, classes, and social communication.",
        ],
      },
      {
        heading: "Massive 6000mAh Battery with 45W Fast Charging",
        paragraphs: [
          "Battery life is one of the strongest highlights of the Infinix Hot 70. The device packs a huge 6000mAh battery that easily supports all-day heavy usage, including gaming, video streaming, and browsing. The smartphone also supports 45W fast charging, allowing users to recharge quickly and spend less time connected to a charger. This makes the device highly practical for busy users who need reliable all-day power.",
        ],
      },
      {
        heading: "Modern Design with IP64 Protection",
        paragraphs: [
          "The Infinix Hot 70 combines performance with a sleek modern design. Despite its large battery, the phone maintains a slim 7.49mm thickness and weighs only 195g, making it comfortable to hold and use daily. The device also features IP64 dust and splash resistance, helping protect it from minor water splashes and dust exposure during everyday use.",
        ],
      },
      {
        heading: "Advanced Connectivity and Smart Features",
        paragraphs: [
          "The smartphone supports 4G connectivity, dual nano SIM functionality, dual-band Wi-Fi, Bluetooth 5.4, GPS, NFC, and USB Type-C connectivity. It also includes useful features like OTG support, an infrared blaster, and a fast side-mounted fingerprint sensor for secure unlocking. Additional sensors such as the gyroscope, proximity sensor, light sensor, and E-compass improve the overall user experience for gaming, navigation, and daily smartphone activities.",
        ],
      },
      {
        heading: "Buying the Infinix Hot 70 (8/128GB) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
