/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/infinix-hot-60-pro.jpeg";
import img2 from "@/images/products/infinix-hot-60-pro/02-infinix-hot-60-pro-silver610.jpeg";
import img3 from "@/images/products/infinix-hot-60-pro/03-infinix-hot-60-pro-silver-1448.jpeg";
import img4 from "@/images/products/infinix-hot-60-pro/04-infinix-hot-60-pro-silver-2734.jpeg";
import img5 from "@/images/products/infinix-hot-60-pro/05-infinix-hot-60-pro-silver-3866.jpeg";
import img6 from "@/images/products/infinix-hot-60-pro/06-infinix-hot-60-pro-silver-4947.jpeg";
import img7 from "@/images/products/infinix-hot-60-pro/07-infinix-hot-60-pro-black-1135.jpeg";
import img8 from "@/images/products/infinix-hot-60-pro/08-infinix-hot-60-pro-black-2141.jpeg";
import img9 from "@/images/products/infinix-hot-60-pro/09-infinix-hot-60-pro-black-3719.jpeg";
import img10 from "@/images/products/infinix-hot-60-pro/10-infinix-hot-60-pro-black-4811.jpeg";
import img11 from "@/images/products/infinix-hot-60-pro/11-infinix-hot-60-pro-blue617.jpeg";
import img12 from "@/images/products/infinix-hot-60-pro/12-infinix-hot-60-pro-blue-1862.jpeg";
import img13 from "@/images/products/infinix-hot-60-pro/14-infinix-hot-60-pro-blue-3491.jpeg";

export const infinixHot60Pro: ProductDetail = {
  breadcrumb: [
    { label: "Phones", slug: "phone" },
    { label: "Infinix", slug: "infinix-mobile-phone" },
  ],
  gallery: [img1, img2, img3, img4, img5, img6, img7, img8, img9, img10, img11, img12, img13],
  inStock: false,

  highlights: [
    "Display: 6.78 inches, LTPS AMOLED",
    "Processor: MediaTek Helio G200",
    "Camera: 50MP Rear, 13MP Front",
    "Features: Rear Dual Flash, Type-C",
  ],

  colors: [
    { name: "Titanium Silver", hex: "#E4E3DE", image: img2 },
    { name: "Sleek Black", hex: "#252E41", image: img1 },
    { name: "Sapphire Blue", hex: "#3B6295", image: img11 },
  ],

  emi: { months: 6, perMonth: 3500 },

  specs: [
    {
      title: "Display",
      rows: [
        { label: "Size", value: ["6.78 inches"] },
        { label: "Type", value: ["LTPS AMOLED"] },
        { label: "Resolution", value: ["1.5K"] },
        { label: "Refresh Rate", value: ["60Hz/90Hz/120Hz/144Hz"] },
        { label: "Brightness", value: ["700nits (TYP), 1600nits (HBM Brightness), 4500nits (Peak Brightness)"] },
        { label: "Protection", value: ["Corning® Gorilla® Glass 7i"] },
      ],
    },
    {
      title: "Processor",
      rows: [
        { label: "Chipset", value: ["MediaTek Helio G200"] },
        { label: "CPU Type", value: ["Octa-core (2x2.2 GHz Cortex-A76 &", "6x2.0 GHz Cortex-A55)"] },
        { label: "GPU", value: ["Mali-G57 MC2"] },
      ],
    },
    {
      title: "Memory",
      rows: [
        { label: "RAM", value: ["8GB"] },
        { label: "ROM", value: ["128GB"] },
        { label: "Internal Storage", value: ["Up to 2TB"] },
      ],
    },
    {
      title: "Rear Camera",
      rows: [
        { label: "Resolution", value: ["50MP"] },
        { label: "Features", value: ["Rear Dual Flash", "Vlog，Video，AI Cam，Portrait，Super Night", "Slow Motion, Time-Lapse, Dual Video, Sky Shop,", "Pro，Panorama，Documents，Aigc Portrait"] },
        { label: "Video Recording", value: ["2K 30FPS/1080P 60FPS/1080P", "30FPS/720P 30FPS", "Slow Motion: 720P 120FPS (Only Rear Camera)"] },
      ],
    },
    {
      title: "Front Camera",
      rows: [
        { label: "Resolution", value: ["13MP"] },
      ],
    },
    {
      title: "Audio",
      rows: [
        { label: "Audio Features", value: ["MP3, FLAC, OGG, OGA,WAV, AAC,", "AMR, AWB, APE, MIDI"] },
      ],
    },
    {
      title: "Network & AMP; Connectivity",
      rows: [
        { label: "SIM", value: ["2 nano SIMs + Micro SD"] },
        { label: "Network", value: ["2G/3G/4G", "2G：B2|3|5|8", "3G：B1|2|4|5|8", "4G：B1|2|3|4|5|7|8|20|28A|28B|38|41(120M)|40"] },
        { label: "Wi-Fi", value: ["Wi-Fi 802.11 (a/b/g/n/ac)"] },
        { label: "Bluetooth", value: ["Bluetooth 5.4"] },
        { label: "NFC", value: ["YES"] },
        { label: "USB", value: ["USB Type-C"] },
        { label: "OTG", value: ["YES"] },
        { label: "Audio Jack", value: ["Type-C"] },
      ],
    },
    {
      title: "OS",
      rows: [
        { label: "Operating System", value: ["XOS15.1.1, Powered by Android™ 15"] },
      ],
    },
    {
      title: "Features",
      rows: [
        { label: "Sensors", value: ["G-SENSOR", "E-COMPASS", "GYROSCOPE", "LIGHT SENSOR", "PROXIMITY SENSOR", "FINGERPRINT", "INFRARED BLASTER", "MOTOR"] },
        { label: "IP Rating", value: ["IP64"] },
      ],
    },
    {
      title: "Battery",
      rows: [
        { label: "Type", value: ["5160mAh"] },
        { label: "Fast Charging", value: ["45W", "REVERSE CHARGING Yes, Max 10W"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["163.47mmx75.87mmx6.6mm"] },
        { label: "Weight", value: ["170g"] },
        { label: "Colors", value: ["Sleek Black, Titanium Silver"] },
      ],
    },
  ],

  description: {
    title: "Infinix Hot 60 Pro (8/128GB)",
    blocks: [
      {
        heading: "Key Features of Infinix Hot 60 Pro",
        paragraphs: [
          "Dive into a cinematic viewing experience on the 6.78-inch LTPS AMOLED display. With an impressive 1.5K resolution and adaptive refresh rates of 60Hz/90Hz/120Hz/144Hz, every scroll, swipe, and stream feels buttery smooth. Corning Gorilla Glass 7i adds durable protection, and with a peak brightness of 4500 nits, the screen remains crystal-clear even under harsh sunlight.",
          "Display Size: 6.78 inches",
          "Type: LTPS AMOLED",
          "Resolution: 1.5K",
          "Refresh Rate: 60Hz/90Hz/120Hz/144Hz",
          "Brightness: 700nits (TYP), 1600nits (HBM Brightness), 4500nits (Peak Brightness)",
          "Protection: Corning® Gorilla® Glass 7i",
          "Chipset: MediaTek Helio G200",
          "CPU Type: Octa-core (2x2.2 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)",
          "GPU: Mali-G57 MC2",
          "RAM: 8GB",
          "ROM: 128GB",
          "Internal Storage: Up to 2TB",
          "Rear Camera: 50MP",
          "Front Camera: 13MP",
          "Network & AMP; Connectivity",
          "SIM: 2 nano SIMs + Micro SD",
          "Network: 2G/3G/4G",
          "Wi-Fi: Wi-Fi 802.11 (a/b/g/n/ac)",
          "Bluetooth: 5.4",
          "USB: Type-C",
          "Audio Jack: Type-C",
          "Operating System: XOS15.1.1, Powered by Android™ 15",
        ],
      },
      {
        heading: "Power-Packed Performance",
        paragraphs: [
          "Running on the MediaTek Helio G200 processor, this phone handles multitasking, gaming, and daily apps effortlessly. The octa-core CPU (2x Cortex-A76 + 6x Cortex-A55) paired with Mali-G57 MC2 GPU brings balanced power and energy efficiency. Backed by 8GB RAM and 128GB storage, expandable up to 2TB, the Hot 60 Pro makes lag a thing of the past.",
        ],
      },
      {
        heading: "Capture Every Camera",
        paragraphs: [
          "Snap high-quality photos and videos with the 50MP rear camera, supported by features like Super Night Mode, Vlog Mode, Time-Lapse, and Dual Video. Record in 2K at 30FPS, or capture smooth slow-mo at 720p 120FPS. On the front, the 13MP selfie camera ensures you're always picture-perfect.",
        ],
      },
      {
        heading: "Stay Charged Longer Battery",
        paragraphs: [
          "The 5160mAh battery keeps you going all day and beyond. When you do need a top-up, the 45W fast charging fills the battery fast. And with 10W reverse charging, your phone can even power up other devices on the go. Stay connected with dual 4G SIM support, Wi-Fi 802.11 a/b/g/n/ac, Bluetooth 5.4, and NFC for contactless payments. The USB Type-C port supports OTG, and there's a built-in infrared blaster, fingerprint scanner, and all essential sensors. With an IP64 rating, the Hot 60 Pro is also protected against dust and light water splashes. At just 6.6mm thin and weighing 170g, the Hot 60 Pro combines portability with durability. The refined design feels premium in hand without sacrificing robustness.",
        ],
      },
      {
        heading: "Buying the Infinix Hot 60 Pro (8/128GB) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
