/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/ipad-pro-11-inch-wifi-m5-chip.jpeg";
import img2 from "@/images/products/ipad-pro-11-inch-wifi-m5-chip/03-ipad-pro-11-inch-wifi-m5-chip-silver-1318.jpeg";

export const ipadPro11InchWifiM5Chip: ProductDetail = {
  breadcrumb: ["Tablets", "iPad"],
  gallery: [img1, img2],
  inStock: true,

  highlights: [
    "Processor: Apple M5 chip",
    "Display: 11\" Tandem OLED, Ultra Retina XDR, Standard Glass",
    "Camera: 12MP Wide and Landscape 12MP Center Stage",
    "Memory Capacity: 256GB, 12GB RAM",
  ],

  colors: [
    { name: "Space Black with Standard Glass", hex: "#353336", image: img1 },
    { name: "Silver with Standard Glass", hex: "#E0E2E3", image: img2 },
  ],

  emi: { months: 12, perMonth: 15000 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["Apple"] },
        { label: "Model Name", value: ["iPad Pro"] },
      ],
    },
    {
      title: "Main Feature",
      rows: [
        { label: "Display Type", value: ["Ultra Retina XDR display Tandem OLED"] },
        { label: "Size", value: ["11‑inch"] },
        { label: "Resolution", value: ["2420-by-1668-pixel resolution at 264 ppi"] },
        { label: "RAM", value: ["12GB"] },
        { label: "Storage", value: ["256GB"] },
        { label: "Processor", value: ["Apple M5 chip", "9-core CPU with 3 performance cores and 6 efficiency cores", "10-core GPU", "Neural Accelerators", "Hardware-accelerated ray tracing", "16-core Neural Engine"] },
        { label: "Operating System", value: ["iPadOS 26"] },
        { label: "Connectivity", value: ["Wi-Fi"] },
        { label: "Audio", value: ["FaceTime audio", "Relay cellular calls from your nearby iPhone with the Phone app"] },
        { label: "Others", value: ["Studio-quality four-mic array for calls, video recording, and audio recording"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimensions", value: ["Height: 249.7 mm", "Width: 177.5 mm", "Depth: 5.3 mm"] },
        { label: "Weight", value: ["0.98 pound (444 grams)"] },
        { label: "Color", value: ["Space Gray, Silver"] },
      ],
    },
    {
      title: "Camera",
      rows: [
        { label: "Front Camera", value: ["12MP Wide camera, ƒ/1.8 aperture", "Digital zoom up to 5x", "Five‑element lens", "Adaptive True Tone flash", "Panorama (up to 63MP)", "Sapphire crystal lens cover", "Autofocus with Focus Pixels", "Smart HDR 4", "Wide color capture for photos and Live Photos", "Advanced red-eye correction", "Photo geotagging", "Auto image stabilization", "Burst mode", "Image formats captured: HEIF and JPEG"] },
        { label: "Rear Camera", value: ["Landscape 12MP Center Stage camera", "ƒ/2.0 aperture", "Portrait mode with advanced bokeh and Depth Control", "Portrait Lighting with six effects (Natural, Studio, Contour, Stage, Stage Mono, High‑Key Mono)", "Animoji and Memoji", "Smart HDR 4", "1080p HD video recording at 25 fps, 30 fps, or 60 fps", "Time‑lapse video with stabilization", "Extended dynamic range for video up to 30 fps", "Cinematic video stabilization (1080p and 720p)", "Wide color capture for photos and Live Photos", "Lens correction", "Retina Flash with True Tone", "Auto image stabilization", "Burst mode"] },
        { label: "Video", value: ["4K video recording at 24 fps, 25 fps, 30 fps, or 60 fps", "1080p HD video recording at 25 fps, 30 fps, or 60 fps", "720p HD video recording at 30 fps", "ProRes video recording up to 4K at 30 fps (1080p at 30 fps for 256GB storage)", "Audio zoom", "Adaptive True Tone flash", "Slo‑mo video support for 1080p at 120 fps or 240 fps", "Time‑lapse video with stabilization", "Extended dynamic range for video up to 30 fps", "Cinematic video stabilization (4K, 1080p, and 720p)", "Continuous autofocus video", "Playback zoom", "Video formats recorded: HEVC and H.264", "Stereo recording"] },
      ],
    },
    {
      title: "Battery",
      rows: [
        { label: "Type", value: ["Built-in rechargeable lithium-polymer battery"] },
        { label: "Capacity", value: ["31.29-watt-hour"] },
        { label: "Charging", value: ["Charging via power adapter or USB-C to computer system"] },
      ],
    },
    {
      title: "Special Features",
      rows: [
        { label: "Sensors", value: ["Face ID", "LiDAR Scanner", "Three-axis gyro", "Accelerometer", "Barometer", "Ambient light sensors"] },
        { label: "Bluetooth", value: ["Bluetooth 6"] },
        { label: "WLAN", value: ["Apple N1 wireless networking chip", "Wi‑Fi 7 (802.11be) with 2x2 MIMO6", "Simultaneous dual band", "Thread networking technology"] },
        { label: "GPS", value: ["Digital compass", "Wi-Fi", "iBeacon microlocation"] },
        { label: "USB", value: ["Thunderbolt / USB 4 port with support for:", "Charging", "DisplayPort", "Thunderbolt 3 (up to 40Gb/s)", "USB 4 (up to 40Gb/s)", "USB 3 (up to 10Gb/s)"] },
      ],
    },
  ],

  description: {
    title: "iPad Pro 11\" WiFi M5 Chip 256GB with Standard Glass",
    blocks: [
      {
        paragraphs: [
          "The iPad Pro 11\" WiFi M5 Chip sets a new standard for performance and portability, merging Apple’s most advanced technology with a stunning design. Crafted for professionals, creators, and multitaskers, this iPad Pro is more powerful, more immersive, and more efficient than ever. Whether you’re editing 4K videos, sketching intricate designs, or running demanding apps, the M5 chip ensures every task feels fluid and responsive.",
        ],
      },
      {
        heading: "Key Features of iPad Pro 11 inch M5 Chip",
        paragraphs: [
          "The iPad Pro 11\" features a breathtaking Ultra Retina XDR display powered by Apple’s cutting-edge Tandem OLED technology. Every image bursts with detail, color accuracy, and contrast, providing an immersive visual experience ideal for creative professionals. With a resolution of 2420 x 1668 pixels at 264 ppi, it delivers razor-sharp clarity and lifelike tones that make photos, videos, and games look stunning. Apple’s ProMotion adaptive refresh rate dynamically adjusts from 10Hz to 120Hz, ensuring ultra-smooth scrolling, responsive Apple Pencil movements, and seamless animations. True Tone and P3 wide color support guarantee natural, precise visuals in every environment, while the display’s peak brightness of up to 1600 nits enhances HDR content for breathtaking realism.",
        ],
      },
      {
        heading: "Powered by the Groundbreaking M5 Chip",
        paragraphs: [
          "At the heart of the iPad Pro 11\" is Apple’s newest M5 chip, delivering unmatched performance and efficiency. Built with next-generation architecture, it features an enhanced multi-core CPU, powerful GPU, and advanced Neural Engine, designed to handle everything from professional workflows to high-end gaming. The M5 chip ensures that heavy creative applications like Final Cut Pro, Adobe Photoshop, or Logic Pro run effortlessly, even when multitasking. Its efficiency cores extend battery life, keeping you productive all day long. The M5 also integrates AI-powered optimizations for faster image processing, real-time rendering, and smoother multitasking experiences.",
        ],
      },
      {
        heading: "Ultra-Thin Design and Premium Build",
        paragraphs: [
          "Apple has refined the design of the iPad Pro 11\" to be thinner, lighter, and more durable than ever. Crafted from premium recycled aluminum, it offers a sleek, minimalist look that’s both elegant and portable. At just a few millimeters thick, it’s easy to carry anywhere — from the studio to the classroom — without compromising on strength or performance.",
        ],
      },
      {
        heading: "Exceptional Camera System for Professionals",
        paragraphs: [
          "The iPad Pro 11\" M5 redefines what a tablet camera can do. The rear 12MP wide camera captures stunningly detailed photos and 4K videos with incredible depth and precision. Smart HDR and advanced image processing ensure accurate color and lighting in every shot. The front-facing 12MP Ultra Wide TrueDepth camera makes video calls crystal clear and dynamic, with Center Stage automatically adjusting to keep you perfectly in frame. Whether you’re attending meetings, recording content, or capturing creative projects, the iPad Pro’s cameras deliver professional-grade quality every time.",
        ],
      },
      {
        heading: "Immersive Audio and Studio-Quality Mics",
        paragraphs: [
          "The iPad Pro 11\" delivers an exceptional audio experience with its four-speaker sound system. It produces rich, balanced tones that bring movies, music, and games to life. Combined with studio-quality microphones, it ensures crystal-clear audio capture, ideal for content creators, podcasters, and professionals who demand premium sound performance.",
        ],
      },
      {
        heading: "Next-Level Connectivity and Expansion",
        paragraphs: [
          "Stay ahead with the Thunderbolt/USB 4 port, offering data transfer speeds up to 40Gb/s. Connect high-resolution monitors, fast external SSDs, or other peripherals seamlessly. The iPad Pro 11\" also supports Wi-Fi 6E for lightning-fast wireless performance and lower latency, ensuring smooth browsing, streaming, and collaboration. It works flawlessly with the latest Apple Pencil (USB-C) and Magic Keyboard, transforming your tablet into a true creative workstation. The Apple Pencil hover feature lets you preview strokes before you touch the screen, providing unmatched precision for artists and designers.",
        ],
      },
      {
        heading: "Advanced Face ID and iPadOS Experience",
        paragraphs: [
          "Enjoy fast, secure authentication with Face ID, powered by the TrueDepth camera. Unlock your device, make purchases, and sign in to apps safely with just a glance. The iPad Pro runs on the latest iPadOS, optimized for multitasking and productivity. Use Stage Manager, Split View, and advanced drag-and-drop tools to switch between tasks effortlessly. With powerful built-in apps and App Store support, the iPad Pro adapts to your workflow — from editing videos to managing spreadsheets or coding on the go.",
        ],
      },
      {
        heading: "All-Day Battery Life and Efficiency",
        paragraphs: [
          "Despite its immense power, the iPad Pro 11\" M5 offers incredible battery efficiency. With up to 10 hours of continuous web browsing or video playback, it’s built to keep up with your productivity. The energy-efficient M5 architecture ensures smooth, long-lasting performance, making it ideal for long working sessions or travel.",
        ],
      },
      {
        heading: "Buying the iPad Pro 11\" WiFi M5 Chip 256GB with Standard Glass from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
