/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/apple-ipad-air-13-inch-wifi-m3-chip-display-unit.jpeg";
import img2 from "@/images/products/ipad-air-13-inch-wifi-m3-chip-display-unit/02-ipad-air-13-inch-wifi-m3-chip745.jpeg";
import img3 from "@/images/products/ipad-air-13-inch-wifi-m3-chip-display-unit/03-ipad-air-13-inch-wifi-m3-chip-1372.jpeg";
import img4 from "@/images/products/ipad-air-13-inch-wifi-m3-chip-display-unit/04-ipad-air-13-inch-wifi-m3-chip-2935.jpeg";

export const ipadAir13InchWifiM3ChipDisplayUnit: ProductDetail = {
  breadcrumb: ["Tablets", "iPad"],
  gallery: [img1, img2, img3, img4],
  inStock: true,

  highlights: [
    "Liquid Retina display",
    "Apple M3 chip",
    "Up to 10 hours battery standby",
    "Landscape stereo speakers",
  ],

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["Apple"] },
        { label: "Model Name", value: ["iPad Air"] },
      ],
    },
    {
      title: "Main Feature",
      rows: [
        { label: "Display Type", value: ["Liquid Retina"] },
        { label: "Size", value: ["13\""] },
        { label: "Resolution", value: ["2732-by-2048-pixel resolution at 264 ppi"] },
        { label: "Storage", value: ["128GB"] },
        { label: "Processor", value: ["Apple M3 chip"] },
        { label: "Operating System", value: ["iPadOS 18"] },
        { label: "Connectivity", value: ["USB-C port with support for:", "Charging", "DisplayPort", "USB 3 (up to 10Gb/s)"] },
        { label: "Audio", value: ["Landscape stereo speakers"] },
        { label: "Others", value: ["ide color (P3)", "True Tone", "Fingerprint-resistant oleophobic coating", "Fully laminated", "Antireflective coating", "600 nits brightness", "Supports Apple Pencil Pro", "Supports Apple Pencil (USB‑C)", "Apple Pencil hover"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimensions", value: ["Width 8.46 inches (214.9 mm)", "Height 11.04 inches (280.6 mm)", "Depth 0.24 inch (6.1 mm)"] },
        { label: "Weight", value: ["1.36 pounds (617 grams)"] },
        { label: "Color", value: ["Space Gray"] },
      ],
    },
    {
      title: "Camera",
      rows: [
        { label: "Front Camera", value: ["Landscape 12MP Center Stage camera", "ƒ/2.0 aperture"] },
        { label: "Rear Camera", value: ["12MP Wide camera, ƒ/1.8 aperture"] },
        { label: "Video", value: ["4K video recording at 24 fps, 25 fps, 30 fps, or 60 fps", "1080p HD video recording at 25 fps, 30 fps, or 60 fps", "720p HD video recording at 30 fps", "Slo‑mo video support for 1080p at 120 fps or 240 fps", "Time‑lapse video with stabilisation", "Extended dynamic range for video up to 30 fps", "Cinematic video stabilization (4K, 1080p, and 720p)", "Continuous autofocus video", "Playback zoom", "Video formats captured: HEVC and H.264"] },
      ],
    },
    {
      title: "Battery",
      rows: [
        { label: "Type", value: ["Built‐in 36.59‐watt‐hour rechargeable lithium‑polymer battery"] },
        { label: "Charging", value: ["Charging via power adapter or USB‑C to computer system"] },
      ],
    },
    {
      title: "Special Features",
      rows: [
        { label: "Sensors", value: ["Touch ID", "Three‐axis gyro", "Accelerometer", "Barometer", "Ambient light sensor"] },
        { label: "Bluetooth", value: ["Bluetooth 5.3"] },
        { label: "WLAN", value: ["Wi-Fi 6E (802.11ax) with 2x2 MIMO5", "Simultaneous dual band"] },
        { label: "USB", value: ["USB-C port"] },
      ],
    },
  ],

  description: {
    title: "iPad Air 13\" WiFi M3 Chip 128GB Space Gray (Display Unit)",
    blocks: [
      {
        heading: "Buying the iPad Air 13\" WiFi M3 Chip 128GB Space Gray (Display Unit) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
