/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/iphone-17-pro-max.jpeg";
import img2 from "@/images/products/iphone-17-pro-max/02-iphone-17-pro-max-deep-blue737.jpeg";
import img3 from "@/images/products/iphone-17-pro-max/03-iphone-17-pro-max-silver416.jpeg";

export const iphone17ProMax: ProductDetail = {
  breadcrumb: [
    { label: "Phones", slug: "phone" },
    { label: "iPhone", slug: "iphone" },
  ],
  gallery: [img1, img2, img3],
  inStock: true,

  highlights: [
    "Display Size: 6.9‑inch (diagonal), Super Retina XDR display",
    "Processor: Apple A19 Pro, 6‑core CPU",
    "Camera: 48.0 MP + 48.0 MP + 48.0 MP + 18.0 MP",
    "Features: Face ID, Barometer, High dynamic range gyro",
    "Up to 24 Months 0% EMI (Selected Banks)",
  ],

  colors: [
    { name: "Deep Blue", hex: "#406585", image: img2 },
    { name: "Silver", hex: "#ededed", image: img3 },
    { name: "Cosmic Orange", hex: "#FA8D4D", image: img1 },
  ],

  options: [
    { label: "Storage", values: ["256GB", "512GB", "1TB"] },
  ],

  emi: { months: 24, perMonth: 9167 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["Apple"] },
        { label: "Model Name", value: ["iPhone 17 Pro Max"] },
      ],
    },
    {
      title: "Display",
      rows: [
        { label: "Size", value: ["6.9‑inch (diagonal)"] },
        { label: "Type", value: ["Super Retina XDR display", "all‑screen OLED display"] },
        { label: "Resolution", value: ["2868‑by‑1320-pixel resolution at 460 ppi"] },
        { label: "Refresh Rate", value: ["ProMotion technology with adaptive refresh rates up to 120Hz"] },
        { label: "Brightness", value: ["1000 nits max brightness (typical)", "1600 nits peak brightness (HDR)", "3000 nits peak brightness (outdoor)", "1 nit minimum brightness"] },
        { label: "Features", value: ["Dynamic Island", "Always-On display", "ProMotion technology with adaptive refresh rates up to 120Hz", "HDR display", "True Tone", "Wide color (P3)", "Haptic Touch", "2,000,000:1 contrast ratio (typical)", "Fingerprint-resistant oleophobic coating", "Anti-reflective coating", "Support for display of multiple languages and characters simultaneously"] },
      ],
    },
    {
      title: "Processor",
      rows: [
        { label: "Chipset", value: ["A19 Pro chip"] },
        { label: "CPU Type", value: ["6‑core CPU with 2 performance and 4 efficiency cores", "16‑core Neural Engine", "Hardware‑accelerated ray tracing"] },
        { label: "GPU", value: ["6‑core GPU with Neural Accelerators"] },
      ],
    },
    {
      title: "Memory",
      rows: [
        { label: "ROM", value: ["256GB", "512GB", "1TB", "2TB"] },
      ],
    },
    {
      title: "Rear Camera",
      rows: [
        { label: "Resolution", value: ["48MP Pro Fusion camera system"] },
        { label: "Features", value: ["48MP Fusion Main: 24 mm, ƒ/1.78 aperture, second‑generation sensor‑shift optical image stabilization, 100% Focus Pixels, support for super‑high‑resolution photos (24MP and 48MP)", "Also enables 12MP optical-quality 2x Telephoto: 48 mm, ƒ/1.78 aperture, second‑generation sensor‑shift optical image stabilization, 100% Focus Pixels", "48MP Fusion Ultra Wide: 13 mm, ƒ/2.2 aperture and 120° field of view, Hybrid Focus Pixels, super‑high‑resolution photos (48MP)", "48MP Fusion Telephoto: 100 mm (4x), ƒ/2.8 aperture, Hybrid Focus Pixels, 3D sensor‑shift optical image stabilization and autofocus, tetraprism design", "Also enables 12MP optical-quality 8x Telephoto: 200 mm, ƒ/2.8 aperture, Hybrid Focus Pixels, 3D sensor‑shift optical image stabilization and autofocus, tetraprism design", "8x optical‑quality zoom in, 2x optical zoom out", "16x optical‑quality zoom range", "Digital zoom up to 40x", "Customizable default lens (Fusion Main)", "Sapphire crystal lens cover", "Adaptive True Tone flash", "Photonic Engine", "Deep Fusion", "Smart HDR 5", "Next-generation portraits with Focus and Depth Control", "Portrait Lighting with six effects", "Night mode", "Panorama (up to 63MP)", "Latest-generation Photographic Styles", "Spatial photos", "48MP macro photography", "ProRAW", "Wide color capture for photos and Live Photos", "Lens correction (Fusion Ultra Wide)", "Advanced red-eye correction", "Auto image stabilization", "Burst mode", "Photo geotagging", "Image formats captured: HEIF, JPEG, and DNG"] },
        { label: "Video Recording", value: ["4K Dolby Vision video recording at 24 fps, 25 fps, 30 fps, 60 fps, 100 fps (Fusion Main), or 120 fps (Fusion Main)", "1080p Dolby Vision video recording at 25 fps, 30 fps, 60 fps, or 120 fps (Fusion Main)", "720p Dolby Vision video recording at 30 fps", "Cinematic mode up to 4K Dolby Vision at 30 fps", "Action mode up to 2.8K Dolby Vision at 60 fps", "Spatial video recording at 1080p at 30 fps", "ProRes video recording up to 4K at 120 fps with external recording", "ProRes RAW5", "Academy Color Encoding System", "Apple Log 2", "Genlock support6", "Macro video recording, including slo‑mo and time‑lapse", "Slo‑mo video support for 1080p up to 240 fps and 4K Dolby Vision up to 120 fps (Fusion Main)", "Dual Capture up to 4K Dolby Vision at 30 fps", "Time‑lapse video with stabilization", "Night mode Time‑lapse", "QuickTake video up to 4K Dolby Vision at 60 fps", "Second‑generation sensor‑shift optical image stabilization for video (Fusion Main)", "3D sensor‑shift optical image stabilization and autofocus for video (Fusion Telephoto)", "Digital zoom up to 15x", "Audio zoom", "True Tone flash", "Cinematic video stabilization (4K, 1080p, and 720p)", "Continuous autofocus video", "Take 8MP still photos while recording 4K video", "Playback zoom", "Video formats recorded: HEVC, H.264, ProRes, and ProRes RAW", "Spatial Audio and stereo recording", "Four studio-quality mics", "Wind noise reduction", "Audio Mix"] },
      ],
    },
    {
      title: "Front Camera",
      rows: [
        { label: "Resolution", value: ["18MP Center Stage camera"] },
        { label: "Features", value: ["ƒ/1.9 aperture", "Autofocus with Focus Pixels", "Retina Flash", "Tap to zoom and rotate", "Center Stage for photos", "Ultra-stabilized video", "Dual Capture", "Center Stage for video calls", "Photonic Engine", "Deep Fusion", "Smart HDR 5", "Next-generation portraits with Focus and Depth Control", "Portrait Lighting with six effects", "Animoji and Memoji", "Night mode", "Latest-generation Photographic Styles", "ProRAW", "Wide color capture for photos and Live Photos", "Lens correction", "Auto image stabilization", "Burst mode", "4K Dolby Vision video recording at 24 fps, 25 fps, 30 fps, or 60 fps", "1080p Dolby Vision video recording at 25 fps, 30 fps, or 60 fps", "Cinematic mode up to 4K Dolby Vision at 30 fps", "ProRes video recording up to 4K at 60 fps with external recording", "ProRes RAW5", "Academy Color Encoding System", "Apple Log 2", "Slo-mo video support for 1080p at 120 fps", "Time‑lapse video with stabilization", "Night mode Time-lapse", "QuickTake video up to 4K at 60 fps in Dolby Vision", "Cinematic video stabilization (4K, 1080p, and 720p)", "Spatial Audio and stereo recording", "Wind noise reduction", "Audio Mix"] },
      ],
    },
    {
      title: "Audio",
      rows: [
        { label: "Speaker", value: ["Spatial Audio playback"] },
        { label: "Audio Features", value: ["Supported formats include AAC, APAC, MP3, Apple Lossless, FLAC, Dolby Digital, Dolby Digital Plus, and Dolby Atmos", "User‑configurable maximum volume limit"] },
      ],
    },
    {
      title: "Network & Connectivity",
      rows: [
        { label: "SIM", value: ["Dual SIM (nano-SIM and eSIM)"] },
        { label: "Network", value: ["FDD-5G NR (Bands n1, n2, n3, n5, n7, n8, n12, n14, n20, n25, n26, n28, n29, n30, n66, n70, n71, n75)", "TDD-5G NR (Bands n38, n40, n41, n48, n53, n77, n78, n79)", "5G NR mmWave (Bands n258, n260, n261)", "FDD-LTE (Bands 1, 2, 3, 4, 5, 7, 8, 12, 13, 14, 17, 18, 19, 20, 25, 26, 28, 29, 30, 32, 66, 71)", "TDD-LTE (Bands 34, 38, 39, 40, 41, 42, 48, 53)", "UMTS/HSPA+/DC-HSDPA (850, 900, 1700/2100, 1900, 2100 MHz)", "GSM/EDGE (850, 900, 1800, 1900 MHz)"] },
        { label: "Wi-Fi", value: ["Apple N1 wireless networking chip", "Wi‑Fi 7 (802.11be) with 2x2 MIMO", "Thread networking technology"] },
        { label: "Bluetooth", value: ["Bluetooth 6"] },
        { label: "GPS", value: ["Precision dual-frequency GPS (GPS, GLONASS, Galileo, QZSS, BeiDou, and NavIC)"] },
        { label: "NFC", value: ["Supported"] },
        { label: "USB", value: ["USB 3 (up to 10Gb/s)"] },
        { label: "OTG", value: ["Supported"] },
        { label: "Audio Jack", value: ["USB-C"] },
      ],
    },
    {
      title: "OS",
      rows: [
        { label: "Operating System", value: ["iOS 26", "iOS is the world’s most personal and secure mobile operating system, packed with powerful features and designed to protect your privacy."] },
      ],
    },
    {
      title: "Features",
      rows: [
        { label: "Sensors", value: ["Face ID", "LiDAR Scanner", "Barometer", "High dynamic range gyro", "High-g accelerometer", "Proximity sensor", "Dual ambient light sensors"] },
        { label: "IP Rating", value: ["Rated IP68 (maximum depth of 6 meters up to 30 minutes) under IEC standard 60529"] },
        { label: "Other Features", value: ["Enabled by TrueDepth technology in the Center Stage front camera", "NFC with reader mode", "Express Cards with power reserve", "Action button features", "Silent mode, Focus, Camera, Visual Intelligence14, Flashlight, Voice Memo, Recognize Music, Translate, Magnifier, Controls, Shortcut, or Accessibility", "Camera controls", "Exposure, Depth, Zoom, Cameras, Styles, Tone"] },
      ],
    },
    {
      title: "Battery",
      rows: [
        { label: "Type", value: ["Built‑in rechargeable lithium‑ion battery", "Video playback: Up to 39 hours", "Video playback (streamed): Up to 35 hours"] },
        { label: "Fast Charging", value: ["Up to 50% charge in 20 minutes with 40W adapter or higher (available separately) paired with USB-C charging cable", "Up to 50% charge in 30 minutes with 30W adapter or higher paired with MagSafe Charger (both available separately)", "MagSafe wireless charging up to 25W", "Qi2 wireless charging up to 25W"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["Height: 6.43 inches (163.4 mm)", "Width: 3.07 inches (78.0 mm)", "Depth: 0.34 inch (8.75 mm)"] },
        { label: "Weight", value: ["Weight: 8.22 ounces (233 grams)"] },
        { label: "Colors", value: ["Silver, Cosmic Orange, Deep Blue"] },
      ],
    },
  ],

  description: {
    title: "iPhone 17 Pro Max",
    blocks: [
      {
        heading: "Powerful Performance with the A19 Pro Chip",
        paragraphs: [
          "At the centre of the Apple iPhone 17 Pro Max is the A19 Pro chip, featuring a 6-core CPU, 6-core GPU with Neural Accelerators and a 16-core Neural Engine. This hardware delivers fast, responsive performance when gaming, editing high-resolution video, multitasking or using demanding professional apps.",
          "A vapour-chamber thermal system helps manage heat during intensive workloads, allowing the phone to maintain strong performance for longer. Hardware-accelerated ray tracing also enhances lighting, detail and realism in supported games. With iOS 26 and Apple Intelligence, everyday tasks such as writing, searching and organising information feel more intuitive while benefiting from Apple's focus on privacy.",
        ],
      },
      {
        heading: "Immersive 6.9-inch Super Retina XDR Display",
        paragraphs: [
          "The expansive 6.9-inch Super Retina XDR display creates an immersive viewing experience for movies, games, editing and daily browsing. ProMotion technology provides an adaptive refresh rate of up to 120Hz, making scrolling, animations and compatible games look noticeably smoother.",
          "With up to 3,000 nits of peak outdoor brightness, content remains easier to see under bright sunlight. The Always-On display keeps useful information available at a glance, while Ceramic Shield 2 on the front provides added protection for everyday use.",
        ],
      },
      {
        heading: "Triple 48MP Pro Fusion Camera System",
        paragraphs: [
          "Mobile photographers and content creators get three capable rear cameras: a 48MP Fusion Main, 48MP Fusion Ultra Wide and 48MP Fusion Telephoto. The system covers sweeping landscapes, detailed macro images, natural portraits and distant subjects without requiring separate camera equipment.",
          "The Telephoto camera offers 4x optical zoom and an 8x optical-quality option, while the entire system provides a 16x optical-quality zoom range. Features such as Smart HDR 5, Night mode, ProRAW and next-generation portraits help produce detailed, balanced images in varied conditions.",
        ],
      },
      {
        heading: "Professional Video and Center Stage Camera",
        paragraphs: [
          "The iPhone 17 Pro Max supports 4K Dolby Vision recording, ProRes RAW, Apple Log 2, Genlock and external ProRes recording up to 4K at 120 fps. These tools make it a practical choice for vloggers, filmmakers and commercial content creators. Its 18MP Center Stage front camera can adjust framing during calls and supports ultra-stabilised video and Dual Capture.",
        ],
      },
      {
        heading: "Long Battery Life, USB-C and MagSafe",
        paragraphs: [
          "Built for demanding days, the iPhone 17 Pro Max combines a larger battery with the efficiency of the A19 Pro chip. It supports fast charging through USB-C, MagSafe wireless charging and compatible Qi2 accessories. Storage choices range from 256GB and 512GB to 1TB and 2TB, giving creators ample room for 4K footage, ProRAW photos, games and offline media.",
          "Wi-Fi 7, 5G, Bluetooth 6 and second-generation Ultra Wideband provide modern connectivity. The aluminium unibody design, Ceramic Shield protection and IP68 dust and water resistance add confidence for everyday use. Available finishes include Cosmic Orange, Deep Blue and Silver.",
        ],
      },
      {
        heading: "Which storage options are available?",
        paragraphs: [
          "Apple offers the iPhone 17 Pro Max in 256GB, 512GB, 1TB and 2TB capacities.",
        ],
      },
      {
        heading: "Is the iPhone 17 Pro Max water-resistant?",
        paragraphs: [
          "Yes. It carries an IP68 rating for resistance to dust and water under controlled laboratory conditions. Water resistance can decrease through normal wear.",
        ],
      },
      {
        heading: "Buying the iPhone 17 Pro Max from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
