/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/jbl-charge-6-portable-wireless-speaker.jpeg";
import img2 from "@/images/products/jbl-charge-6-portable-wireless-speaker/02-jbl-charge-6-portable-wireless-speaker562.jpeg";
import img3 from "@/images/products/jbl-charge-6-portable-wireless-speaker/03-jbl-charge-6-portable-wireless-speaker-1577.jpeg";
import img4 from "@/images/products/jbl-charge-6-portable-wireless-speaker/04-jbl-charge-6-portable-wireless-speaker-2697.jpeg";
import img5 from "@/images/products/jbl-charge-6-portable-wireless-speaker/05-jbl-charge-6-portable-wireless-speaker-black-3453.jpeg";
import img6 from "@/images/products/jbl-charge-6-portable-wireless-speaker/06-jbl-charge-6-portable-wireless-speaker-funky393.jpeg";
import img7 from "@/images/products/jbl-charge-6-portable-wireless-speaker/07-jbl-charge-6-portable-wireless-speaker-funky-211.jpeg";
import img8 from "@/images/products/jbl-charge-6-portable-wireless-speaker/08-jbl-charge-6-portable-wireless-speaker-funky-387.jpeg";
import img9 from "@/images/products/jbl-charge-6-portable-wireless-speaker/09-jbl-charge-6-portable-wireless-speaker-blue583.jpeg";
import img10 from "@/images/products/jbl-charge-6-portable-wireless-speaker/10-jbl-charge-6-portable-wireless-speaker-blue-1222.jpeg";
import img11 from "@/images/products/jbl-charge-6-portable-wireless-speaker/11-jbl-charge-6-portable-wireless-speaker-blue-3773.jpeg";
import img12 from "@/images/products/jbl-charge-6-portable-wireless-speaker/12-jbl-charge-6-portable-wireless-speaker-blue-2775.jpeg";
import img13 from "@/images/products/jbl-charge-6-portable-wireless-speaker/13-jbl-charge-6-portable-wireless-speaker-blue-4315.jpeg";
import img14 from "@/images/products/jbl-charge-6-portable-wireless-speaker/14-jbl-charge-6-portable-wireless-speaker-pink596.jpeg";
import img15 from "@/images/products/jbl-charge-6-portable-wireless-speaker/15-jbl-charge-6-portable-wireless-speaker-pink-1679.jpeg";
import img16 from "@/images/products/jbl-charge-6-portable-wireless-speaker/16-jbl-charge-6-portable-wireless-speaker-pink-2144.jpeg";
import img17 from "@/images/products/jbl-charge-6-portable-wireless-speaker/17-jbl-charge-6-portable-wireless-speaker-pink-3370.jpeg";
import img18 from "@/images/products/jbl-charge-6-portable-wireless-speaker/18-jbl-charge-6-portable-wireless-speaker-red523.jpeg";
import img19 from "@/images/products/jbl-charge-6-portable-wireless-speaker/19-jbl-charge-6-portable-wireless-speaker-red-1176.jpeg";
import img20 from "@/images/products/jbl-charge-6-portable-wireless-speaker/20-jbl-charge-6-portable-wireless-speaker-red-2490.jpeg";
import img21 from "@/images/products/jbl-charge-6-portable-wireless-speaker/21-jbl-charge-6-portable-wireless-speaker-red-3780.jpeg";
import img22 from "@/images/products/jbl-charge-6-portable-wireless-speaker/22-jbl-charge-6-portable-wireless-speaker-red-417.jpeg";
import img23 from "@/images/products/jbl-charge-6-portable-wireless-speaker/23-jbl-charge-6-portable-wireless-speaker-sand343.jpeg";
import img24 from "@/images/products/jbl-charge-6-portable-wireless-speaker/24-jbl-charge-6-portable-wireless-speaker-sand-1438.jpeg";
import img25 from "@/images/products/jbl-charge-6-portable-wireless-speaker/25-jbl-charge-6-portable-wireless-speaker-sand-2947.jpeg";
import img26 from "@/images/products/jbl-charge-6-portable-wireless-speaker/26-jbl-charge-6-portable-wireless-speaker-sand-3756.jpeg";
import img27 from "@/images/products/jbl-charge-6-portable-wireless-speaker/27-jbl-charge-6-portable-wireless-speaker-squad21.jpeg";
import img28 from "@/images/products/jbl-charge-6-portable-wireless-speaker/28-jbl-charge-6-portable-wireless-speaker-squad-113.jpeg";
import img29 from "@/images/products/jbl-charge-6-portable-wireless-speaker/29-jbl-charge-6-portable-wireless-speaker-squad-3637.jpeg";
import img30 from "@/images/products/jbl-charge-6-portable-wireless-speaker/30-jbl-charge-6-portable-wireless-speaker-squad-2609.jpeg";
import img31 from "@/images/products/jbl-charge-6-portable-wireless-speaker/31-jbl-charge-6-portable-wireless-speaker-white617.jpeg";
import img32 from "@/images/products/jbl-charge-6-portable-wireless-speaker/32-jbl-charge-6-portable-wireless-speaker-white-1793.jpeg";
import img33 from "@/images/products/jbl-charge-6-portable-wireless-speaker/33-jbl-charge-6-portable-wireless-speaker-white-3858.jpeg";
import img34 from "@/images/products/jbl-charge-6-portable-wireless-speaker/34-jbl-charge-6-portable-wireless-speaker-white-4963.jpeg";
import img35 from "@/images/products/jbl-charge-6-portable-wireless-speaker/35-jbl-charge-6-portable-wireless-speaker-white-2148.jpeg";

export const jblCharge6PortableWirelessSpeaker: ProductDetail = {
  breadcrumb: [
    { label: "Headphone & Speaker", slug: "headphone-speaker" },
    { label: "Speaker", slug: "speakers" },
    { label: "JBL", slug: "jbl-speaker" },
  ],
  gallery: [img1, img2, img3, img4, img5, img6, img7, img8, img9, img10, img11, img12, img13, img14, img15, img16, img17, img18, img19, img20, img21, img22, img23, img24, img25, img26, img27, img28, img29, img30, img31, img32, img33, img34, img35],
  inStock: true,

  highlights: [
    "Bluetooth 5.4",
    "IP68 waterproof and dustproof",
    "Li-ion polymer 34 Wh",
    "Charging Time: 3 hours",
  ],

  colors: [
    { name: "Black", hex: "#000000", image: img2 },
    { name: "Black / Orange", hex: "#CC3633", image: img6 },
    { name: "Blue", hex: "#035BBC", image: img9 },
    { name: "Pink", hex: "#FDAEC8", image: img14 },
    { name: "Red", hex: "#FF0000", image: img18 },
    { name: "Sand", hex: "#CAC3B3", image: img23 },
    { name: "Squad", hex: "#737D62", image: img27 },
    { name: "White", hex: "#ffffff", image: img31 },
  ],

  emi: { months: 6, perMonth: 2917 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["JBL"] },
        { label: "Model Name", value: ["Charge 6"] },
      ],
    },
    {
      title: "Main Features",
      rows: [
        { label: "Connection Type", value: ["Wireless"] },
        { label: "Bluetooth Version", value: ["5.4"] },
        { label: "Bluetooth Profiles", value: ["A2DP 1.4, AVRCP 1.6"] },
        { label: "Frequency Response", value: ["56 Hz - 20 kHz (-6 dB)"] },
        { label: "Amplifier Power", value: ["< 15 dBm (EIRP)"] },
        { label: "Battery Type", value: ["Li-ion polymer 34 Wh (equivalent to 7.2 V /4722 mAh)"] },
        { label: "Charging Type", value: ["3 hours (12 - 20 V / 3 A)"] },
        { label: "Music play time", value: ["Up to 24 hours of playtime plus 4 hours with Playtime Boost (dependent on volume level and audio content)"] },
        { label: "Signal / Noise Ratio", value: ["> 80 dB"] },
        { label: "Output power (W)", value: ["30 W RMS for woofer, 15 W RMS for tweeter"] },
        { label: "Others", value: ["IP68 waterproof and dustproof"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["228.8 x 98.5 x 94.0 mm / 9.0\" x 3.9\" x 3.7\""] },
        { label: "Weight", value: ["1.37 kg / 3 lbs"] },
        { label: "Colors", value: ["Black, Black/Orange, Blue, Pink, Red , Sand, Squad, White"] },
      ],
    },
  ],

  description: {
    title: "JBL Charge 6",
    blocks: [
      {
        paragraphs: [
          "Introducing the JBL Charge 6 Speaker, the perfect blend of powerful sound and unmatched convenience. Whether you're hosting a party or relaxing outdoors, the JBL Charge 6 delivers exceptional sound quality and an impressive battery life. With cutting-edge Bluetooth technology, rugged design, and a long-lasting battery, it’s an ideal companion for any adventure.",
        ],
      },
      {
        heading: "Key Features of JBL Charge 6 Speaker",
        paragraphs: [
          "The JBL Charge 6 sets a new standard in portable wireless speakers. Packed with features designed to provide an unbeatable audio experience, it’s perfect for music lovers on the go. Let’s explore what makes the JBL Charge 6 the ultimate choice for your listening needs:",
        ],
      },
      {
        heading: "Wireless Connectivity",
        paragraphs: [
          "The JBL Charge 6 comes equipped with Bluetooth 5.4, ensuring seamless wireless connection for superior sound transmission. It supports A2DP 1.4 and AVRCP 1.6 profiles, allowing you to stream music from your device effortlessly. Whether you're using it with a smartphone, tablet, or laptop, you'll enjoy smooth and uninterrupted connectivity. With a frequency response of 56 Hz - 20 kHz and a signal-to-noise ratio of over 80 dB, the JBL Charge 6 offers rich, clear sound across all genres. The combination of a 30W RMS woofer and a 15W RMS tweeter ensures powerful bass and crisp highs, delivering a truly immersive listening experience.",
        ],
      },
      {
        heading: "Long Battery Life for Extended Playtime",
        paragraphs: [
          "Never worry about running out of power during your adventures with the JBL Charge 6. It features a 34 Wh Li-ion polymer battery, offering up to 24 hours of continuous music playtime. Plus, with the Playtime Boost, you can enjoy an additional 4 hours, depending on the volume level and audio content. Whether you're camping, at the beach, or hosting an outdoor event, this speaker will keep the music going for hours on end.",
        ],
      },
      {
        heading: "Fast Charging Capabilities",
        paragraphs: [
          "The JBL Charge 6 comes with fast charging capabilities, requiring only 3 hours to fully charge with a 12-20V/3A input. This makes it incredibly convenient for users who need to quickly recharge their speaker and get back to enjoying their music.",
        ],
      },
      {
        heading: "Buying the JBL Charge 6 Portable Wireless Speaker from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
