/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/jbl-partybox-520-wireless-speaker.jpeg";
import img2 from "@/images/products/jbl-partybox-520-wireless-speaker/02-jbl-partybox-520-wireless-speaker-1700.jpeg";
import img3 from "@/images/products/jbl-partybox-520-wireless-speaker/03-jbl-partybox-520-wireless-speaker-2734.jpeg";
import img4 from "@/images/products/jbl-partybox-520-wireless-speaker/04-jbl-partybox-520-wireless-speaker-5309.jpeg";
import img5 from "@/images/products/jbl-partybox-520-wireless-speaker/05-jbl-partybox-520-wireless-speaker-4353.jpeg";
import img6 from "@/images/products/jbl-partybox-520-wireless-speaker/06-jbl-partybox-520-wireless-speaker-3727.jpeg";

export const jblPartybox520WirelessSpeaker: ProductDetail = {
  breadcrumb: [
    { label: "Headphone & Speaker", slug: "headphone-speaker" },
    { label: "Speaker", slug: "speakers" },
    { label: "JBL", slug: "jbl-speaker" },
  ],
  gallery: [img1, img2, img3, img4, img5, img6],
  inStock: true,

  highlights: [
    "Battery Type: JBL BATTERY 600, Li-ion 99.02 Wh",
    "Frequency Response: 40 Hz – 20 kHz",
    "Music play time: Up to 15 hours",
    "Battery charge time: Up to 3 Hrs",
  ],

  colors: [
    { name: "Black", hex: "#000000", image: img1 },
  ],

  emi: { months: 6, perMonth: 13333 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["JBL"] },
        { label: "Model Name", value: ["PartyBox 520"] },
      ],
    },
    {
      title: "Main Features",
      rows: [
        { label: "Connection Type", value: ["Bluetooth"] },
        { label: "Bluetooth Version", value: ["V5.4"] },
        { label: "Bluetooth Profiles", value: ["A2DP V1.4, AVRCP V1.6"] },
        { label: "Bluetooth Transmitter Power", value: ["≤ 18 dBm (EIRP)"] },
        { label: "Frequency Response", value: ["40 Hz – 20 kHz"] },
        { label: "Battery Type", value: ["JBL BATTERY 600, Li-ion 99.02 Wh"] },
        { label: "Charging Type", value: ["USB C"] },
        { label: "Battery charge time", value: ["Up to 3 Hrs"] },
        { label: "Music play time", value: ["Up to 15 hours"] },
        { label: "Signal / Noise Ratio", value: ["> 80dB"] },
        { label: "Input Impedance", value: ["100 – 240 V ~ 50-60 Hz"] },
        { label: "Output power (W)", value: ["400W"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["Dimensions (Width x Height x Depth) (cm) 42 x 77 x 37", "Dimensions (Width x Height x Depth) (in) 16 x 30 x 15"] },
        { label: "Weight", value: ["Weight (kgs) 26", "Weight (lbs) 56"] },
        { label: "Colors", value: ["Black"] },
      ],
    },
  ],

  description: {
    title: "JBL PartyBox 520 Wireless Speaker",
    blocks: [
      {
        paragraphs: [
          "The JBL PartyBox 520 Wireless Speaker is made for those who don’t just play music they live it. Whether you're throwing an outdoor bash, a house party, or just vibing on your rooftop, this high-performance Bluetooth speaker brings the energy. With 400W of JBL Pro Sound, bold bass, and eye-catching design, the PartyBox 520 is everything you need to create unforgettable nights. And with wireless freedom, long battery life, and next-gen Bluetooth 5.4, you can take the party with you wherever you go.",
        ],
      },
      {
        heading: "JBL PartyBox 520 Speaker Specification",
        paragraphs: [
          "Experience music like never before with the JBL PartyBox 520. This powerful speaker blends JBL’s legendary sound quality with advanced wireless features and rugged design. Let’s break down why it’s quickly becoming the go-to party speaker around the world. Bring your events to life with 400 watts of pure JBL Pro Sound. From deep lows to crisp highs, the PartyBox 520 fills any space big or small with dynamic audio. Whether you're DJing your own party or playing from a phone playlist, the sound quality stays clear, powerful, and bass-rich.",
          "Connection Type: Bluetooth",
          "Bluetooth Version: 5.4",
          "Bluetooth Profiles Supported: A2DP V1.4, AVRCP V1.6",
          "Bluetooth Transmitter Power: &le; 18 dBm (EIRP)",
          "Frequency Response: 40 Hz – 20 kHz",
          "Signal-to-Noise Ratio: Greater than 80 dB",
          "Output Power: 400W RMS",
          "Battery Type: JBL Battery 600, Lithium-ion, 99.02 Wh",
          "Charging Type: USB Type-C",
          "Battery Charging Time: Up to 3 hours",
          "Music Playback Time: Up to 15 hours (dependent on volume level and audio content)",
          "Input Impedance: 100 – 240V ~ 50/60Hz",
        ],
      },
      {
        heading: "Wireless Freedom with Bluetooth & Non-Stop Party",
        paragraphs: [
          "With the latest Bluetooth v5.4, you get stronger, faster, and more stable wireless connections. It supports A2DP V1.4 and AVRCP V1.6 profiles, so you can stream high-quality audio without interruptions. Sync it to your smartphone, tablet, or laptop, and enjoy a seamless connection across the dancefloor. Powered by a robust JBL 600 Li-ion battery (99.02 Wh), this wireless speaker gives you up to 15 hours of music playtime on a full charge. And when you're running low, the USB-C fast charging takes you back to full power in just 3 hours—perfect for festivals, beach days, or all-nighters.",
        ],
      },
      {
        heading: "Rich Bass & Balanced Frequency Response",
        paragraphs: [
          "With a frequency response range of 40 Hz to 20 kHz, the JBL PartyBox 520 delivers a wide audio spectrum. Whether you're blasting EDM or chill acoustic tracks, the balance between bass, mids, and highs stays consistent. A signal-to-noise ratio above 80dB ensures minimal distortion at any volume. Designed to match its power, the PartyBox 520 comes in a rugged, party-ready body. With dimensions of 42 x 77 x 37 cm and a weight of 26kg (56 lbs), it’s built to travel, perform, and withstand the wildest weekends. Whether it's indoors or outdoors, this speaker looks and sounds amazing.",
        ],
      },
      {
        heading: "Buying the JBL PartyBox 520 Wireless Speaker from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
