/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/jbl-boombox-4.jpeg";
import img2 from "@/images/products/jbl-boombox-4/02-jbl-boombox-4-black.jpg-1447.jpeg";
import img3 from "@/images/products/jbl-boombox-4/03-jbl-boombox-4-black.jpg-2718.jpeg";
import img4 from "@/images/products/jbl-boombox-4/04-jbl-boombox-4-black.jpg-3643.jpeg";
import img5 from "@/images/products/jbl-boombox-4/05-jbl-boombox-4-black.jpg-4329.jpeg";
import img6 from "@/images/products/jbl-boombox-4/06-jbl-boombox-4-black.jpg-5285.jpeg";
import img7 from "@/images/products/jbl-boombox-4/07-jbl-boombox-4-squad488.jpeg";
import img8 from "@/images/products/jbl-boombox-4/08-jbl-boombox-4-squad.jpg-1938.jpeg";
import img9 from "@/images/products/jbl-boombox-4/09-jbl-boombox-4-squad.jpg-2999.jpeg";
import img10 from "@/images/products/jbl-boombox-4/10-jbl-boombox-4-squad.jpg-3489.jpeg";
import img11 from "@/images/products/jbl-boombox-4/11-jbl-boombox-4-squad.jpg-465.jpeg";
import img12 from "@/images/products/jbl-boombox-4/12-jbl-boombox-4-squad.jpg-5967.jpeg";

export const jblBoombox4: ProductDetail = {
  breadcrumb: ["Headphone & Speaker", "Speaker", "JBL"],
  gallery: [img1, img2, img3, img4, img5, img6, img7, img8, img9, img10, img11, img12],
  inStock: true,

  highlights: [
    "Massive sound output / upgraded driver system",
    "Two-level Bass Boost + AI Sound Boost",
    "Long battery + power-bank capability",
    "Rugged, outdoor-ready design (IP68 rating)",
  ],

  colors: [
    { name: "Black", hex: "#000000", image: img1 },
    { name: "Squad", hex: "#737D62", image: img7 },
  ],

  emi: { months: 6, perMonth: 9333 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["JBL"] },
        { label: "Model Name", value: ["Boombox 4"] },
      ],
    },
    {
      title: "Main Features",
      rows: [
        { label: "Connection Type", value: ["AC-in, USB-C"] },
        { label: "Bluetooth Version", value: ["5.4"] },
        { label: "Bluetooth Profiles", value: ["A2DP 1.4, AVRCP 1.6"] },
        { label: "Bluetooth Transmitter Power", value: ["≤ 14dBm (EIRP)"] },
        { label: "Frequency Response", value: ["37Hz - 20 kHz"] },
        { label: "Battery Type", value: ["Rechargeable Li-ion"] },
        { label: "Battery Capacity / Voltage", value: ["99.02Wh (21.6V / 4584 mAh)"] },
        { label: "Battery Life", value: ["Up to 28 hours"] },
        { label: "Battery charge time", value: ["Approx. 3 hours"] },
        { label: "Music play time", value: ["6 hours with Playtime Boost, depends on volume & content"] },
        { label: "Signal / Noise Ratio", value: ["> 80 Db"] },
        { label: "Output power (W)", value: ["(AC mode) - 2 x 65W RMS Woofer, 2 x 40W RMS Tweeter (Battery mode) - 2 60W RMS Woofer, 2 x 40W RMS Tweeter"] },
        { label: "Others", value: ["AI Sound Boost, JBL Playtime Boost, Auracast for Multi Speaker Connection, Bass Boost Settings, Glowing JBL Horn | Accessories: AC Power Cable (2000mm / 78.7”)", "IP68 Dust & Water Resistant"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["Product: 506.4 × 262.9 × 212.9 mm (19.9 × 10.4 × 8.4 in)", "(W × H × D) | Packaging: 565 × 345 × 256 mm (22.2 × 13.6 × 10.1 in)", "(W × H × D)"] },
        { label: "Weight", value: ["Net Weight: 5.89 kg (13 lbs) | Gross Weight: 8.16 kg (17.99 lbs)"] },
        { label: "Colors", value: ["Black, Squad"] },
      ],
    },
  ],

  description: {
    title: "JBL Boombox 4",
    blocks: [
      {
        paragraphs: [
          "The JBL Boombox 4 is the ultimate portable Bluetooth speaker designed for those who crave powerful sound, deep bass, and all-day playtime. Combining rugged design, impressive battery life, and the iconic JBL sound signature, this speaker redefines outdoor and party audio experiences. Whether you’re hosting a beach party, camping trip, or backyard event, the JBL Boombox 4 delivers pure, dynamic sound that moves with you wherever you go.",
        ],
      },
      {
        heading: "JBL Boombox 4 Specifications",
        paragraphs: [
          "The JBL Boombox 4 delivers powerful JBL Pro Sound with deep bass, crystal-clear highs, and up to 24 hours of playtime. Featuring Bluetooth 5.3, an IP67 waterproof and dustproof design, and a built-in power bank, it’s the perfect portable speaker for outdoor parties, beach trips, or home entertainment. With its rugged build, modern design, and eco-friendly materials, the Boombox 4 ensures top-tier performance and durability—your ultimate music companion anywhere, anytime.",
          "Connection Type: AC-in, USB-C",
          "Bluetooth Version: 5.4",
          "Bluetooth Profiles: A2DP 1.4, AVRCP 1.6",
          "Bluetooth Transmitter Power: &le; 14dBm (EIRP)",
          "Frequency Response: 37Hz – 20kHz",
          "Battery Type: Rechargeable Li-ion",
          "Battery Capacity / Voltage: 99.02Wh (21.6V / 4584mAh)",
          "Battery Life: Up to 28 hours of continuous playtime",
          "Battery Charge Time: Approximately 3 hours",
          "Music Play Time: Up to 6 hours with Playtime Boost (varies by volume and content)",
          "Signal-to-Noise Ratio: > 80dB",
          "Output Power (W):",
          "AC Mode: 2 × 65W RMS Woofer + 2 × 40W RMS Tweeter",
          "Battery Mode: 2 × 60W RMS Woofer + 2 × 40W RMS Tweeter",
          "Extra Features: AI Sound Boost, JBL Playtime Boost, Auracast for multi-speaker connection, Bass Boost settings",
          "Accessories Included: AC Power Cable (2000mm / 78.7”)",
          "Durability: IP68 dustproof and waterproof rating for ultimate outdoor protection",
        ],
      },
      {
        heading: "Unmatched JBL Pro Sound Performance",
        paragraphs: [
          "Experience the legendary JBL Original Pro Sound with the Boombox 4, featuring upgraded drivers that produce even clearer highs, punchier mids, and deeper bass. With its advanced acoustic design, this speaker delivers a room-filling and distortion-free sound experience at any volume. From soft melodies to booming beats, every note feels alive and immersive—perfect for music lovers who demand the best.",
        ],
      },
      {
        heading: "Massive Power and Long-Lasting Battery Life",
        paragraphs: [
          "The JBL Boombox 4 comes equipped with a powerful built-in rechargeable Li-ion battery that offers up to 24 hours of continuous playtime on a single charge. You can enjoy your favorite tracks all day and night without interruption. Charging is simple with the included AC power cord, and the speaker’s USB-C port allows you to power up your devices on the go. With fast recharging and versatile connectivity, it’s always ready for your next adventure.",
        ],
      },
      {
        heading: "Rugged, Waterproof, and Built for Adventure",
        paragraphs: [
          "Designed with an IP68 waterproof and dustproof rating, the JBL Boombox 4 is built to withstand any environment. Take it to the pool, beach, or mountains without worrying about water splashes or dust. Its durable exterior and sturdy handle make it easy to carry, ensuring you can enjoy powerful sound anywhere your journey takes you.",
        ],
      },
      {
        heading: "Modern Design with Intuitive Controls",
        paragraphs: [
          "The Boombox 4 features a sleek, modern look with bold JBL branding and easy-to-use control buttons. Its sturdy handle design makes it ultra-portable while maintaining a stylish appeal. The integrated LED indicators let you check battery levels and connection status at a glance, keeping you in control of your music experience.",
        ],
      },
      {
        heading: "Seamless Wireless Connectivity",
        paragraphs: [
          "With Bluetooth 5.4 technology, the JBL Boombox 4 provides faster and more stable wireless connections to your smartphone, tablet, or laptop. It also supports Auracast™, allowing you to connect multiple JBL speakers for an even bigger, synchronized sound. Stream your favorite playlists effortlessly and experience uninterrupted, high-quality audio anywhere.",
        ],
      },
      {
        heading: "Eco-Friendly and Future-Ready",
        paragraphs: [
          "JBL continues its commitment to sustainability with the Boombox 4, featuring recycled materials and eco-friendly packaging. You get premium sound while helping reduce environmental impact—a win for both music and the planet. For those who demand power, clarity, and durability in a portable speaker, the JBL Boombox 4 stands above the rest. It’s the perfect combination of cutting-edge sound technology, rugged design, and long-lasting battery life, delivering the ultimate wireless audio experience for any occasion.",
        ],
      },
      {
        heading: "Buying the JBL Boombox 4 from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
