/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/jbl-xtreme-5.jpeg";
import img2 from "@/images/products/jbl-xtreme-5/02-jbl-xtreme-5-squad.jpeg";
import img3 from "@/images/products/jbl-xtreme-5/03-jbl-xtreme-5-blue.jpeg";

export const jblXtreme5: ProductDetail = {
  breadcrumb: ["Headphone & Speaker", "Speaker", "JBL"],
  gallery: [img1, img2, img3],
  inStock: true,

  highlights: [
    "Frequency Response: 40 Hz-20k Hz",
    "Transducer: 2 x 0.75\"",
    "IP68 Waterproof and Dustproof",
    "Maximum 28 hours of playtime",
  ],

  colors: [
    { name: "Squad", hex: "#737D62", image: img2 },
    { name: "Black", hex: "#000000", image: img1 },
    { name: "Blue", hex: "#035BBC", image: img3 },
  ],

  emi: { months: 6, perMonth: 7167 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["JBL"] },
        { label: "Model Name", value: ["XTREME 5"] },
      ],
    },
    {
      title: "Main Features",
      rows: [
        { label: "Connection Type", value: ["USB-C"] },
        { label: "Bluetooth Version", value: ["6.0"] },
        { label: "Bluetooth Profiles", value: ["A2DP 1.4, AVRCP 1.6"] },
        { label: "Bluetooth Transmitter Power", value: ["≤ 15dBm (EIRP)"] },
        { label: "Frequency Response", value: ["40 Hz - 20k Hz"] },
        { label: "Battery Type", value: ["Li-ion 68Wh"] },
        { label: "Battery charge time", value: ["Charging time (hrs): 3.5"] },
        { label: "Music play time", value: ["28 Hours"] },
        { label: "Signal / Noise Ratio", value: ["> 80 dB"] },
        { label: "Input Impedance", value: ["5V / 9V / 12V / 15V 3A, 20V / 4A"] },
        { label: "Output power (W)", value: ["1 x 90W RMS Woofer + 2 x 20W RMS Tweeter (AC power mode) 1 x 60W RMS Woofer + 2 x 15W RMS Tweeter (Battery mode)"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["13.6 x 6.5 x 6.1 inches"] },
        { label: "Weight", value: ["2.9kg"] },
        { label: "Colors", value: ["Black, Blue, Squad"] },
      ],
    },
  ],

  description: {
    title: "JBL Xtreme 5",
    blocks: [
      {
        paragraphs: [
          "Experience powerful JBL Pro Sound with the all-new JBL Xtreme 5 portable Bluetooth speaker. Designed for deep bass, long battery life, and rugged outdoor use, this premium speaker features AI Sound Boost, IP68 waterproof protection, Bluetooth connectivity, and extended playtime.",
        ],
      },
      {
        heading: "Key Features of JBL Xtreme 5",
        paragraphs: [
          "Massive JBL Pro Sound with AI Sound Boost",
          "Up to 24–28 hours battery backup",
          "IP68 waterproof and dustproof design",
          "Advanced Bluetooth connectivity",
          "Auracast multi-speaker pairing support",
          "USB-C audio playback and charging",
          "Built-in power bank feature",
          "Rugged portable design with strap",
        ],
      },
      {
        heading: "JBL Xtreme 5 Full Description",
        paragraphs: [
          "The JBL Xtreme 5 is a high-performance portable Bluetooth speaker built for users who want powerful bass, clear sound, and reliable performance. With advanced AI Sound Boost technology, the speaker enhances audio output to deliver louder and cleaner sound with minimal distortion.",
          "This speaker is ideal for outdoor use in Bangladesh thanks to its IP68 waterproof and dustproof rating. It performs reliably during travel, outdoor gatherings, and everyday use.",
          "The speaker offers stable wireless streaming and supports multi-speaker connection through Auracast, allowing you to expand your sound setup easily.",
          "The built-in battery delivers long playback time, making it suitable for extended listening sessions. The USB-C port supports both fast charging and wired audio playback.",
        ],
      },
      {
        heading: "Why Buy JBL Xtreme 5 in Bangladesh?",
        paragraphs: [
          "Suitable for both indoor and outdoor use",
          "Strong bass performance for music and entertainment",
          "Durable and waterproof build quality",
          "Long battery backup for extended usage",
          "Reliable sound quality from JBL",
        ],
      },
      {
        heading: "What is the price of JBL Xtreme 5 in Bangladesh?",
        paragraphs: [
          "The price may vary depending on availability and seller. Please check the product page for the latest price.",
        ],
      },
      {
        heading: "Is JBL Xtreme 5 waterproof?",
        paragraphs: [
          "Yes, it comes with IP68 waterproof and dustproof protection.",
        ],
      },
      {
        heading: "How long does the battery last?",
        paragraphs: [
          "The speaker provides long playback time suitable for all-day use.",
        ],
      },
      {
        heading: "Can I connect multiple speakers?",
        paragraphs: [
          "Yes, Auracast allows multi-speaker connection.",
        ],
      },
      {
        heading: "Is it good for outdoor use?",
        paragraphs: [
          "Yes, the speaker is designed for outdoor environments with durable construction.",
        ],
      },
      {
        heading: "Related Products",
        paragraphs: [
          "JBL Charge 6",
          "JBL Boombox 4",
          "JBL Flip 7",
          "JBL Bluetooth Speakers",
        ],
      },
      {
        heading: "Buying the JBL XTREME 5 Portable Bluetooth Speaker from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
