/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/jbl-flip-7-portable-wireless-speaker.jpeg";
import img2 from "@/images/products/jbl-flip-7-portable-wireless-speaker/02-jbl-flip-7-portable-wireless-speaker-black-28.jpeg";
import img3 from "@/images/products/jbl-flip-7-portable-wireless-speaker/03-jbl-flip-7-portable-wireless-speaker-black482.jpeg";
import img4 from "@/images/products/jbl-flip-7-portable-wireless-speaker/04-jbl-flip-7-portable-wireless-speaker-black-1858.jpeg";
import img5 from "@/images/products/jbl-flip-7-portable-wireless-speaker/05-jbl-flip-7-portable-wireless-speaker-black-3883.jpeg";
import img6 from "@/images/products/jbl-flip-7-portable-wireless-speaker/06-jbl-flip-7-portable-wireless-speaker-black-4580.jpeg";
import img7 from "@/images/products/jbl-flip-7-portable-wireless-speaker/07-jbl-flip-7-portable-wireless-speaker-blue-1490.jpeg";
import img8 from "@/images/products/jbl-flip-7-portable-wireless-speaker/08-jbl-flip-7-portable-wireless-speaker-blue482.jpeg";
import img9 from "@/images/products/jbl-flip-7-portable-wireless-speaker/09-jbl-flip-7-portable-wireless-speaker-blue-2789.jpeg";
import img10 from "@/images/products/jbl-flip-7-portable-wireless-speaker/10-jbl-flip-7-portable-wireless-speaker-blue-3502.jpeg";
import img11 from "@/images/products/jbl-flip-7-portable-wireless-speaker/11-jbl-flip-7-portable-wireless-speaker-blacknorange-363.jpeg";
import img12 from "@/images/products/jbl-flip-7-portable-wireless-speaker/12-jbl-flip-7-portable-wireless-speaker-blacknorange-2580.jpeg";
import img13 from "@/images/products/jbl-flip-7-portable-wireless-speaker/13-jbl-flip-7-portable-wireless-speaker-blacknorange-1554.jpeg";
import img14 from "@/images/products/jbl-flip-7-portable-wireless-speaker/14-jbl-flip-7-portable-wireless-speaker-blacknorange52.jpeg";
import img15 from "@/images/products/jbl-flip-7-portable-wireless-speaker/15-jbl-flip-7-portable-wireless-speaker-pink-3974.jpeg";
import img16 from "@/images/products/jbl-flip-7-portable-wireless-speaker/16-jbl-flip-7-portable-wireless-speaker-pink-1154.jpeg";
import img17 from "@/images/products/jbl-flip-7-portable-wireless-speaker/17-jbl-flip-7-portable-wireless-speaker-pink-250.jpeg";
import img18 from "@/images/products/jbl-flip-7-portable-wireless-speaker/18-jbl-flip-7-portable-wireless-speaker-pink832.jpeg";
import img19 from "@/images/products/jbl-flip-7-portable-wireless-speaker/19-jbl-flip-7-portable-wireless-speaker-red-3812.jpeg";
import img20 from "@/images/products/jbl-flip-7-portable-wireless-speaker/20-jbl-flip-7-portable-wireless-speaker-red-2494.jpeg";
import img21 from "@/images/products/jbl-flip-7-portable-wireless-speaker/21-jbl-flip-7-portable-wireless-speaker-red-1837.jpeg";
import img22 from "@/images/products/jbl-flip-7-portable-wireless-speaker/22-jbl-flip-7-portable-wireless-speaker-red400.jpeg";
import img23 from "@/images/products/jbl-flip-7-portable-wireless-speaker/23-jbl-flip-7-portable-wireless-speaker-sand-3367.jpeg";
import img24 from "@/images/products/jbl-flip-7-portable-wireless-speaker/24-jbl-flip-7-portable-wireless-speaker-sand-278.jpeg";
import img25 from "@/images/products/jbl-flip-7-portable-wireless-speaker/25-jbl-flip-7-portable-wireless-speaker-sand-1139.jpeg";
import img26 from "@/images/products/jbl-flip-7-portable-wireless-speaker/26-jbl-flip-7-portable-wireless-speaker-sand653.jpeg";
import img27 from "@/images/products/jbl-flip-7-portable-wireless-speaker/27-jbl-flip-7-portable-wireless-speaker-squad-3665.jpeg";
import img28 from "@/images/products/jbl-flip-7-portable-wireless-speaker/28-jbl-flip-7-portable-wireless-speaker-squad-2207.jpeg";
import img29 from "@/images/products/jbl-flip-7-portable-wireless-speaker/29-jbl-flip-7-portable-wireless-speaker-squad-1946.jpeg";
import img30 from "@/images/products/jbl-flip-7-portable-wireless-speaker/30-jbl-flip-7-portable-wireless-speaker-squad635.jpeg";
import img31 from "@/images/products/jbl-flip-7-portable-wireless-speaker/31-jbl-flip-7-portable-wireless-speaker-white-3648.jpeg";
import img32 from "@/images/products/jbl-flip-7-portable-wireless-speaker/32-jbl-flip-7-portable-wireless-speaker-white-1884.jpeg";
import img33 from "@/images/products/jbl-flip-7-portable-wireless-speaker/33-jbl-flip-7-portable-wireless-speaker-white-2113.jpeg";
import img34 from "@/images/products/jbl-flip-7-portable-wireless-speaker/34-jbl-flip-7-portable-wireless-speaker-white190.jpeg";

export const jblFlip7PortableWirelessSpeaker: ProductDetail = {
  breadcrumb: [
    { label: "Headphone & Speaker", slug: "headphone-speaker" },
    { label: "Speaker", slug: "speakers" },
    { label: "JBL", slug: "jbl-speaker" },
  ],
  gallery: [img1, img2, img3, img4, img5, img6, img7, img8, img9, img10, img11, img12, img13, img14, img15, img16, img17, img18, img19, img20, img21, img22, img23, img24, img25, img26, img27, img28, img29, img30, img31, img32, img33, img34],
  inStock: true,

  highlights: [
    "Frequency response: 60 Hz - 20k Hz",
    "Signal-to-noise Ratio: > 80 dB",
    "Battery Type: Li-ion polymer 17.28 Wh",
    "Battery Charge Time: 2.5 hours (5V / 3A)",
  ],

  colors: [
    { name: "Black", hex: "#000000", image: img2 },
    { name: "Blue", hex: "#035BBC", image: img7 },
    { name: "Black / Orange", hex: "#CC3633", image: img11 },
    { name: "Pink", hex: "#FDAEC8", image: img15 },
    { name: "Red", hex: "#FF0000", image: img19 },
    { name: "Sand", hex: "#CAC3B3", image: img23 },
    { name: "Squad", hex: "#737D62", image: img27 },
    { name: "White", hex: "#ffffff", image: img31 },
  ],

  emi: { months: 6, perMonth: 2250 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["JBL"] },
        { label: "Model Name", value: ["Flip 7"] },
      ],
    },
    {
      title: "Main Features",
      rows: [
        { label: "Connection Type", value: ["5.4"] },
        { label: "Bluetooth Version", value: ["Wireless"] },
        { label: "Bluetooth Profiles", value: ["A2DP 1.4, AVRCP 1.6"] },
        { label: "Bluetooth Transmitter Power", value: ["≤ 14 dBm (EIRP)"] },
        { label: "Frequency Response", value: ["60 Hz - 20k Hz"] },
        { label: "Battery Life", value: ["Li-ion polymer 17.28 Wh (equivalent to 3.6V /4800mAh)"] },
        { label: "Battery charge time", value: ["2.5 hours (5V / 3A)"] },
        { label: "Music play time", value: ["up to 14 hours (dependent on volume level and audio content)"] },
        { label: "Signal / Noise Ratio", value: ["> 80 dB"] },
        { label: "Output power (W)", value: ["25 W RMS for woofer, 10 W RMS for tweeter"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["182.5 x 69.5 x 71.5 mm/ 7.19 x 2.7x 2.8 \""] },
        { label: "Weight", value: ["0.56 kg/ 1.23 lbs"] },
        { label: "Colors", value: ["White"] },
      ],
    },
  ],

  description: {
    title: "JBL Flip 7 Portable Wireless Speaker",
    blocks: [
      {
        paragraphs: [
          "Introducing the JBL Flip 7 Portable Wireless Speaker – your ultimate companion for on-the-go music enjoyment. Compact yet powerful, the JBL Flip 7 delivers immersive sound, long-lasting battery life, and the convenience of wireless connectivity. Whether you're chilling by the pool, hitting the road, or hanging out with friends, the Flip 7 is designed to keep the music flowing with ease and style.",
        ],
      },
      {
        heading: "Key Features of JBL Flip 7 Portable Speaker",
        paragraphs: [
          "The JBL Flip 7 is not just another portable speaker – it's a game-changer when it comes to portable sound. Packed with features to enhance your audio experience, the Flip 7 ensures that you get the best out of every song, podcast, or movie. Let’s dive into the standout features of this amazing speaker:",
        ],
      },
      {
        heading: "Seamless Wireless Connectivity",
        paragraphs: [
          "With Bluetooth 5.4, the JBL Flip 7 allows you to effortlessly connect your smartphone, tablet, or laptop to stream your favorite music. The Bluetooth profiles supported, including A2DP 1.4 and AVRCP 1.6, ensure smooth and uninterrupted audio performance. Whether you're at home or on the go, the wireless connectivity of the JBL Flip 7 ensures a hassle-free listening experience. Experience exceptional sound with the JBL Flip 7. It features a frequency response range of 60 Hz - 20 kHz, providing rich lows, clear mids, and crisp highs. The powerful 25W RMS woofer and 10W RMS tweeter deliver deep bass and detailed treble, ensuring that every track sounds dynamic and full of life. Whether you're listening to pop, rock, or electronic music, the Flip 7 ensures high-quality sound every time.",
        ],
      },
      {
        heading: "Long-Lasting Battery for Nonstop Fun",
        paragraphs: [
          "The JBL Flip 7 is equipped with a 17.28 Wh Li-ion polymer battery, offering up to 14 hours of playtime on a single charge. Enjoy your music for hours, whether you're lounging on the beach or throwing a backyard party. The Flip 7’s battery life is designed to last as long as you do, depending on the volume and content you’re playing. Plus, with a fast charge time of just 2.5 hours (5V/3A), you can quickly recharge and get back to enjoying your tunes.",
        ],
      },
      {
        heading: "Compact and Portable Design",
        paragraphs: [
          "Weighing just 0.56 kg (1.23 lbs), the JBL Flip 7 is incredibly lightweight and portable. Its compact design (182.5 x 69.5 x 71.5 mm) makes it easy to carry wherever you go. Whether you're traveling, hiking, or heading to a picnic, this speaker fits perfectly into your bag or backpack, so you can take your music anywhere.",
        ],
      },
      {
        heading: "Buying the JBL Flip 7 Portable Wireless Speaker from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
