/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/macbook-pro-14-inch-m5-chip-16gb-1tb.jpeg";
import img2 from "@/images/products/macbook-pro-14-inch-m5-chip-16gb-1tb/02-macbook-pro-14-inch-m5-chip-silver776.jpeg";
import img3 from "@/images/products/macbook-pro-14-inch-m5-chip-16gb-1tb/03-macbook-pro-14-inch-m5-chip-silver-1318.jpeg";
import img4 from "@/images/products/macbook-pro-14-inch-m5-chip-16gb-1tb/04-macbook-pro-14-inch-m5-chip-silver-2429.jpeg";
import img5 from "@/images/products/macbook-pro-14-inch-m5-chip-16gb-1tb/05-macbook-pro-14-inch-m5-chip-silver-3446.jpeg";
import img6 from "@/images/products/macbook-pro-14-inch-m5-chip-16gb-1tb/07-macbook-pro-14-inch-m5-chip-space-black-1374.jpeg";
import img7 from "@/images/products/macbook-pro-14-inch-m5-chip-16gb-1tb/08-macbook-pro-14-inch-m5-chip-space-black-2652.jpeg";
import img8 from "@/images/products/macbook-pro-14-inch-m5-chip-16gb-1tb/09-macbook-pro-14-inch-m5-chip-space-black-3314.jpeg";
import img9 from "@/images/products/macbook-pro-14-inch-m5-chip-16gb-1tb/10-macbook-pro-14-inch-m5-chip-new.jpg-2697.jpeg";

export const macbookPro14InchM5Chip16gb1tb: ProductDetail = {
  breadcrumb: ["Mac", "MacBook"],
  gallery: [img1, img2, img3, img4, img5, img6, img7, img8, img9],
  inStock: true,

  highlights: [
    "Processor: Apple M5 chip with 10-core CPU",
    "RAM: 16GB Storage: 1TB",
    "Display: 14.2\" Liquid Retina XDR display (3024x1964)",
    "Features: Backlit Magic Keyboard, Touch ID",
  ],

  colors: [
    { name: "Silver", hex: "#ededed", image: img2 },
    { name: "Space Black", hex: "#17161B", image: img1 },
  ],

  emi: { months: 12, perMonth: 28333 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["Apple"] },
        { label: "Model Name", value: ["MacBook Pro"] },
      ],
    },
    {
      title: "Processor",
      rows: [
        { label: "Processor Core", value: ["10 Core CPU with 4 performance cores and 6 efficiency cores 16-core Neural Engine 153GB/s memory bandwidth"] },
      ],
    },
    {
      title: "Display",
      rows: [
        { label: "Size", value: ["14.2-inch"] },
        { label: "Type", value: ["Liquid Retina XDR display"] },
        { label: "Resolution", value: ["Liquid Retina XDR display;2 3024-by-1964 native resolution at 254 pixels per inch"] },
        { label: "Refresh Rate", value: ["ProMotion technology for adaptive refresh rates up to 120Hz", "Fixed refresh rates: 47.95Hz, 48.00Hz, 50.00Hz, 59.94Hz, 60.00Hz"] },
        { label: "Display Features", value: ["XDR (Extreme Dynamic Range)", "1,000,000:1 contrast ratio", "XDR brightness: 1000 nits sustained full-screen, 1600 nits peak2 (HDR content only)", "SDR brightness: up to 1000 nits (outdoor)", "Color", "1 billion colors", "Wide color (P3)", "True Tone technology", "Configurable with: Nano-texture display"] },
      ],
    },
    {
      title: "Memory",
      rows: [
        { label: "RAM", value: ["16GB"] },
        { label: "RAM Type", value: ["Unified memory"] },
        { label: "Max RAM Capacity", value: ["Configurable to: 24GB or 32GB"] },
      ],
    },
    {
      title: "Storage",
      rows: [
        { label: "Type", value: ["SSD"] },
        { label: "Storage Capacity", value: ["1TB"] },
        { label: "Storage Upgrade", value: ["Configurable to 2TB, or 4TB"] },
      ],
    },
    {
      title: "Graphics",
      rows: [
        { label: "Model", value: ["10-core GPU", "Neural Accelerators", "Hardware-accelerated ray tracing"] },
        { label: "Graphics Memory", value: ["Shared"] },
      ],
    },
    {
      title: "Keyboard & Touchpad",
      rows: [
        { label: "Keyboard Type", value: ["Backlit Magic Keyboard"] },
        { label: "Keyboard Features", value: ["78 (U.S.) or 79 (ISO) keys including 12 full-height function keys and 4 arrow keys in an inverted‑T arrangement", "Touch ID", "Ambient light sensor"] },
        { label: "TouchPad", value: ["Force Touch trackpad for precise cursor control and pressure-sensing capabilities", "enables Force clicks, accelerators, pressure-sensitive drawing, and Multi-Touch gestures"] },
      ],
    },
    {
      title: "Camera & Audio",
      rows: [
        { label: "Webcam", value: ["12MP Center Stage camera with support for Desk View", "1080p HD video recording", "Advanced image signal processor with computational video"] },
        { label: "Speaker", value: ["High-fidelity six-speaker sound system with force-cancelling woofers"] },
        { label: "Microphone", value: ["Studio-quality three-mic array with high signal-to-noise ratio and directional beamforming", "3.5 mm headphone jack with advanced support for high-impedance headphones"] },
        { label: "Audio Features", value: ["Wide stereo sound", "Support for Spatial Audio when playing music or video with Dolby Atmos on built-in speakers", "Spatial Audio with dynamic head tracking when using AirPods (3rd generation), AirPods 4, AirPods Pro, AirPods Pro 2, and AirPods Max"] },
      ],
    },
    {
      title: "Ports & Slots",
      rows: [
        { label: "Card Reader", value: ["1x SDXC card slot"] },
        { label: "HDMI Port", value: ["1x HDMI"] },
        { label: "USB Type-C / Thunderbolt Port", value: ["3 x Thunderbolt 4/ USB 4 ports"] },
        { label: "Microphone Port", value: ["3.5 mm headphone jack"] },
      ],
    },
    {
      title: "Network & Connectivity",
      rows: [
        { label: "WiFi", value: ["Wi-Fi 6E (802.11ax)"] },
        { label: "Bluetooth", value: ["Bluetooth 5.3"] },
      ],
    },
    {
      title: "Security",
      rows: [
        { label: "Fingerprint Sensor", value: ["Touch ID"] },
      ],
    },
    {
      title: "Software",
      rows: [
        { label: "Operating System", value: ["macOS"] },
      ],
    },
    {
      title: "Battery & Power",
      rows: [
        { label: "Battery Type", value: ["Lithium‑polymer"] },
        { label: "Battery Capacity", value: ["Up to 24 hours video streaming", "Up to 16 hours wireless web", "72.4-watt-hour lithium-polymer battery"] },
        { label: "Adapter Type", value: ["70W USB-C Power Adapter", "USB-C to MagSafe 3 Cable", "Fast-charge capable with 96W or higher USB-C Power Adapter"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Other Features", value: ["Line voltage: 100V to 240V AC", "Frequency: 50Hz to 60Hz", "Operating temperature: 50° to 95° F (10° to 35° C)", "Storage temperature: –13° to 113° F (–25° to 45° C)", "Relative humidity: 0% to 90% noncondensing", "Operating altitude: tested up to 10,000 feet (3000 meters)", "Maximum storage altitude: 15,000 feet", "Maximum shipping altitude: 35,000 feet"] },
        { label: "Dimensions", value: ["Height: 0.61 inch (1.55 cm)", "Width: 12.31 inches (31.26 cm)", "Depth: 8.71 inches (22.12 cm)"] },
        { label: "Weight", value: ["3.4 pounds (1.55 kg)"] },
        { label: "Color", value: ["Space Black, Silver"] },
      ],
    },
  ],

  description: {
    title: "MacBook Pro 14\" M5 Chip 16GB/1TB (10C CPU 10C GPU)",
    blocks: [
      {
        paragraphs: [
          "The MacBook Pro 14\" M5 Chip 16GB/1TB (10C CPU 10C GPU) redefines performance and creativity in one sleek, professional machine. Designed for those who demand power, efficiency, and visual brilliance, this 2025 MacBook Pro takes everything Apple is known for and elevates it with the next-generation Apple M5 chip. Whether you’re editing 8K videos, designing 3D models, coding complex software, or streaming on the go—this laptop handles it all with unmatched ease.",
        ],
      },
      {
        heading: "Key Features of MacBook Pro 14\" M5 Chip 16GB/1TB",
        paragraphs: [
          "The 14.2-inch Liquid Retina XDR display on the MacBook Pro 14\" M5 Chip delivers breathtaking color accuracy and brightness. With a 3024-by-1964 resolution and ProMotion technology supporting up to 120Hz adaptive refresh rate, every scroll, edit, and animation feels silky smooth. The XDR brightness of up to 1600 nits (HDR) and 1000 nits (SDR) ensures vibrant, lifelike visuals whether you’re indoors or working in bright sunlight. Combined with True Tone technology and wide P3 color, your creative work has never looked better.",
          "Processor: Apple M5 chip with 10-core CPU (4 performance cores + 6 efficiency cores)",
          "Neural Engine: 16-core Neural Engine with 153GB/s memory bandwidth",
          "Graphics: 10-core GPU with Neural Accelerators and hardware-accelerated ray tracing",
          "Memory (RAM): 16GB unified memory (configurable up to 32GB)",
          "Storage: 1TB SSD (configurable up to 2TB or 4TB)",
          "Size: 14.2-inch Liquid Retina XDR display",
          "Resolution: 3024-by-1964 native resolution at 254 pixels per inch",
          "Brightness: 1000 nits sustained (XDR), 1600 nits peak (HDR content), 1000 nits (SDR outdoor)",
          "Contrast Ratio: 1,000,000:1",
          "Color: 1 billion colors, wide color (P3), True Tone technology",
          "Refresh Rate: ProMotion adaptive refresh rates up to 120Hz (fixed: 47.95Hz, 48.00Hz, 50.00Hz, 59.94Hz, 60.00Hz)",
          "Display Options: Configurable with Nano-texture glass",
          "Keyboard Type: Backlit Magic Keyboard",
          "Keys: 78 (U.S.) or 79 (ISO) keys with 12 full-height function keys",
          "Features: Touch ID, ambient light sensor",
          "Touchpad: Force Touch trackpad with pressure-sensing and Multi-Touch gestures",
          "Webcam: 12MP Center Stage camera with Desk View and 1080p HD recording",
          "Processor: Advanced image signal processor with computational video",
          "Speakers: High-fidelity six-speaker sound system with force-cancelling woofers",
          "Microphone: Studio-quality three-mic array with directional beamforming",
          "Battery Life: Up to 24 hours video playback, Up to 16 hours wireless web",
          "Battery Type: 72.4-watt-hour lithium-polymer battery",
          "Charging: 70W USB-C Power Adapter, USB-C to MagSafe 3 Cable",
        ],
      },
      {
        heading: "Next-Level Performance with Apple M5 Chip",
        paragraphs: [
          "At the heart of this MacBook Pro is the revolutionary Apple M5 chip, engineered for extraordinary performance and energy efficiency. Featuring a 10-core CPU with 4 performance cores and 6 efficiency cores, a 10-core GPU, and a 16-core Neural Engine, it delivers seamless multitasking, real-time rendering, and AI-accelerated workflows. Whether you’re compiling code or editing 4K video, the M5 chip ensures lightning-fast response with 153GB/s memory bandwidth and unified 16GB memory — expandable up to 32GB for professionals who need even more power.",
        ],
      },
      {
        heading: "Superfast SSD Storage for Every Workflow",
        paragraphs: [
          "The 1TB SSD storage gives you incredible speed and reliability, making loading large projects, apps, and files instantaneous. You can configure it up to 2TB or 4TB, ensuring ample room for your creative assets, photos, and video libraries without sacrificing performance. This Mac is built for those who move fast and need their tech to keep up.",
        ],
      },
      {
        heading: "Immersive Sound and Precision Audio",
        paragraphs: [
          "Apple’s high-fidelity six-speaker system brings theater-quality sound right to your workspace. With force-cancelling woofers, wide stereo, and Spatial Audio support with Dolby Atmos, your movies, music, and calls sound crystal clear. The studio-quality three-mic array ensures professional-grade audio capture, while the 3.5mm high-impedance headphone jack delivers exceptional listening detail for audiophiles.",
        ],
      },
      {
        heading: "Smart Connectivity and Pro-Level Ports",
        paragraphs: [
          "Connectivity is effortless with three Thunderbolt 4 / USB 4 ports, an HDMI port, an SDXC card slot, and a 3.5 mm headphone jack. With Wi-Fi 6E and Bluetooth 5.3, you can stay connected to high-speed networks and peripherals without lag. The MagSafe 3 charging port brings back the convenience of magnetic power connection, ensuring safety and easy plug-in every time.",
        ],
      },
      {
        heading: "Advanced Camera and Video Experience",
        paragraphs: [
          "Stay crystal clear on every video call with the 12MP Center Stage camera supporting 1080p HD recording and computational video enhancements. The camera automatically frames you perfectly during meetings or streams, while Desk View makes presentations smoother and more engaging. Whether you’re video conferencing or creating content, this is the best MacBook camera yet.",
        ],
      },
      {
        heading: "All-Day Battery Life for the Modern Pro",
        paragraphs: [
          "With up to 24 hours of video playback or 16 hours of wireless web use, the 72.4-watt-hour lithium-polymer battery ensures you can work, create, and stream without interruptions. The included 70W USB-C power adapter supports fast charging, and you can upgrade to a 96W adapter for even quicker top-ups—perfect for busy professionals on the move.",
        ],
      },
      {
        heading: "Elegant, Durable, and Built for Pros",
        paragraphs: [
          "Crafted from premium aluminum, the MacBook Pro 14\" M5 Chip is as stunning as it is strong. At just 1.55 kg, it’s lightweight yet durable enough for travel. Available in Space Black and Silver, it’s a true reflection of professional elegance. The Magic Keyboard with Touch ID ensures quick, secure logins, and the Force Touch trackpad offers precise control for creative workflows.",
        ],
      },
      {
        heading: "macOS – The Power of Software Harmony",
        paragraphs: [
          "Running the latest macOS, this MacBook Pro is optimized for both speed and efficiency. Enjoy seamless app transitions, advanced productivity features, and better integration with your iPhone, iPad, and Apple ecosystem. macOS also brings new AI-driven tools, enhancing how you create, communicate, and collaborate.",
        ],
      },
      {
        heading: "Buying the MacBook Pro 14\" M5 Chip 16GB/1TB (10C CPU 10C GPU) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
