/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/apple-macbook-air-15-inch-m4-chip-display-unit.jpeg";
import img2 from "@/images/products/macbook-air-15-inch-m4-chip-display-unit/02-macbook-air-13-inch-m4-chip-24gb-512gb-midnight35.jpeg";
import img3 from "@/images/products/macbook-air-15-inch-m4-chip-display-unit/03-macbook-air-13-inch-m4-chip-24gb-512gb-midnight-1490.jpeg";
import img4 from "@/images/products/macbook-air-15-inch-m4-chip-display-unit/04-macbook-air-13-inch-m4-chip-24gb-512gb-midnight-2817.jpeg";
import img5 from "@/images/products/macbook-air-15-inch-m4-chip-display-unit/05-macbook-air-13-inch-m4-chip-24gb-512gb-midnight-348.jpeg";

export const macbookAir15InchM4ChipDisplayUnit: ProductDetail = {
  breadcrumb: ["Mac", "MacBook"],
  gallery: [img1, img2, img3, img4, img5],
  inStock: false,

  highlights: [
    "Apple M4 chip",
    "1080p FaceTime HD camera",
    "3.5 mm Headphone jack",
    "Up to 18 hours of video streaming",
  ],

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["Apple"] },
        { label: "Model Name", value: ["MacBook Air"] },
      ],
    },
    {
      title: "Processor",
      rows: [
        { label: "Frequency Response", value: ["50Hz to 60Hz"] },
        { label: "Processor Core", value: ["10‑core CPU with 4 performance cores and 6 efficiency cores"] },
      ],
    },
    {
      title: "Chipset",
      rows: [
        { label: "Chipset Model", value: ["Apple M4 chip"] },
      ],
    },
    {
      title: "Display",
      rows: [
        { label: "Size", value: ["15.3-inch (diagonal)"] },
        { label: "Type", value: ["LED-backlit display with IPS"] },
        { label: "Resolution", value: ["2880-by-1864 native resolution at 224 pixels per inch"] },
        { label: "Display Features", value: ["500 nits brightness", "Support for 1 billion colors", "Wide color (P3)", "True Tone technology"] },
      ],
    },
    {
      title: "Memory",
      rows: [
        { label: "RAM", value: ["16GB unified memory"] },
        { label: "Max RAM Capacity", value: ["Upgrade to: 24GB or 32GB"] },
      ],
    },
    {
      title: "Storage",
      rows: [
        { label: "Storage Capacity", value: ["256GB SSD"] },
        { label: "Storage Upgrade", value: ["Upgrade to: 512GB, 1TB, or 2TB"] },
      ],
    },
    {
      title: "Graphics",
      rows: [
        { label: "Type", value: ["10‑core GPU"] },
      ],
    },
    {
      title: "Keyboard & Touchpad",
      rows: [
        { label: "Keyboard Type", value: ["Backlit Magic Keyboard"] },
        { label: "Keyboard Features", value: ["78 (U.S.) or 79 (ISO) keys including 12 full‑height function keys and 4 arrow keys in an inverted‑T arrangement", "Ambient light sensor", "Force Touch trackpad for precise cursor control and pressure‑sensing capabilities", "enables Force clicks, accelerators, pressure‑sensitive drawing, and Multi‑Touch gestures"] },
        { label: "TouchPad", value: ["Touch ID"] },
      ],
    },
    {
      title: "Camera & Audio",
      rows: [
        { label: "Webcam", value: ["12MP Center Stage camera with support for Desk View", "1080p HD video recording", "Advanced image signal processor with computational video"] },
        { label: "Speaker", value: ["Four-speaker sound system", "Support for Spatial Audio when playing music or video with Dolby Atmos on built-in speakers", "Spatial Audio with dynamic head tracking when using supported models of AirPods, AirPods Pro, and AirPods Max", "Three-mic array with directional beamforming", "Voice Isolation and Wide Spectrum microphone modes", "Enhanced voice clarity in audio and video calls", "3.5 mm headphone jack with advanced support for high‑impedance headphones"] },
        { label: "Audio Features", value: ["Supported formats include AAC, MP3, Apple Lossless, FLAC, Dolby Digital, Dolby Digital Plus, and Dolby Atmos"] },
      ],
    },
    {
      title: "Ports & Slots",
      rows: [
        { label: "Display Port", value: ["Yes"] },
        { label: "USB Type-C / Thunderbolt Port", value: ["MagSafe 3 charging port", "Thunderbolt 4 (up to 40Gb/s)", "USB 4 (up to 40Gb/s)", "Two Thunderbolt 4 (USB-C) ports with support"] },
        { label: "Microphone Port", value: ["3.5 mm headphone jack"] },
      ],
    },
    {
      title: "Network & Connectivity",
      rows: [
        { label: "WiFi", value: ["Wi-Fi 6E (802.11ax)"] },
        { label: "Bluetooth", value: ["V5.3"] },
      ],
    },
    {
      title: "Software",
      rows: [
        { label: "Operating System", value: ["macOS"] },
      ],
    },
    {
      title: "Battery & Power",
      rows: [
        { label: "Battery Type", value: ["Built-in 53.8‑watt‑hour lithium‑polymer battery"] },
        { label: "Battery Capacity", value: ["Up to 18 hours of video streaming", "Up to 15 hours of wireless web"] },
        { label: "Adapter Type", value: ["35W Dual USB-C Port Compact Power Adapter (included with M4 with 10‑core GPU", "USB-C to MagSafe 3 Cable", "Fast-charge capable with 70W USB-C Power Adapter"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Body Material", value: ["Metal"] },
        { label: "Dimensions", value: ["Height: 0.45 inch (1.15 cm)", "Width: 13.40 inches (34.04 cm)", "Depth: 9.35 inches (23.76 cm)"] },
        { label: "Weight", value: ["3.3 pounds (1.51 kg)"] },
        { label: "Color", value: ["Midnight"] },
      ],
    },
  ],

  description: {
    title: "MacBook Air 15\" M4 Chip 16/256GB Midnight (10C CPU 10C GPU) (Display Unit)",
    blocks: [
      {
        heading: "Buying the MacBook Air 15\" M4 Chip 16/256GB Midnight (10C CPU 10C GPU) (Display Unit) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
