/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/macbook-neo-512.png";
import img2 from "@/images/products/macbook-neo-8-256/07-macbook-neo-blush.jpeg";
import img3 from "@/images/products/macbook-neo-8-512/03-macbook-neo-blush-512gb.jpeg";
import img4 from "@/images/products/macbook-neo-8-256/09-macbook-neo-blush-2.jpeg";
import img5 from "@/images/products/macbook-neo-256.png";
import img6 from "@/images/products/macbook-neo-8-256/10-macbook-neo-indigo.jpeg";
import img7 from "@/images/products/macbook-neo-8-512/07-macbook-neo-indigo-512gb.jpeg";
import img8 from "@/images/products/macbook-neo-8-256/12-macbook-neo-indigo-2.jpeg";
import img9 from "@/images/products/macbook-neo-8-256/02-macbook-neo-8gb-512gb-silver-10.png";
import img10 from "@/images/products/macbook-neo-8-256/03-macbook-neo-silver.jpeg";
import img11 from "@/images/products/macbook-neo-8-256/04-macbook-neo-silver-1.jpeg";
import img12 from "@/images/products/macbook-neo-8-256/05-macbook-neo-silver-2.jpeg";
import img13 from "@/images/products/macbook-neo-8-256/13-macbook-neo-8gb-512gb-citrus-10.png";
import img14 from "@/images/products/macbook-neo-8-256/14-macbook-neo-citrus.jpeg";
import img15 from "@/images/products/macbook-neo-8-512/15-macbook-neo-citrus512gb.jpeg";
import img16 from "@/images/products/macbook-neo-8-256/16-macbook-neo-citrus-2.jpeg";

export const macbookNeo8512: ProductDetail = {
  breadcrumb: [
    { label: "Mac", slug: "apple-store" },
    { label: "MacBook", slug: "macbook" },
  ],
  gallery: [img1, img2, img3, img4, img5, img6, img7, img8, img9, img10, img11, img12, img13, img14, img15, img16],
  inStock: true,

  highlights: [
    "Processor: Apple A18 Pro chip with 6‑core CPU, 5‑core GPU",
    "RAM: 8GB Unified Memory, Storage: 512GB",
    "Display: 13-inch Liquid Retina display with IPS (2408 x 1506)",
    "Features: Backlit Magic Keyboard with Touch ID, Wi-Fi 6E",
  ],

  colors: [
    { name: "Blush", hex: "#C9ADA2", image: img1 },
    { name: "Indigo", hex: "#69758D", image: img5 },
    { name: "Silver", hex: "#ededed", image: img9 },
    { name: "Citrus", hex: "#DDDC8C", image: img13 },
  ],

  emi: { months: 12, perMonth: 10667 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["Apple"] },
        { label: "Model Name", value: ["MacBook Neo"] },
      ],
    },
    {
      title: "Processor",
      rows: [
        { label: "Processor Core", value: ["6‑core CPU with 2 performance cores and 4 efficiency cores"] },
      ],
    },
    {
      title: "Chipset",
      rows: [
        { label: "Chipset Model", value: ["Apple A18 Pro chip"] },
      ],
    },
    {
      title: "Display",
      rows: [
        { label: "Size", value: ["13.0-inch (diagonal)"] },
        { label: "Type", value: ["Liquid Retina display", "LED-backlit display with IPS technology"] },
        { label: "Resolution", value: ["2408-by-1506 native resolution at 219 pixels per inch"] },
        { label: "Touch Screen", value: ["60Hz"] },
        { label: "Display Features", value: ["500 nits brightness", "Support for 1 billion colors", "sRGB color"] },
      ],
    },
    {
      title: "Memory",
      rows: [
        { label: "RAM", value: ["8GB"] },
        { label: "RAM Type", value: ["unified memory"] },
        { label: "Removable", value: ["Non-Removable"] },
      ],
    },
    {
      title: "Storage",
      rows: [
        { label: "Type", value: ["SSD"] },
        { label: "Storage Capacity", value: ["512GB"] },
      ],
    },
    {
      title: "Graphics",
      rows: [
        { label: "Type", value: ["Integrated Shared"] },
        { label: "Model", value: ["5‑core GPU", "ProRes encode and decode engine", "AV1 decode"] },
      ],
    },
    {
      title: "Keyboard & Touchpad",
      rows: [
        { label: "Keyboard Type", value: ["Magic Keyboard (with Touch ID on select models) | Multi-Touch trackpad"] },
        { label: "Keyboard Features", value: ["78 (ANSI) or 79 (ISO) keys including 12 full-height function keys"] },
        { label: "TouchPad", value: ["Multi-Touch trackpad for precise cursor control and support for gestures"] },
      ],
    },
    {
      title: "Camera & Audio",
      rows: [
        { label: "Webcam", value: ["1080p FaceTime HD camera", "1080p HD video recording", "Advanced image signal processor with computational video"] },
        { label: "Speaker", value: ["Dual-speaker sound system"] },
      ],
    },
    {
      title: "Ports & Slots",
      rows: [
        { label: "Card Reader", value: ["N/A"] },
        { label: "USB 2 Port", value: ["Charging", "USB 2 (up to 480Mb/s)"] },
        { label: "USB 3 Port", value: ["Charging", "DisplayPort", "USB 3 (up to 10Gb/s)"] },
        { label: "Microphone Port", value: ["3.5 mm jack"] },
      ],
    },
    {
      title: "Network & Connectivity",
      rows: [
        { label: "LAN", value: ["N/A"] },
        { label: "WiFi", value: ["Wi-Fi 6E (802.11ax)"] },
        { label: "Bluetooth", value: ["Bluetooth 6"] },
      ],
    },
    {
      title: "Security",
      rows: [
        { label: "Fingerprint Sensor", value: ["Magic Keyboard (with Touch ID on select models) | Multi-Touch trackpad"] },
      ],
    },
    {
      title: "Software",
      rows: [
        { label: "Operating System", value: ["macOS"] },
      ],
    },
    {
      title: "Battery & Power",
      rows: [
        { label: "Battery Type", value: ["lithium‑ion battery"] },
        { label: "Battery Capacity", value: ["36.5‑watt"] },
        { label: "Backup Time (Approx)", value: ["Up to 16 hours video streaming", "Up to 11 hours wireless web"] },
        { label: "Adapter Type", value: ["20W USB-C Power Adapter"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Body Material", value: ["MacBook Neo is made with 60% recycled content, including:", "90% recycled aluminum", "100% recycled cobalt and 95% recycled lithium in the battery", "100% recycled rare earth elements in all magnets", "100% recycled gold plating and tin solder in all Apple-designed printed circuit boards", "100% recycled copper in multiple printed circuit boards", "80% recycled steel in the battery tray, keyboard link bars, and speaker"] },
        { label: "Dimensions", value: ["Height: 0.50 inch (1.27 cm)", "Width: 11.71 inches (29.75 cm)", "Depth: 8.12 inches (20.64 cm)"] },
        { label: "Weight", value: ["2.7 pounds (1.23 kg)"] },
        { label: "Color", value: ["Blush, Indigo, Silver, Citrus"] },
      ],
    },
  ],

  description: {
    title: "MacBook Neo 8/512GB",
    blocks: [
      {
        paragraphs: [
          "The MacBook Neo 8/512GB is designed for users who want extra space without compromising performance. With a powerful Apple chipset, stunning Liquid Retina display, and expanded 512GB SSD storage, this laptop is built to handle everything from daily tasks to creative projects with ease. Sleek, lightweight, and efficient, it’s a perfect companion for work, study, and entertainment.",
        ],
      },
      {
        heading: "Apple A18 Pro Chip for Smooth Performance",
        paragraphs: [
          "At the heart of the MacBook Neo is the Apple A18 Pro chip, featuring a 6-core CPU with 2 performance cores and 4 efficiency cores. This advanced processor ensures fast performance, smooth multitasking, and energy efficiency. Whether you're editing videos, browsing multiple tabs, or running demanding applications, the MacBook Neo delivers a seamless experience.",
        ],
      },
      {
        heading: "512GB SSD Storage for More Space",
        paragraphs: [
          "With 512GB SSD storage, you get more room for your files, apps, photos, and videos. It also ensures lightning-fast boot times and quick file access, making your workflow faster and more efficient. This makes the MacBook Neo 8/512GB ideal for professionals and students who need reliable and spacious storage.",
        ],
      },
      {
        heading: "Immersive 13-inch Liquid Retina Display",
        paragraphs: [
          "The 13-inch Liquid Retina display offers sharp visuals with a resolution of 2408 x 1506 and 219 PPI. With support for 1 billion colors, sRGB color accuracy, and 500 nits brightness, you can enjoy vibrant visuals whether you're watching content, editing photos, or working on design projects.",
        ],
      },
      {
        heading: "8GB Unified Memory for Efficient Multitasking",
        paragraphs: [
          "The 8GB unified memory ensures smooth performance across multiple apps. It allows faster data access and improved system efficiency, helping you switch between tasks without lag.",
        ],
      },
      {
        heading: "Magic Keyboard with Touch ID & Precision Trackpad",
        paragraphs: [
          "The Magic Keyboard offers a comfortable typing experience with full-height function keys. Select models include Touch ID for secure and quick access. The Multi-Touch trackpad ensures precise control and supports intuitive gestures, enhancing productivity.",
        ],
      },
      {
        heading: "Advanced Camera and Audio Experience",
        paragraphs: [
          "The 1080p FaceTime HD camera delivers sharp and clear video quality, enhanced by an advanced image signal processor. Combined with a dual-speaker sound system, it provides an immersive audio-visual experience for calls, meetings, and entertainment.",
        ],
      },
      {
        heading: "Reliable Battery Life All Day Long",
        paragraphs: [
          "With up to 16 hours of video playback and 11 hours of web browsing, the MacBook Neo keeps you productive throughout the day. Its energy-efficient design ensures you spend more time working and less time charging.",
        ],
      },
      {
        heading: "Fast Connectivity and Modern Ports",
        paragraphs: [
          "Stay connected with Wi-Fi 6E and Bluetooth 6 for faster and more stable connections. The USB-C ports support charging, data transfer, and DisplayPort functionality, making it versatile for modern usage.",
        ],
      },
      {
        heading: "Eco-Friendly and Premium Build Quality",
        paragraphs: [
          "The MacBook Neo is crafted using 60% recycled materials, including 90% recycled aluminum and 100% recycled rare earth elements. It’s not just stylish and durable—it’s also environmentally responsible.",
        ],
      },
      {
        heading: "Buying the MacBook Neo 8/512GB from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
