/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/marshall-middleton-ii-bluetooth-speaker.jpeg";
import img2 from "@/images/products/marshall-middleton-ii-bluetooth-speaker/02-marshall-middleton-ii-bluetooth-speaker-1480.jpeg";
import img3 from "@/images/products/marshall-middleton-ii-bluetooth-speaker/03-marshall-middleton-ii-bluetooth-speaker-2868.jpeg";
import img4 from "@/images/products/marshall-middleton-ii-bluetooth-speaker/04-marshall-middleton-ii-bluetooth-speaker-3155.jpeg";
import img5 from "@/images/products/marshall-middleton-ii-bluetooth-speaker/05-marshall-middleton-ii-bluetooth-speaker-4568.jpeg";
import img6 from "@/images/products/marshall-middleton-ii-bluetooth-speaker/06-marshall-middleton-ii-bluetooth-speaker-513.jpeg";

export const marshallMiddletonIiBluetoothSpeaker: ProductDetail = {
  breadcrumb: ["Headphone & Speaker", "Speaker", "Marshall"],
  gallery: [img1, img2, img3, img4, img5, img6],
  inStock: true,

  highlights: [
    "Frequency Range: 50HZ - 20KHZ",
    "Wireless Connectivity: Bluetooth 5.3",
    "Bluetooth Range: 60M, 200FT",
    "Music Play Time: 30+ Hours",
  ],

  colors: [
    { name: "Black & Brass", hex: "#333333", image: img1 },
    { name: "Cream", hex: "#d4d4d8", image: img4 },
  ],

  emi: { months: 6, perMonth: 6333 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["Marshall"] },
        { label: "Model Name", value: ["Middleton II"] },
      ],
    },
    {
      title: "Main Features",
      rows: [
        { label: "Connection Type", value: ["Bluetooth"] },
        { label: "Bluetooth Version", value: ["5.3"] },
        { label: "Frequency Response", value: ["50HZ - 20KHZ"] },
        { label: "Amplifier Power", value: ["Two 30 Watt Class D Amplifiers For the Woofers", "Two 10 Watt Class D Amplifiers For the Tweeters"] },
        { label: "Battery Type", value: ["Rechargeable, replaceable, Li-ion battery"] },
        { label: "Battery charge time", value: ["3 hours to full recharge", "20 minutes gives 5 hours of playtime"] },
        { label: "Music play time", value: ["30+ hours"] },
        { label: "Others", value: ["IP67, Battery Preservation, Bluetooth Multipoint Connectivity, Codecs- SBC, AAC-mpeg 2 and LC3, Microphone system"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["Height: 110 mm / 4.33\"", "Width: 230 mmm / 9.05\"", "Depth: 98 mm / 3.86\""] },
        { label: "Weight", value: ["1.8 kg / 3.9 lbs"] },
        { label: "Colors", value: ["Black & Brass, Cream"] },
      ],
    },
  ],

  description: {
    title: "Marshall Middleton II Portable Bluetooth Speaker",
    blocks: [
      {
        paragraphs: [
          "The Marshall Middleton II Portable Bluetooth Speaker is built for people who want powerful sound, iconic design, and true portability in one premium package. Inspired by Marshall’s legendary rock heritage and upgraded with modern wireless technology, this speaker delivers rich audio performance wherever you go. Whether you’re at home, outdoors, or on the move, the Middleton II offers immersive sound, long battery life, and rugged durability that fits your lifestyle perfectly.",
        ],
      },
      {
        heading: "Signature Marshall Sound with Powerful Audio Performance",
        paragraphs: [
          "The Marshall Middleton II Bluetooth Speaker is engineered to deliver bold, room-filling sound with impressive clarity and depth. With a wide frequency response ranging from 50 Hz to 20 kHz, it reproduces deep bass, detailed mids, and crisp highs that bring every genre to life. From punchy rock tracks to smooth vocals and electronic beats, the sound remains balanced and distortion-free even at higher volumes. Under the hood, the speaker features two 30-watt Class D amplifiers for the woofers and two 10-watt Class D amplifiers for the tweeters, ensuring a powerful and immersive listening experience. This advanced amplifier setup allows the Middleton II to deliver strong low-end performance while keeping vocals and high frequencies clean and well-defined, making it ideal for both indoor and outdoor use.",
        ],
      },
      {
        heading: "Advanced Bluetooth 5.3 Connectivity for Seamless Streaming",
        paragraphs: [
          "Equipped with Bluetooth 5.3, the Marshall Middleton II Portable Bluetooth Speaker offers faster pairing, stronger signal stability, and improved energy efficiency. You can enjoy smooth wireless audio streaming with minimal lag, whether you’re listening to music, watching videos, or taking calls. The speaker also supports Bluetooth multipoint connectivity, allowing you to connect two devices simultaneously and switch between them effortlessly. Support for modern audio codecs such as SBC, AAC-MPEG 2, and LC3 ensures high-quality wireless sound across a wide range of devices. Whether you’re using an Android phone, iPhone, tablet, or laptop, the Middleton II delivers consistent and reliable audio performance.",
        ],
      },
      {
        heading: "Rugged IP67 Design for Outdoor Adventures",
        paragraphs: [
          "The Marshall Middleton II Portable Bluetooth Speaker is built to handle real-world conditions with confidence. Featuring an IP67 rating, it is both water-resistant and dustproof, making it suitable for outdoor use, beach trips, poolside parties, or unpredictable weather. You can enjoy your music without worrying about splashes, dust, or accidental exposure to the elements. Despite its rugged build, the speaker maintains a premium feel with Marshall’s signature design elements, combining durability with timeless style. It’s a speaker that looks as good as it sounds, no matter where you take it.",
        ],
      },
      {
        heading: "Built for Portability with Long-Lasting Battery Life",
        paragraphs: [
          "Designed to keep the music going all day and beyond, the Marshall Middleton II comes with a rechargeable and replaceable Li-ion battery that offers an impressive 30+ hours of music playback on a single charge. This makes it an excellent choice for long trips, outdoor gatherings, or extended listening sessions at home. When time is short, the quick charge feature ensures you’re never without music for long. Just 20 minutes of charging provides up to 5 hours of playtime, while a full recharge takes approximately 3 hours. The built-in battery preservation technology helps extend battery lifespan, ensuring reliable performance over time.",
        ],
      },
      {
        heading: "Buying the Marshall Middleton II Portable Bluetooth Speaker from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
