/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/marshall-kilburn-iii-portable-bluetooth-speaker.jpeg";
import img2 from "@/images/products/marshall-kilburn-iii-portable-bluetooth-speaker/02-marshall-kilburn-iii-portable-speaker-1741.jpeg";
import img3 from "@/images/products/marshall-kilburn-iii-portable-bluetooth-speaker/03-marshall-kilburn-iii-portable-speaker-2640.jpeg";
import img4 from "@/images/products/marshall-kilburn-iii-portable-bluetooth-speaker/04-marshall-kilburn-iii-portable-bluetooth-speaker-black-brass163.jpeg";
import img5 from "@/images/products/marshall-kilburn-iii-portable-bluetooth-speaker/05-marshall-kilburn-iii-portable-bluetooth-speaker-black-brass-1721.jpeg";
import img6 from "@/images/products/marshall-kilburn-iii-portable-bluetooth-speaker/06-marshall-kilburn-iii-portable-bluetooth-speaker-black-brass-2886.jpeg";
import img7 from "@/images/products/marshall-kilburn-iii-portable-bluetooth-speaker/07-marshall-kilburn-iii-portable-bluetooth-speaker-black-brass-33.jpeg";

export const marshallKilburnIiiPortableBluetoothSpeaker: ProductDetail = {
  breadcrumb: [
    { label: "Headphone & Speaker", slug: "headphone-speaker" },
    { label: "Speaker", slug: "speakers" },
    { label: "Marshall", slug: "marshall-speaker" },
  ],
  gallery: [img1, img2, img3, img4, img5, img6, img7],
  inStock: true,

  highlights: [
    "Clear, Powerful 50W Marshall Sound",
    "True Stereophonic 360∘ Sound",
    "Extended 50-Hour Battery Life",
    "Rugged and Road-Ready Design",
  ],

  colors: [
    { name: "Cream", hex: "#d4d4d8", image: img1 },
    { name: "Black & Brass", hex: "#333333", image: img4 },
  ],

  emi: { months: 6, perMonth: 8000 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["Marshall"] },
        { label: "Model Name", value: ["Kilburn III"] },
      ],
    },
    {
      title: "Main Features",
      rows: [
        { label: "Connection Type", value: ["Bluetooth"] },
        { label: "Bluetooth Version", value: ["Bluetooth 5.3", "Auracast"] },
        { label: "Driver Unit", value: ["Dynamic Driver"] },
        { label: "Frequency Response", value: ["45 Hz–20 kHz"] },
        { label: "Battery Type", value: ["‎1 Lithium Ion batteries required. (included)"] },
        { label: "Battery Life", value: ["50+ HOURS OF PORTABLE PLAYTIME"] },
        { label: "Charging Type", value: ["USB-C to USB-C charging cable"] },
        { label: "Battery charge time", value: ["‎3 Hours"] },
        { label: "Music play time", value: ["50+ hours"] },
        { label: "Others", value: ["‎Bass Boost, Built-In Powerbank, Portable", "Wired connectivity: AUX 3.5 mm", "Top panel controls:", "Bass", "Treble", "Volume", "On/off", "Media jog", "M-button", "Bluetooth button", "Water Resistance: IP54"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["273×150×169 mm", "10,74×5,9×6,65in"] },
        { label: "Weight", value: ["2.8 kg", "6.17 lb"] },
        { label: "Colors", value: ["Cream"] },
      ],
    },
  ],

  description: {
    title: "Marshall Kilburn III Portable Bluetooth Speaker",
    blocks: [
      {
        paragraphs: [
          "Unleash your music anywhere with the Marshall Kilburn III Portable Bluetooth Speaker, a powerhouse of sound packed into a classic, vintage-inspired design. Built for true music lovers, this speaker combines Marshall’s signature craftsmanship with cutting-edge wireless technology, giving you the freedom to enjoy immersive sound wherever life takes you.",
        ],
      },
      {
        heading: "Features of Marshall Kilburn III Speaker",
        paragraphs: [
          "The Marshall Kilburn III Portable Bluetooth Speaker delivers powerful, immersive 360° sound in a stylish, vintage-inspired design. With up to 20+ hours of playtime, Bluetooth 5.1 connectivity, and customizable bass and treble controls, it offers the perfect balance of performance and portability. Its splash-resistant build and iconic Marshall look make it ideal for both indoor and outdoor listening. The Marshall Kilburn III stays true to the brand’s heritage, featuring the iconic textured vinyl, salt-and-pepper fret, and the legendary script logo. Its durable build and water-resistant design make it perfect for both indoor and outdoor use. With a sturdy carrying strap reminiscent of a guitar strap, this speaker is made to move with your rhythm.",
        ],
      },
      {
        heading: "Powerful, Balanced Sound Performance",
        paragraphs: [
          "Experience room-filling audio with deep bass, clear mids, and crisp highs. The Kilburn III delivers a dynamic 360° sound that ensures everyone in the room hears music the way it was meant to be heard. Thanks to three dedicated Class D amplifiers, this speaker produces rich and powerful sound while maintaining clarity at any volume.",
        ],
      },
      {
        heading: "Advanced Bluetooth 5.1 Connectivity",
        paragraphs: [
          "Stay connected effortlessly with Bluetooth 5.1 technology, offering a stable, high-quality wireless connection up to 30 feet away. Pair your devices seamlessly and enjoy lag-free music streaming, whether you’re using your smartphone, tablet, or laptop. Fine-tune your listening experience with the classic Marshall analog control knobs for bass, treble, and volume. Whether you want deep, thumping bass or a brighter sound profile, the Kilburn III lets you adjust the sound to match your mood and style. Compact yet powerful, the Marshall Kilburn III Portable Bluetooth Speaker is designed for versatility. Its splash-resistant build and portable form make it the perfect choice for road trips, picnics, and outdoor parties — wherever great sound belongs.",
        ],
      },
      {
        heading: "Long-Lasting Battery Life",
        paragraphs: [
          "Keep the music going for hours on end with up to 20+ hours of portable playtime. The Marshall Kilburn III supports quick charging, giving you several hours of playback in just 20 minutes — perfect for those spontaneous adventures and outdoor gatherings.",
        ],
      },
      {
        heading: "Buying the Marshall Kilburn III Portable Bluetooth Speaker from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
