/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/oneplus-pad-4-12gb-512gb.jpeg";
import img2 from "@/images/products/oneplus-pad-4-12gb-512gb/02-oneplus-pad-4-dune-glow-1.jpeg";
import img3 from "@/images/products/oneplus-pad-4-12gb-512gb/03-oneplus-pad-4-dune-glow-2.jpeg";
import img4 from "@/images/products/oneplus-pad-4-12gb-512gb/04-oneplus-pad-4-dune-glow-3.jpeg";
import img5 from "@/images/products/oneplus-pad-4-12gb-512gb/05-oneplus-pad-4-dune-glow-4.jpeg";

export const oneplusPad412gb512gb: ProductDetail = {
  breadcrumb: [
    { label: "Tablets", slug: "tablets" },
    { label: "OnePlus", slug: "oneplus-tablet-pc" },
  ],
  gallery: [img1, img2, img3, img4, img5],
  inStock: true,

  highlights: [
    "Display: 13.2-inch / LCD",
    "Processor: Snapdragon 8 Elite Gen 5 Mobile Platform",
    "Camera: 13MP + 8MP",
    "Features: 13380 mAh / Up to 80W SUPERVOOC",
  ],

  colors: [
    { name: "Dune Glow", hex: "#766762", image: img1 },
  ],

  emi: { months: 6, perMonth: 18333 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["OnePlus"] },
        { label: "Model Name", value: ["Pad 4"] },
      ],
    },
    {
      title: "Main Feature",
      rows: [
        { label: "Display Type", value: ["LCD"] },
        { label: "Size", value: ["13.2-inch"] },
        { label: "Resolution", value: ["3392*2400"] },
        { label: "Refresh Rate", value: ["Up to 144 Hz, adaptive refresh"] },
        { label: "Brightness", value: ["700 nits (1000 nits HBM)"] },
        { label: "Processor", value: ["Snapdragon 8 Elite Gen 5 Mobile Platform"] },
        { label: "RAM", value: ["12GB"] },
        { label: "Storage", value: ["512GB"] },
        { label: "Connectivity", value: ["Wi-Fi 7, Bluetooth 6.0"] },
        { label: "Operating System", value: ["OxygenOS 16.0"] },
        { label: "Audio", value: ["8 Speakers (4 Woofers + 4 Tweeters)", "Microphones: 2"] },
        { label: "Others", value: ["Screen to Body Ratio: 89.4%", "Screen Color Depth: 12-bit (8+4-bit)", "Colour Gamut: DCI-P3 coverage 98%", "DeltaE≈0.7", "OnePlus AI"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimensions", value: ["289.71 x 209.76 x 5.94 mm"] },
        { label: "Weight", value: ["672g"] },
        { label: "Color", value: ["Dune Glow"] },
      ],
    },
    {
      title: "Camera",
      rows: [
        { label: "Front Camera", value: ["8MP"] },
        { label: "Rear Camera", value: ["13 MP"] },
        { label: "Video", value: ["Color spectrum sensor, LED flash", "4K@30fps, 1080p@30ps, gyro-EIS"] },
      ],
    },
    {
      title: "Battery",
      rows: [
        { label: "Capacity", value: ["13,380 mAh (typical)", "*The Battery has a rated capacity of 13,065 mAh"] },
        { label: "Charging", value: ["Up to 80W SUPERVOOC Charging"] },
      ],
    },
    {
      title: "Special Features",
      rows: [
        { label: "Sensors", value: ["Accelerometer", "proximity (accessories only)", "gyro", "compass"] },
        { label: "Bluetooth", value: ["Bluetooth 6.0, Bluetooth Low Energy, BLE Audio"] },
        { label: "WLAN", value: ["Wi-Fi 7 (802.11be)", "Wi-Fi 6 (802.11ax)", "Wi-Fi 5 (802.11ac)", "802.11a/b/g/n", "Wi-Fi Display", "WLAN Tethering", "Wi-Fi 2.4GHz 2x2+Wi-Fi 5GHz 2x2 Concurrent", "Wi-Fi 5GHz 160MHz", "2x2 MIMO"] },
        { label: "USB", value: ["Type-C (USB3.2 Gen1 @ 5Gbps)"] },
      ],
    },
  ],

  description: {
    title: "OnePlus Pad 4 (12/512GB)",
    blocks: [
      {
        paragraphs: [
          "The OnePlus Pad 4 (12/512GB) is a premium Android tablet built for users who demand top-tier performance, massive storage, and a seamless multitasking experience. Whether you're a professional, student, or entertainment enthusiast in Bangladesh, this tablet delivers unmatched speed, stunning visuals, and all-day battery life. With 12GB RAM and 512GB storage, it’s designed to handle heavy workloads, gaming, and media consumption effortlessly.",
        ],
      },
      {
        heading: "Why Buy OnePlus Pad 4 (12/512GB) in Bangladesh?",
        paragraphs: [
          "Looking for a high-performance tablet with large storage in Bangladesh? The OnePlus Pad 4 solves common problems like slow performance, limited storage, and poor display quality. It offers a future-proof experience with powerful hardware and refined software optimization.",
          "Massive 512GB storage for professionals and creators",
          "12GB RAM for ultra-smooth multitasking",
          "High refresh rate display for fluid visuals",
          "Long battery life for uninterrupted use",
          "Premium design with lightweight portability",
        ],
      },
      {
        heading: "Next-Level Performance with 12GB RAM",
        paragraphs: [
          "The OnePlus Pad 4 is engineered for speed. With 12GB RAM, it handles multiple apps, heavy files, and demanding games without lag. Perfect for users who need a reliable tablet for work and play.",
        ],
      },
      {
        heading: "Huge 512GB Storage – No More Space Issues",
        paragraphs: [
          "Say goodbye to storage anxiety. The 512GB internal storage allows you to store large files, videos, apps, and documents easily. Ideal for content creators, professionals, and students.",
        ],
      },
      {
        heading: "Immersive Display for Work & Entertainment",
        paragraphs: [
          "Experience vibrant colors, sharp details, and smooth scrolling with a high-resolution display. Whether you’re watching movies, editing content, or attending meetings, the visual quality enhances every task.",
        ],
      },
      {
        heading: "All-Day Battery with Fast Charging",
        paragraphs: [
          "The large battery ensures you stay productive throughout the day. From online classes to office work and entertainment, you won’t need frequent charging.",
        ],
      },
      {
        heading: "Premium Build Quality",
        paragraphs: [
          "The OnePlus Pad 4 features a sleek, modern design that feels premium in hand. Lightweight yet durable, it’s perfect for on-the-go use in Bangladesh.",
        ],
      },
      {
        heading: "For Students in Bangladesh",
        paragraphs: [
          "Attend online classes, read PDFs, take notes, and complete assignments with ease. The large display and fast performance make studying more efficient.",
        ],
      },
      {
        heading: "For Professionals & Remote Workers",
        paragraphs: [
          "Handle emails, documents, Zoom meetings, and multitasking effortlessly. It’s a powerful alternative to laptops for daily productivity.",
        ],
      },
      {
        heading: "For Gaming & Entertainment",
        paragraphs: [
          "Play high-end games, stream YouTube, Netflix, and browse social media with ultra-smooth performance and immersive visuals.",
        ],
      },
      {
        heading: "OnePlus Pad 4 (12/512GB) vs Other Tablets",
        paragraphs: [
          "Compared to tablets in the same category, the OnePlus Pad 4 offers more storage and better RAM capacity. It competes strongly with tablets from Samsung, Xiaomi, and Lenovo by delivering smoother performance and a more optimized user experience.",
        ],
      },
      {
        heading: "Buying Guide: Should You Buy OnePlus Pad 4 (12/512GB)?",
        paragraphs: [
          "If you are searching for a premium Android tablet in Bangladesh with massive storage, the OnePlus Pad 4 (12/512GB) is one of the best options. It is ideal for:",
          "Heavy multitasking and professional work",
          "Content creators needing large storage",
          "Students requiring smooth performance",
          "Entertainment lovers who want immersive visuals",
          "This tablet offers excellent value for money with its flagship features and future-ready performance.",
        ],
      },
      {
        heading: "Related Products & Internal Links",
        paragraphs: [
          "Explore More Tablets",
          "Shop OnePlus Devices",
          "Tablet Accessories",
          "Apple Products",
        ],
      },
      {
        heading: "Is OnePlus Pad 4 good for heavy multitasking?",
        paragraphs: [
          "Yes, with 12GB RAM and a powerful processor, it handles multitasking and heavy apps smoothly.",
        ],
      },
      {
        heading: "Is 512GB storage enough for long-term use?",
        paragraphs: [
          "Absolutely. 512GB is more than enough for storing large files, apps, videos, and documents without worrying about space.",
        ],
      },
      {
        heading: "Can I use OnePlus Pad 4 for online classes and office work?",
        paragraphs: [
          "Yes, it’s perfect for online learning, meetings, document editing, and daily productivity tasks.",
        ],
      },
      {
        heading: "Buying the OnePlus Pad 4 (12/512GB) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
