/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/oneplus-nord-buds-4-pro-earbuds.jpeg";
import img2 from "@/images/products/oneplus-nord-buds-4-pro-earbuds/02-oneplus-nord-buds-4-pro-upto-55db-nc-earbuds-1.jpeg";
import img3 from "@/images/products/oneplus-nord-buds-4-pro-earbuds/03-oneplus-nord-buds-4-pro-upto-55db-nc-earbuds-2.jpeg";
import img4 from "@/images/products/oneplus-nord-buds-4-pro-earbuds/04-oneplus-nord-buds-4-pro-upto-55db-nc-earbuds-3.jpeg";
import img5 from "@/images/products/oneplus-nord-buds-4-pro-earbuds/05-oneplus-nord-buds-4-pro-upto-55db-nc-earbuds-4.jpeg";
import img6 from "@/images/products/oneplus-nord-buds-4-pro-earbuds/06-oneplus-nord-buds-4-pro-upto-55db-nc-earbuds-5.jpeg";
import img7 from "@/images/products/oneplus-nord-buds-4-pro-earbuds/07-oneplus-nord-buds-4-pro-upto-55db-nc-earbuds-6.jpeg";
import img8 from "@/images/products/oneplus-nord-buds-4-pro-earbuds/08-oneplus-nord-buds-4-pro-upto-55db-nc-earbuds-7.jpeg";

export const oneplusNordBuds4ProEarbuds: ProductDetail = {
  breadcrumb: [
    { label: "Headphone & Speaker", slug: "headphone-speaker" },
    { label: "Earbuds", slug: "earbuds" },
    { label: "OnePlus", slug: "oneplus-earbuds" },
  ],
  gallery: [img1, img2, img3, img4, img5, img6, img7, img8],
  inStock: true,

  highlights: [
    "Driver: 12 mm dynamic driver",
    "Pro-level Real-time ANC, 6-mic AI Clear Call Noise Cancellation",
    "Battery: 530mAh (Case), 62mAh (Earbuds), Up to 54 hours Playback",
    "Bluetooth 6.0, Google Fast Pair, Microsoft Swift Pair, Dual Device Connectivity",
  ],

  colors: [
    { name: "Raven Black", hex: "#3F3F41", image: img1 },
    { name: "Radiant Gray", hex: "#C2C2C2", image: img5 },
  ],

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["OnePlus"] },
        { label: "Model Name", value: ["Nord Buds 4 Pro"] },
      ],
    },
    {
      title: "Main Feature",
      rows: [
        { label: "Connection Type", value: ["Bluetooth 6.0", "Bluetooth Codec: LHDC 5.0/AAC/SBC", "Google Fast Pair", "Microsoft Swift Pair", "Dual Connection"] },
        { label: "Frequency", value: ["20Hz - 40kHz"] },
        { label: "Microphone", value: ["Microphone Sensitivity", "-38dB", "Microphone", "6 microphones (3 mics per bud)"] },
        { label: "Impedance", value: ["28Ω"] },
        { label: "Battery Type", value: ["Wired: USB Type-C"] },
        { label: "Charging Case", value: ["60.00mm x 49.64mm x 25.04mm"] },
        { label: "Battery Capacity", value: ["Battery Capacity (earbuds): 62mAh, 0.242Wh", "Battery Capacity (charging case): 530mAh, 2.0617Wh"] },
        { label: "Charging Time", value: ["Earbuds: about 60 mins", "Earbuds + Case: about 90 mins"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Drivers", value: ["12 mm dynamic driver"] },
        { label: "Controls", value: ["Active Noise Cancellation", "Adaptive Noise Cancellation"] },
        { label: "Water Resistant", value: ["Yes"] },
        { label: "Bluetooth Range", value: ["10 meters"] },
        { label: "Dimension", value: ["Earbuds: 31mm x 20mm x 17.52mm", "Charging case: 60.00mm x 49.64mm x 25.04mm"] },
        { label: "Weight", value: ["43 Grams"] },
        { label: "Colors", value: ["Raven Black, Radiant Gray"] },
      ],
    },
  ],

  description: {
    title: "OnePlus Nord Buds 4 Pro Earbuds",
    blocks: [
      {
        paragraphs: [
          "The OnePlus Nord Buds 4 Pro Earbuds are designed to deliver powerful sound, smart connectivity, and premium comfort in a compact design. Whether you're listening to music, taking calls, or gaming, these true wireless earbuds offer a seamless and immersive audio experience for everyday use.",
        ],
      },
      {
        heading: "Premium Sound with 12mm Dynamic Drivers",
        paragraphs: [
          "Enjoy rich and detailed audio with the 12mm dynamic drivers, delivering deep bass, clear mids, and crisp highs. With a wide 20Hz–40kHz frequency range, the OnePlus Nord Buds 4 Pro ensures high-resolution sound quality for music lovers and audiophiles alike.",
        ],
      },
      {
        heading: "Advanced Active Noise Cancellation",
        paragraphs: [
          "Experience uninterrupted listening with Active Noise Cancellation (ANC) and Adaptive Noise Cancellation. These features intelligently reduce background noise, allowing you to focus on your music or calls even in noisy environments like public transport or busy streets.",
        ],
      },
      {
        heading: "Crystal-Clear Calls with 6 Microphones",
        paragraphs: [
          "Equipped with 6 microphones (3 per earbud) and a -38dB sensitivity, these earbuds deliver clear voice quality during calls. Whether you're attending meetings or chatting with friends, your voice stays sharp and noise-free.",
        ],
      },
      {
        heading: "Next-Gen Connectivity with Bluetooth 6.0",
        paragraphs: [
          "Stay connected with Bluetooth 6.0, ensuring faster pairing, stable connections, and low latency. Supported codecs like LHDC 5.0, AAC, and SBC enhance audio quality across devices. With Google Fast Pair and Microsoft Swift Pair, connecting to your devices is quick and effortless. The dual connection feature allows you to switch between devices seamlessly.",
        ],
      },
      {
        heading: "Long Battery Life & Fast Charging",
        paragraphs: [
          "The earbuds come with a 62mAh battery per bud and a 530mAh charging case, offering extended playback time. Fully charge the earbuds in about 60 minutes, while the case takes around 90 minutes. Perfect for all-day use without frequent charging interruptions.",
        ],
      },
      {
        heading: "Comfortable Design & Water Resistance",
        paragraphs: [
          "Designed for comfort, the earbuds are lightweight and ergonomic, weighing just 43g (with case). With water resistance, they are suitable for workouts, commuting, and daily use. Available in stylish Raven Black and Radiant Gray, they complement your modern lifestyle.",
        ],
      },
      {
        heading: "Smart Controls & User-Friendly Features",
        paragraphs: [
          "Control your music, calls, and noise cancellation easily with intuitive touch controls. The earbuds are designed to provide a hassle-free user experience, making them perfect for both casual and professional use.",
        ],
      },
      {
        heading: "Buying the OnePlus Nord Buds 4 Pro Earbuds from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
