/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/oppo-a6s-pro.jpeg";
import img2 from "@/images/products/oppo-a6s-pro/02-oppo-a6s-pro-2.jpeg";
import img3 from "@/images/products/oppo-a6s-pro/03-oppo-a6s-pro-1.jpeg";
import img4 from "@/images/products/oppo-a6s-pro/04-oppo-a6s-pro-3.jpeg";

export const oppoA6sPro: ProductDetail = {
  breadcrumb: [
    { label: "Phones", slug: "phone" },
    { label: "OPPO", slug: "oppo" },
  ],
  gallery: [img1, img2, img3, img4],
  inStock: true,

  highlights: [
    "Display: 6.57\" 120Hz AMOLED Display",
    "Processor: MediaTek Helio G100 Max",
    "Camera: 50MP + 2MP + 50MP",
    "Features: In-Display Fingerprint",
  ],

  colors: [
    { name: "Lumina Frost", hex: "#C7DFE8", image: img1 },
    { name: "Eclipse Blue", hex: "#2E3A52", image: img3 },
  ],

  emi: { months: 12, perMonth: 3333 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["OPPO"] },
        { label: "Model Name", value: ["A6s Pro"] },
      ],
    },
    {
      title: "Display",
      rows: [
        { label: "Size", value: ["6.57\""] },
        { label: "Type", value: ["AMOLED"] },
        { label: "Refresh Rate", value: ["120Hz"] },
        { label: "Brightness", value: ["1400nits"] },
        { label: "Features", value: ["Rainforce Touch + Gloves Touch"] },
      ],
    },
    {
      title: "Processor",
      rows: [
        { label: "Chipset", value: ["MediaTek Helio G100 Max"] },
        { label: "CPU Type", value: ["2.2GHz Octa Core Processor"] },
      ],
    },
    {
      title: "Memory",
      rows: [
        { label: "RAM", value: ["8GB"] },
        { label: "ROM", value: ["256GB"] },
      ],
    },
    {
      title: "Rear Camera",
      rows: [
        { label: "Resolution", value: ["50MP + 2MP"] },
        { label: "Features", value: ["Al Imaging: Al Portrait Glow, Al Eraser 2.0, Al Reflection Remover, Al Unblur, Al Clarity Enhancer, Al Recompose, Al Perfect Shot, Al Smart Image Matting 2.0, Al Studio, Al Night Portrate Al Smart Office: Al Document Summary, Al Document Translate, Al Rewriting, Al Assistant for Notes Al Networking: Al LinkBoost 3.0, Beaconlink 2.0 Al Gaming: Al GameBoost, Hyperboost 2.0, Underwater Photography + Videography"] },
      ],
    },
    {
      title: "Front Camera",
      rows: [
        { label: "Resolution", value: ["50MP"] },
        { label: "Features", value: ["Underwater Photography + Videography"] },
      ],
    },
    {
      title: "Audio",
      rows: [
        { label: "Speaker", value: ["Dual Stereo Speakers"] },
        { label: "Audio Features", value: ["300% Ultra Volume"] },
      ],
    },
    {
      title: "OS",
      rows: [
        { label: "Operating System", value: ["ColorOS 16"] },
      ],
    },
    {
      title: "Features",
      rows: [
        { label: "Fingerprint", value: ["In-Display Fingerprint"] },
        { label: "IP Rating", value: ["IP69K"] },
      ],
    },
    {
      title: "Battery",
      rows: [
        { label: "Type", value: ["7000mAh"] },
        { label: "Fast Charging", value: ["80W"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["Thickness: 7.99mm"] },
        { label: "Weight", value: ["190g"] },
        { label: "Body Material", value: ["Unibody metal-textured frame"] },
      ],
    },
  ],

  description: {
    title: "OPPO A6s Pro (8/256GB)",
    blocks: [
      {
        heading: "6.57” AMOLED Display with 120Hz Refresh Rate",
        paragraphs: [
          "Enjoy immersive visuals on the 6.57-inch AMOLED display with ultra-smooth 120Hz refresh rate. Whether you're scrolling social media, streaming HD videos, or playing competitive games, the higher refresh rate ensures fluid motion and better responsiveness. With up to 1400 nits peak brightness, the display remains clear even under bright sunlight. Advanced Rainforce Touch and Gloves Touch technology allows accurate screen interaction even with wet hands or while wearing gloves—perfect for outdoor users and professionals on the move. If you're searching for a smartphone with a bright AMOLED display and 120Hz refresh rate in Bangladesh, the OPPO A6s Pro is an excellent choice.",
        ],
      },
      {
        heading: "MediaTek Helio G100 Max Processor for Powerful Performance",
        paragraphs: [
          "Powered by the MediaTek Helio G100 Max chipset and a 2.2GHz Octa-Core processor, the OPPO A6s Pro delivers smooth performance for gaming, streaming, and multitasking. Apps open quickly, switching between tasks feels seamless, and heavy usage stays stable thanks to intelligent performance optimization. With 8GB RAM and 256GB internal storage, you get ample space for apps, high-resolution photos, 4K videos, and large game files. This generous storage capacity makes it ideal for power users who demand speed and space.",
        ],
      },
      {
        heading: "50MP AI Dual Rear Camera with Advanced Imaging Tools",
        paragraphs: [
          "Capture professional-quality photos with the 50MP + 2MP dual rear camera setup. The advanced AI imaging system enhances every shot with features like AI Portrait Glow, AI Eraser 2.0, AI Reflection Remover, AI Unblur, and AI Clarity Enhancer. From low-light portraits to creative compositions, AI Night Portrait and AI Recompose ensure every image looks stunning. The phone also supports Underwater Photography and Videography, making it perfect for adventure lovers. Additional smart tools such as AI Smart Image Matting 2.0 and AI Studio help you create social media-ready content instantly. If you are looking for a 50MP AI camera phone with advanced editing features, the OPPO A6s Pro stands out in its class.",
        ],
      },
      {
        heading: "50MP Front Camera for Ultra-Clear Selfies",
        paragraphs: [
          "The 50MP front camera ensures sharp, vibrant selfies with exceptional detail. Whether you're attending video calls, live streaming, or capturing Instagram-ready portraits, this high-resolution selfie camera delivers impressive clarity. With support for underwater photography and videography, your creative possibilities expand beyond standard smartphone cameras.",
        ],
      },
      {
        heading: "Massive 7000mAh Battery with 80W Fast Charging",
        paragraphs: [
          "Battery life is one of the biggest highlights of the OPPO A6s Pro. The 7000mAh large battery easily powers you through a full day—or even more—of heavy usage including gaming, streaming, browsing, and video recording. With 80W fast charging, the device recharges quickly, reducing downtime and keeping you connected. This makes it one of the best long-battery smartphones with fast charging support in its segment.",
        ],
      },
      {
        heading: "Dual Stereo Speakers with 300% Ultra Volume",
        paragraphs: [
          "Experience immersive sound with dual stereo speakers and 300% ultra volume enhancement. Whether you’re watching movies, playing games, or listening to music, the loud and clear audio output enhances your entertainment experience.",
        ],
      },
      {
        heading: "Premium Design with Durable Build",
        paragraphs: [
          "The OPPO A6s Pro features a unibody metal-textured frame with a slim 7.99mm thickness and lightweight 190g design, offering both elegance and comfort in hand. With an impressive IP69K rating, this smartphone provides superior dust and water resistance, making it highly durable for everyday and outdoor use. The in-display fingerprint sensor adds a modern and secure unlocking experience.",
        ],
      },
      {
        heading: "Buying the OPPO A6s Pro (8/256GB) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
