/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/oppo-a6k-6gb-128gb.jpeg";
import img2 from "@/images/products/oppo-a6k-6gb-128gb/02-oppo-a6k-1.jpeg";

export const oppoA6k6gb128gb: ProductDetail = {
  breadcrumb: [
    { label: "Phones", slug: "phone" },
    { label: "OPPO", slug: "oppo" },
  ],
  gallery: [img1, img2],
  inStock: true,

  highlights: [
    "Display: 6.75 inches, 120Hz Ultra Bright Display",
    "Processor: Qualcomm Snapdragon 685 Mobile Platform",
    "Camera: 50MP + 5MP",
    "Features: Side fingerprint sensor, Facial Recognition",
  ],

  colors: [
    { name: "Crystal Violet", hex: "#565872", image: img2 },
    { name: "Crystal Blue", hex: "#C2CBE0", image: img1 },
  ],

  emi: { months: 12, perMonth: 2167 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["OPPO"] },
        { label: "Model Name", value: ["A6k"] },
      ],
    },
    {
      title: "Display",
      rows: [
        { label: "Size", value: ["6.75 inches"] },
        { label: "Resolution", value: ["HD+ 1570 × 720 Pixels"] },
        { label: "Refresh Rate", value: ["Maximum: 120Hz"] },
        { label: "Brightness", value: ["Normal brightness: 800nits (Typical)", "HBM: 1125nits (Typical)"] },
        { label: "Features", value: ["Screen Ratio: 90.6%", "Touch Sampling Rate: Maximum: 240Hz", "Default: 120Hz", "Color Gamut: Vivid mode: 85% DCI-P3", "Natural mode: 100% sRGB", "Color Depth: 16.7 million colors (8-bit)", "Pixel Density: 256 PPI", "Panel: LCD"] },
      ],
    },
    {
      title: "Processor",
      rows: [
        { label: "Chipset", value: ["Qualcomm Snapdragon 685 Mobile Platform"] },
        { label: "CPU Type", value: ["8 cores"] },
        { label: "GPU", value: ["Adreno 610@1260MHz"] },
      ],
    },
    {
      title: "Memory",
      rows: [
        { label: "RAM", value: ["6GB"] },
        { label: "ROM", value: ["128GB"] },
      ],
    },
    {
      title: "Rear Camera",
      rows: [
        { label: "Resolution", value: ["50MP"] },
        { label: "Features", value: ["Wide angle: 50MP", "f/1.8", "FOV 76°", "5P lens", "AF supported", "Monochrome: QVGA", "f/3.0", "FOV 40°", "1P lens", "Photo, Video, Portrait, Night, Panorama, TIME-LAPSE, STICKER, HI-RES, Google Lens, PRO"] },
        { label: "Video Recording", value: ["1080P video: 30fps", "720P video: 30fps", "1080P TIME-LAPSE: 30fps", "Supports video zoom shooting: up to 10x digital zoom"] },
      ],
    },
    {
      title: "Front Camera",
      rows: [
        { label: "Resolution", value: ["5MP"] },
        { label: "Features", value: ["f/2.2", "FOV 77°", "3P lens", "Photo, Video, Portrait, Night, Panorama, TIME-LAPSE, STICKER, Retouch, Screen Fill Light, HI-RES"] },
        { label: "Video Recording", value: ["1080P video: 30fps", "720P video: 30fps", "1080P TIME-LAPSE: 30fps"] },
      ],
    },
    {
      title: "Network & AMP; Connectivity",
      rows: [
        { label: "Network", value: ["GSM: 850/900/1800MHz", "WCDMA: Band 1/5/8", "LTE FDD: Band 1/3/5/7/8/20/28", "LTE TDD: Band 38/40/41"] },
        { label: "Wi-Fi", value: ["Wi-Fi 5 (802.11ac) supported", "802.11a/b/g/n supported", "Wi-Fi Display supported", "WLAN Tethering supported"] },
        { label: "Bluetooth", value: ["Bluetooth 5.0, Low Energy"] },
        { label: "GPS", value: ["GPS, GLONASS, BDS, Galileo, QZSS, A-GNSS assisted positioning, WLAN positioning, Cellular network positioning"] },
        { label: "USB", value: ["USB Type-C"] },
        { label: "Audio Jack", value: ["3.5mm jack"] },
      ],
    },
    {
      title: "OS",
      rows: [
        { label: "Operating System", value: ["ColorOS 15.0"] },
      ],
    },
    {
      title: "Features",
      rows: [
        { label: "Fingerprint", value: ["Side fingerprint sensor"] },
        { label: "Sensors", value: ["Proximity sensor", "Ambient light sensor", "E-compass", "Accelerometer", "Facial Recognition"] },
      ],
    },
    {
      title: "Battery",
      rows: [
        { label: "Type", value: ["6500mAh/25.22Wh (Typical)", "6335mAh/24.58Wh (Rated)"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["Height: about 166.61mm", "Width: about 78.51mm", "Thickness: about 8.61mm"] },
        { label: "Weight", value: ["About 210g"] },
        { label: "Colors", value: ["Crystal Violet, Crystal Blue"] },
      ],
    },
  ],

  description: {
    title: "OPPO A6k (6/128GB)",
    blocks: [
      {
        paragraphs: [
          "The OPPO A6k (6/128GB) is a stylish and performance-focused smartphone designed for users who want a smooth display, long-lasting battery life, reliable camera performance, and efficient multitasking at an affordable price. Powered by the Qualcomm Snapdragon 685 processor and featuring a large 120Hz display, the OPPO A6k delivers a balanced smartphone experience for gaming, entertainment, social media, and daily productivity. With a massive 6500mAh battery, ColorOS 15, and modern connectivity features, this OPPO smartphone is an excellent choice for everyday users in Bangladesh.",
        ],
      },
      {
        heading: "Large 120Hz Display for Smooth Viewing",
        paragraphs: [
          "The OPPO A6k comes with a large 6.75-inch HD+ LCD display that provides an immersive experience for watching videos, browsing social media, gaming, and online streaming. The display supports a maximum 120Hz refresh rate, delivering smoother scrolling, responsive touch interactions, and better gaming performance. With up to 1125 nits HBM brightness, the screen remains visible even under bright outdoor lighting conditions. The display also supports a wide color range with 85% DCI-P3 in Vivid mode and 100% sRGB in Natural mode, offering vibrant and accurate visuals. The 240Hz touch sampling rate further improves responsiveness, making the smartphone feel fast and fluid during everyday use.",
        ],
      },
      {
        heading: "Snapdragon 685 Processor for Reliable Performance",
        paragraphs: [
          "The smartphone is powered by the Qualcomm Snapdragon 685 Mobile Platform, an efficient octa-core processor designed for smooth multitasking and stable daily performance. Combined with the Adreno 610 GPU, the OPPO A6k handles apps, social media, online streaming, and casual gaming with ease. Whether you are switching between multiple apps, browsing the web, or playing mobile games, the device offers a reliable and responsive user experience.",
        ],
      },
      {
        heading: "6GB RAM and 128GB Storage for Everyday Convenience",
        paragraphs: [
          "The OPPO A6k features 6GB RAM for smooth multitasking and efficient app performance. Users can comfortably run multiple applications, browse social media, and stream content without frequent slowdowns. With 128GB internal storage, the device provides enough space for photos, videos, games, documents, and apps, making it suitable for daily entertainment and productivity needs.",
        ],
      },
      {
        heading: "50MP AI Camera for Clear Photography",
        paragraphs: [
          "The OPPO A6k is equipped with a 50MP AI rear camera that captures detailed and vibrant photos in different lighting conditions. The camera supports autofocus and multiple photography modes including Portrait, Night, Panorama, Time-Lapse, Pro Mode, Sticker, HI-RES, and Google Lens. Users can record videos in 1080P at 30fps and enjoy up to 10x digital zoom for flexible shooting options. On the front, the smartphone features a 5MP selfie camera with support for Portrait, Retouch, Night mode, and Screen Fill Light, helping users capture social-media-ready selfies and clear video calls.",
        ],
      },
      {
        heading: "Massive 6500mAh Battery for All-Day Power",
        paragraphs: [
          "One of the biggest highlights of the OPPO A6k is its massive 6500mAh battery, designed to provide long-lasting backup for gaming, video streaming, browsing, and communication throughout the day. The large battery capacity makes the smartphone ideal for heavy users who need reliable performance without frequent charging interruptions.",
        ],
      },
      {
        heading: "Modern Connectivity and Smart Features",
        paragraphs: [
          "The OPPO A6k supports a wide range of modern connectivity options including 4G LTE, Wi-Fi 5, Bluetooth 5.0, GPS, USB Type-C, and a convenient 3.5mm headphone jack. The device runs on the latest ColorOS 15.0, delivering a smooth and user-friendly software experience. Security features such as the side-mounted fingerprint sensor and facial recognition provide quick and secure access to the smartphone. Additional sensors including the accelerometer, ambient light sensor, proximity sensor, and E-compass improve usability for navigation, gaming, and daily smartphone tasks.",
        ],
      },
      {
        heading: "Sleek Design with Comfortable Handling",
        paragraphs: [
          "The OPPO A6k features a modern slim design despite its large battery capacity. Measuring approximately 8.61mm thin and weighing around 210g, the device offers a comfortable grip for long-term use. Its stylish appearance and large screen-to-body ratio make it suitable for both entertainment and professional use.",
        ],
      },
      {
        heading: "Buying the OPPO A6k (6/128GB) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
