/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/oppo-a6-8gb-256gb.jpeg";
import img2 from "@/images/brands/oppo-a6.jpeg";
import img3 from "@/images/products/oppo-a6/02-oppo-a6-blue-2547.jpeg";
import img4 from "@/images/products/oppo-a6/03-oppo-a6-gold-2178.jpeg";
import img5 from "@/images/products/oppo-a6/05-oppo-a6-gold-1602.jpeg";

export const oppoA68gb256gb: ProductDetail = {
  breadcrumb: [
    { label: "Phones", slug: "phone" },
    { label: "OPPO", slug: "oppo" },
  ],
  gallery: [img1, img2, img3, img4, img5],
  inStock: true,

  highlights: [
    "Display: 6.75 inches, IPS Display",
    "Processor: Qualcomm Snapdragon® 685 Mobile Platform",
    "Camera: 50MP + 2MP + 8MP",
    "Features: Side-mounted fingerprint sensor",
  ],

  colors: [
    { name: "Sapphire Blue", hex: "#3B6295", image: img2 },
    { name: "Aurora Gold", hex: "#DDC8B6", image: img1 },
  ],

  emi: { months: 12, perMonth: 3083 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["OPPO"] },
        { label: "Model Name", value: ["A6"] },
      ],
    },
    {
      title: "Display",
      rows: [
        { label: "Size", value: ["6.75 inches"] },
        { label: "Type", value: ["LCD"] },
        { label: "Resolution", value: ["HD+ 1570 × 720 Pixels"] },
        { label: "Refresh Rate", value: ["Maximum: 120Hz"] },
        { label: "Brightness", value: ["Normal brightness: 800nits (Typical)", "HBM: 1125nits (Typical)"] },
        { label: "Features", value: ["Screen Ratio: 90.6%", "Touch Sampling Rate:", "Maximum: 240Hz", "Default: 120Hz", "Colour Gamut", "Vivid mode: 85% DCI-P3", "Natural mode: 100% sRGB", "Colour Depth: 16.7 million colours (8-bit)", "Pixel Density: 256 PPI"] },
      ],
    },
    {
      title: "Processor",
      rows: [
        { label: "Chipset", value: ["Qualcomm Snapdragon®685 Mobile Platform"] },
        { label: "CPU Speed", value: ["8 cores"] },
        { label: "GPU", value: ["Adreno™ 610@1.26GHz"] },
      ],
    },
    {
      title: "Memory",
      rows: [
        { label: "RAM", value: ["8GB"] },
        { label: "ROM", value: ["256GB"] },
      ],
    },
    {
      title: "Rear Camera",
      rows: [
        { label: "Resolution", value: ["Wide angle: 50MP", "f/1.8", "FOV 76°", "5P lens", "AF supported", "Monochrome: 2MP", "f/2.4", "FOV 89°", "3P lens"] },
        { label: "Features", value: ["Photo, Video, Portrait, Night, PANO, SLO-MO, Dual-view video, TIME-LAPSE, STICKER, HI-RES, Google Lens, Underwater, PRO"] },
        { label: "Video Recording", value: ["1080P video: 30fps", "720P video: 30fps", "720P SLO-MO video: 120fps, except 4G RAM", "1080P TIME-LAPSE: 30fps", "Supports Dual-view video shooting, except 4G RAM", "Supports video zoom shooting: up to 10x digital zoom"] },
      ],
    },
    {
      title: "Front Camera",
      rows: [
        { label: "Resolution", value: ["8MP", "f/2.0", "FOV 80°", "4P lens"] },
        { label: "Features", value: ["Photo, Video, Portrait, Night, PANO, Dual-view video, TIME-LAPSE, STICKER, Retouch, Screen Fill Light, HI-RES"] },
        { label: "Video Recording", value: ["1080P video: 30fps", "720P video: 30fps", "1080P TIME-LAPSE: 30fps", "Supports Dual-view video shooting, except 4G RAM"] },
      ],
    },
    {
      title: "Network & AMP; Connectivity",
      rows: [
        { label: "SIM", value: ["Nano-SIM card, Nano-USIM card"] },
        { label: "Wi-Fi", value: ["Wi-Fi 5 (802.11ac) supported", "802.11a/b/g/n supported", "Wi-Fi Display supported", "WLAN Tethering supported"] },
        { label: "Bluetooth", value: ["Bluetooth® 5.0, Low Energy"] },
        { label: "GPS", value: ["Beidou, GPS, GLONASS, Galileo, QZSS", "Supports A-GPS assisted positioning, WLAN positioning, Cellular network positioning, A-GNSS assisted positioning"] },
        { label: "USB", value: ["Type-C"] },
        { label: "OTG", value: ["Supported"] },
        { label: "Audio Jack", value: ["Type-C"] },
      ],
    },
    {
      title: "OS",
      rows: [
        { label: "Operating System", value: ["ColorOS 15.0"] },
      ],
    },
    {
      title: "Features",
      rows: [
        { label: "Fingerprint", value: ["Supported"] },
        { label: "Sensors", value: ["Proximity sensor", "Ambient light sensor", "E-compass", "Accelerometer", "Side fingerprint sensor"] },
        { label: "IP Rating", value: ["IP69"] },
      ],
    },
    {
      title: "Battery",
      rows: [
        { label: "Type", value: ["7000mAh/27.44Wh (Typical)", "6830mAh/26.78Wh (Rated)"] },
        { label: "Fast Charging", value: ["Supports (Max): 45W SUPERVOOCTM", "Compatible with: 33W and below SUPERVOOCTM, 33W PPS, 15W VOOCTM, 13.5W PD, 13.5W QC"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["Height: about 166.61mm", "Width: about 78.51mm", "Thickness: about 8.61mm"] },
        { label: "Weight", value: ["about 215g"] },
        { label: "Colors", value: ["Sapphire Blue | Aurora Gold"] },
      ],
    },
  ],

  description: {
    title: "OPPO A6 (8/256GB)",
    blocks: [
      {
        paragraphs: [
          "The OPPO A6 (8/256GB) brings a refreshing balance of performance, battery life, and storage for users who want a smooth and reliable smartphone experience. With a large immersive display, Snapdragon power, fast charging, and upgraded 256GB storage, this device is designed for everyday use, entertainment, and effortless multitasking.",
        ],
      },
      {
        heading: "Key Features of OPPO A6",
        paragraphs: [
          "The OPPO A6 features a vivid 6.75-inch LCD panel with HD+ 1570 × 720 resolution, offering bright visuals and excellent clarity. Its 120Hz refresh rate ensures smooth animations and fluid scrolling, while the 240Hz touch sampling rate keeps your interactions fast and responsive. Even under sunlight, the phone remains visible with up to 1125 nits of high-brightness mode. With a 90.6% screen ratio and accurate colours thanks to 85% DCI-P3 and 100% sRGB support, this display feels truly immersive.",
          "Size: 6.75 inches",
          "Type: LCD",
          "Resolution: HD+ 1570 × 720 pixels",
          "Refresh Rate: Up to 120Hz",
          "Brightness: 800 nits (typical), 1125 nits HBM",
          "Screen Ratio: 90.6%",
          "Touch Sampling Rate: 240Hz (max), 120Hz (default)",
          "Colour Gamut: 85% DCI-P3 (Vivid), 100% sRGB (Natural)",
          "Colour Depth: 16.7 million colours (8-bit)",
          "Pixel Density: 256 PPI",
          "Chipset: Qualcomm Snapdragon® 685",
          "CPU: 8-core",
          "GPU: Adreno™ 610 @ 1.26GHz",
          "RAM: 8GB",
          "ROM: 256GB",
          "Main Camera: 50MP, f/1.8, FOV 76°, 5P lens, AF",
          "Resolution: 8MP, f/2.0, FOV 80°, 4P lens",
          "SIM: Nano-SIM, Nano-USIM",
          "Wi-Fi: Wi-Fi 5 (802.11ac), 802.11a/b/g/n, Wi-Fi Display, WLAN tethering",
          "Bluetooth: Bluetooth® 5.0 (Low Energy)",
          "GPS: GPS, GLONASS, Beidou, Galileo, QZSS",
          "Positioning Support: A-GPS, WLAN, Cellular network, A-GNSS",
          "USB: Type-C",
          "OTG: Supported",
          "Audio: Type-C audio output",
        ],
      },
      {
        heading: "Snapdragon® 685 Performance with 8GB RAM",
        paragraphs: [
          "Powered by the Qualcomm Snapdragon® 685 chip and an 8-core CPU, the OPPO A6 handles multitasking with ease. The Adreno™ 610 GPU ensures smooth graphics whether you’re browsing, streaming, or gaming. Paired with 8GB RAM and a large 256GB storage, you can store more photos, apps, and media without worrying about space. It’s a fast, reliable companion for long-term everyday use.",
        ],
      },
      {
        heading: "Camera for Crisp, Natural Photos",
        paragraphs: [
          "The OPPO A6 (8/256GB) comes with a 50MP f/1.8 main camera that delivers sharp and vibrant shots in all lighting conditions, supported by a 2MP monochrome lens for depth and detail. You can explore creative modes like Night, Portrait, PRO, Underwater, Google Lens, TIME-LAPSE, and Dual-view video. Video recording goes up to 1080p at 30fps with support for 10x digital zoom. The front 8MP camera captures natural selfies with features like Retouch, Night mode, Screen Fill Light, and Dual-view recording.",
        ],
      },
      {
        heading: "Stable Connectivity and Smooth Navigation",
        paragraphs: [
          "The device supports dual Nano-SIM with reliable network performance. Wi-Fi 5 ensures fast internet speeds, and Bluetooth® 5.0 lets you connect wireless accessories with stability. With GPS systems like GLONASS, Beidou, Galileo, and QZSS, your location stays accurate whether navigating the city or traveling. USB Type-C and OTG support add convenience for file transfers and accessories.",
        ],
      },
      {
        heading: "Smart, Fluid Experience",
        paragraphs: [
          "Running on ColorOS 15.0, the OPPO A6 brings a clean and user-friendly UI with improved animations, enhanced privacy tools, and handy smart features. The side fingerprint sensor ensures fast and secure unlocking, supported by essential sensors like an accelerometer, proximity sensor, E-compass, and ambient light sensor.",
        ],
      },
      {
        heading: "Battery with SUPERVOOC Fast Charging",
        paragraphs: [
          "Battery life is one of the strongest highlights of the OPPO A6. Its huge 7000mAh battery keeps you going through work, travel, videos, and gaming without stress. When you need a quick recharge, the 45W SUPERVOOC technology powers up the device fast, and it remains compatible with various charging standards, including 33W PPS and PD. Despite its large battery, the phone maintains a slim 8.61mm profile and a balanced 215g weight.",
        ],
      },
      {
        heading: "Strong Durability with IP69 Rating",
        paragraphs: [
          "The OPPO A6 is built tough with an IP69 rating, ensuring high resistance to dust and strong water pressure. Whether you’re outdoors or on the go, this durability adds extra peace of mind.",
        ],
      },
      {
        heading: "Buying the OPPO A6 (8/256GB) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
