/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/pitaka-ultraslim-case-for-iphone-17-pro-max-sunset.jpeg";
import img2 from "@/images/products/pitaka-ultraslim-case-for-iphone-17-pro-max-sunset/02-pitaka-ultra-slim-case-for-iphone-17-pro-max-sunet515.jpeg";
import img3 from "@/images/products/pitaka-ultraslim-case-for-iphone-17-pro-max-sunset/03-pitaka-ultra-slim-case-for-iphone-17-pro-sunet-1141.jpeg";
import img4 from "@/images/products/pitaka-ultraslim-case-for-iphone-17-pro-max-sunset/04-pitaka-ultra-slim-case-for-iphone-17-pro-max-sunet-1125.jpeg";

export const pitakaUltraslimCaseForIphone17ProMaxSunset: ProductDetail = {
  breadcrumb: [
    { label: "Cases & Protectors", slug: "cases-screen-protectors" },
    { label: "Apple", slug: "apple-cases-accessories" },
    { label: "iPhone 17 Pro Max", slug: "iphone-17-pro-max-cases" },
  ],
  gallery: [img1, img2, img3, img4],
  inStock: true,

  highlights: [
    "Crafted from aerospace-grade aramid fiber for strength and elegance",
    "Ultra-thin and feather-light for a barely-there feel",
    "Minimalist, timeless design that elevates your iPhone",
    "100% MagSafe compatible and wireless charging ready",
  ],

  colors: [
    { name: "Sunset", hex: "#A3806C", image: img1 },
  ],

  emi: { months: 3, perMonth: 2833 },

  specs: [
    {
      title: "Product Specifications",
      rows: [
        { label: "Compatible Devices", value: ["iPhone 17 Pro Max"] },
        { label: "Material", value: ["Aerospace-grade Aramid fiber", "Fusion Weaving"] },
        { label: "Color", value: ["Sunset"] },
        { label: "Special Feature", value: ["Crafted from aerospace-grade aramid fiber for strength and elegance", "Ultra-thin and feather-light for a barely-there feel", "Minimalist, timeless design that elevates your iPhone", "100% MagSafe compatible and wireless charging ready", "Scratch-resistant and durable for long-lasting use"] },
        { label: "Dimensions", value: ["Thickness: 1.08(±0.1mm)"] },
        { label: "Weight", value: ["22.54(±1g)"] },
      ],
    },
  ],

  description: {
    title: "PITAKA Ultra-Slim Sunset Case for iPhone 17 Pro Max",
    blocks: [
      {
        paragraphs: [
          "Give your iPhone 17 Pro Max the protection it deserves—with a design that turns heads. The PITAKA Ultra-Slim Sunset Case for iPhone 17 Pro Max combines feather-light engineering with an eye-catching gradient finish inspired by the warmth and calm of sunset skies. It’s more than just a case—it’s a style statement for those who love premium design and flawless functionality. The Sunset colorway, achieved through PITAKA’s exclusive Fusion Weaving technique, creates a soft yet dynamic gradient blend—designed to reflect your personality and elevate the look of your iPhone 17 Pro Max.",
        ],
      },
      {
        heading: "Key Features of the PITAKA Ultra-Slim Sunset Case",
        paragraphs: [
          "The Sunset Case is more than just beautiful. It’s engineered for performance. With 100% MagSafe compatibility, you can snap on wireless chargers and magnetic accessories without removing the case. The ultra-thin profile supports wireless charging and maintains full access to all buttons, ports, and cameras. The minimalist design ensures your iPhone remains the star of the show, while the precision-cut fit provides a seamless, secure grip that’s easy to hold and hard to put down. Designed to match the dimensions of the iPhone 17 Pro Max perfectly, this case wraps around your device like a second skin. It offers edge-to-edge coverage without interfering with screen protectors or the sleek profile of your phone. Whether you're using it for work, travel, or daily life, the PITAKA Sunset Case adds style and protection—without compromise.",
        ],
      },
      {
        heading: "Buying the PITAKA Ultra-Slim Sunset Case for iPhone 17 Pro Max from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
