/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/realme-c85-pro-8gb-128gb.jpeg";
import img2 from "@/images/products/realme-c85-pro-8gb-128gb/02-realme-c85.jpg-4212.jpeg";
import img3 from "@/images/products/realme-c85-pro-8gb-128gb/03-realme-c85.jpg-5548.jpeg";
import img4 from "@/images/products/realme-c85-pro-8gb-128gb/04-realme-c85.jpg-6764.jpeg";
import img5 from "@/images/products/realme-c85-pro-8gb-128gb/05-realme-c85.jpg-7763.jpeg";
import img6 from "@/images/products/realme-c85-pro-8gb-128gb/06-realme-c85979.jpeg";
import img7 from "@/images/products/realme-c85-pro-8gb-128gb/07-realme-c85.jpg-124.jpeg";
import img8 from "@/images/products/realme-c85-pro-8gb-128gb/08-realme-c85.jpg-2512.jpeg";
import img9 from "@/images/products/realme-c85-pro-8gb-128gb/09-realme-c85.jpg-3253.jpeg";

export const realmeC85Pro8gb128gb: ProductDetail = {
  breadcrumb: [
    { label: "Phones", slug: "phone" },
    { label: "realme", slug: "realme-mobile-phone" },
  ],
  gallery: [img1, img2, img3, img4, img5, img6, img7, img8, img9],
  inStock: true,

  highlights: [
    "Display: 6.8\" AMOLED, 120Hz",
    "Processor: Snapdragon 685 Mobile Platform",
    "Camera: 50MP AI Camera on Rear, 8MP on Front",
    "Features: IP69 Pro, Military-Grade, 45W Fast Charging",
  ],

  colors: [
    { name: "Peacock Green", hex: "#40B8B9", image: img2 },
    { name: "Purple", hex: "#800080", image: img6 },
  ],

  emi: { months: 6, perMonth: 4667 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["realme"] },
        { label: "Model Name", value: ["C85 Pro"] },
      ],
    },
    {
      title: "Display",
      rows: [
        { label: "Size", value: ["6.8 inches (17.19cm)"] },
        { label: "Type", value: ["AMOLED"] },
        { label: "Resolution", value: ["2344 × 1080"] },
        { label: "Refresh Rate", value: ["Refresh Rate: 120Hz (60/120Hz)", "Touch Sampling Rate: 180Hz, Default 120Hz"] },
        { label: "Brightness", value: ["Local Peak Brightness: 4000nit", "High Brightness Mode: 1200nit", "Normal Brightness: 600nit (The settings bar can increase the brightness to 800nit）"] },
        { label: "Features", value: ["Screen-to-body Ratio: 92.3%", "Colour Depth: 16.7 million colors(8-bit)", "Pixel Density: 381 PPI"] },
      ],
    },
    {
      title: "Processor",
      rows: [
        { label: "Chipset", value: ["Snapdragon 685 Mobile Platform"] },
      ],
    },
    {
      title: "Memory",
      rows: [
        { label: "RAM", value: ["8GB"] },
        { label: "ROM", value: ["128GB"] },
      ],
    },
    {
      title: "Rear Camera",
      rows: [
        { label: "Resolution", value: ["50MP AI Camera"] },
      ],
    },
    {
      title: "Front Camera",
      rows: [
        { label: "Resolution", value: ["8MP"] },
      ],
    },
    {
      title: "Network & AMP; Connectivity",
      rows: [
        { label: "SIM", value: ["Nano-SIM + Nano-SIM"] },
        { label: "Network", value: ["GSM / HSPA / LTE"] },
        { label: "Wi-Fi", value: ["Wi-Fi 5 (802.11ac) Supported", "802.11a/b/g/n Supported", "1 × 1 SISO Supported"] },
        { label: "Bluetooth", value: ["Bluetooth® 5.0 Supported"] },
        { label: "GPS", value: ["Single band: Beidou, GPS, GLONASS, Galileo, QZSS"] },
        { label: "USB", value: ["USB Type-C 2.0"] },
        { label: "OTG", value: ["Yes"] },
      ],
    },
    {
      title: "OS",
      rows: [
        { label: "Operating System", value: ["reame UI"] },
      ],
    },
    {
      title: "Features",
      rows: [
        { label: "Sensors", value: ["Fingerprint, accelerometer, proximity, compass"] },
        { label: "IP Rating", value: ["IP69 Pro Dust & Water Resistance"] },
        { label: "Other Features", value: ["Military-Grade Shock Resistance", "AI Edit Genie", "400% UltraBoom", "AI Outdoor Mode"] },
      ],
    },
    {
      title: "Battery",
      rows: [
        { label: "Type", value: ["7000mAh"] },
        { label: "Fast Charging", value: ["45W"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["164.4 77.99 8.09(mm)"] },
        { label: "Weight", value: ["205g"] },
        { label: "Colors", value: ["Parrot purple, Peacock green"] },
      ],
    },
  ],

  description: {
    title: "realme C85 Pro (8/128GB)",
    blocks: [
      {
        paragraphs: [
          "The realme C85 Pro (8/128GB) brings together power, performance, and premium style to redefine what you expect from a mid-range smartphone. Designed for users who value speed, camera quality, and modern aesthetics, this phone offers an exceptional experience for gaming, entertainment, and everyday multitasking. With its stunning display, powerful processor, and long-lasting battery, the realme C85 Pro (8/128GB) ensures smooth performance throughout your day. Whether you’re capturing photos, streaming your favorite shows, or browsing the web, this smartphone delivers excellence in every aspect.",
        ],
      },
      {
        heading: "realme C85 Pro Specifications",
        paragraphs: [
          "realme C85 Pro (8/128GB) is a stylish and powerful smartphone designed for users who want performance and elegance in one device. It features a stunning high-resolution display, a fast processor for smooth multitasking, and a long-lasting battery with fast charging support. The AI-enhanced camera system captures stunning photos and selfies in any lighting, while its sleek, premium design ensures a comfortable grip. With advanced security features, efficient connectivity, and an intuitive realme UI, the realme C85 Pro delivers a seamless experience for gaming, streaming, and everyday use. Perfect for those seeking power and style at an affordable price.",
          "Size: 6.8 inches (17.19 cm)",
          "Type: AMOLED",
          "Resolution: 2344 × 1080 pixels",
          "Refresh Rate: 120Hz",
          "Brightness: 1200 nits (HBM), 4000 nits (APL)",
          "Screen-to-Body Ratio: 92.3%",
          "Chipset: Snapdragon 685 Mobile Platform",
          "RAM: 8GB",
          "ROM (Storage): 128GB",
          "Rear Camera: 50MP AI Camera",
          "Front Camera: 8MP",
          "OS: realme UI",
          "Durability & Features",
          "IP Rating: IP69 Pro Dust & Water Resistance",
          "Other Features: Military-Grade Shock Resistance, AI Edit Genie, 400% UltraBoom, AI Outdoor Mode",
        ],
      },
      {
        heading: "Brilliant Display for Immersive Viewing",
        paragraphs: [
          "The realme C85 Pro features a large, vibrant display that enhances your viewing experience with crisp details and lifelike colors. With its high-resolution panel and ultra-smooth refresh rate, every scroll, swipe, and animation feels incredibly fluid. Whether you’re watching movies, playing games, or scrolling through social media, the realme C85 Pro’s display brings visuals to life with impressive clarity and brightness. Its minimal bezels and sleek design make it perfect for users who love an immersive viewing experience.",
        ],
      },
      {
        heading: "Powerful Performance with an Advanced Processor",
        paragraphs: [
          "Under the hood, the realme C85 Pro packs a powerful processor designed to handle demanding tasks with ease. From gaming and streaming to multitasking across multiple apps, this device delivers smooth, lag-free performance. The advanced chipset ensures efficient power management, keeping your phone cool even during extended use. Combined with generous RAM and ample storage options, the realme C85 Pro gives you the freedom to store your photos, videos, and apps while maintaining lightning-fast performance.",
        ],
      },
      {
        heading: "AI-Enhanced Camera System for Stunning Photography",
        paragraphs: [
          "Capture every moment in vivid detail with the realme C85 Pro’s advanced AI-powered camera system. The high-resolution main camera delivers sharp, bright, and colorful images even in low light. With AI scene recognition and intelligent image processing, your photos always look professional and well-balanced. The front camera is equally impressive, designed to deliver beautiful selfies and clear video calls. Whether it’s landscapes, portraits, or night shots, the realme C85 Pro’s camera ensures that every click turns into a masterpiece.",
        ],
      },
      {
        heading: "Sleek and Stylish Design That Stands Out",
        paragraphs: [
          "The realme C85 Pro combines modern design with premium craftsmanship. Its slim profile, smooth curved edges, and elegant finish make it comfortable to hold and visually appealing. Available in stylish color options, this smartphone is designed to make a statement wherever you go. The attention to detail in both aesthetics and build quality highlights realme’s commitment to creating devices that are not only powerful but also fashionable.",
        ],
      },
      {
        heading: "Enhanced Connectivity and Smooth User Experience",
        paragraphs: [
          "The realme C85 Pro supports a range of modern connectivity options, including dual SIM, Bluetooth, and fast Wi-Fi, ensuring seamless communication and data transfer. The intuitive realme UI enhances the Android experience with clean visuals and smart features, making navigation effortless. From improved app management to smooth gesture controls, every aspect of the interface is optimized for comfort and convenience.",
        ],
      },
      {
        heading: "Secure and Smart Features for Everyday Use",
        paragraphs: [
          "Your privacy and security are always a priority with the realme C85 Pro. It includes advanced security features such as face unlock and a fingerprint sensor for quick, secure access. The phone’s system-level privacy controls also give you greater command over your personal data, ensuring that your information stays protected at all times. realme has also integrated intelligent optimization tools to enhance performance and extend battery life for long-term efficiency.",
        ],
      },
      {
        heading: "Optimized Gaming and Entertainment Experience",
        paragraphs: [
          "For gaming enthusiasts, the realme C85 Pro offers a powerful combination of hardware and software enhancements. The responsive display, fast processor, and intelligent cooling system ensure smooth, lag-free gameplay. Whether it’s high-graphics gaming or watching HD content, the device handles it effortlessly. Paired with immersive audio quality, the C85 Pro transforms your entertainment experience into something extraordinary, keeping you engaged wherever you are.",
        ],
      },
      {
        heading: "All-Day Battery Life with Fast Charging Support",
        paragraphs: [
          "Stay connected all day with the realme C85 Pro’s high-capacity battery, built to keep up with your busy lifestyle. It offers hours of continuous usage, whether you’re gaming, streaming, or browsing. And when it’s time to recharge, the fast-charging technology gets you back to full power quickly—no long waiting times. With optimized battery management, the realme C85 Pro ensures efficient energy use, giving you dependable performance from morning to night.",
        ],
      },
      {
        heading: "Buying the realme C85 Pro (8/128GB) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
