/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/realme-c100i-4gb-128gb.jpeg";
import img2 from "@/images/products/realme-c100i-4gb-128gb/02-realme-c100i-purple.jpeg";

export const realmeC100i4gb128gb: ProductDetail = {
  breadcrumb: [
    { label: "Phones", slug: "phone" },
    { label: "realme", slug: "realme-mobile-phone" },
  ],
  gallery: [img1, img2],
  inStock: true,

  highlights: [
    "Display: 6.8 inches",
    "Processor: Unisoc T7250",
    "Camera: 8 MP + 5 MP",
    "Features: Accelerometer, Fingerprint Sensor, Gyro Sensor",
  ],

  colors: [
    { name: "Dusk Gray", hex: "#CED1D8", image: img1 },
    { name: "Dawn Purple", hex: "#F8E6FE", image: img2 },
  ],

  emi: { months: 6, perMonth: 3500 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["realme"] },
        { label: "Model Name", value: ["C100i"] },
      ],
    },
    {
      title: "Display",
      rows: [
        { label: "Size", value: ["6.8 inches"] },
        { label: "Type", value: ["LCD"] },
        { label: "Resolution", value: ["HD+ 720×1570 Pixels"] },
        { label: "Refresh Rate", value: ["Maximum 120Hz"] },
        { label: "Brightness", value: ["Normal brightness: 700 nits(Typical)", "HBM: 900 nits(Typical)"] },
      ],
    },
    {
      title: "Processor",
      rows: [
        { label: "Chipset", value: ["T7250"] },
        { label: "CPU Type", value: ["8-core"] },
        { label: "GPU", value: ["Arm® Mali™-G57@850MHz"] },
      ],
    },
    {
      title: "Memory",
      rows: [
        { label: "RAM", value: ["4GB"] },
        { label: "ROM", value: ["128GB"] },
      ],
    },
    {
      title: "Rear Camera",
      rows: [
        { label: "Resolution", value: ["8MP"] },
        { label: "Features", value: ["f/2.0", "FOV 78°", "4P lens", "AF Supported"] },
        { label: "Video Recording", value: ["1080P video: 30 fps(with Retouch on)", "720P video: 30 fps", "1080P TIME-LAPSE: 30 fps", "Supports Dual-view video shooting", "Supports video zoom shooting: up to 10× digital zoom"] },
      ],
    },
    {
      title: "Front Camera",
      rows: [
        { label: "Resolution", value: ["5MP"] },
        { label: "Features", value: ["f/2.2", "FOV 77°", "3P lens"] },
        { label: "Video Recording", value: ["720P video: 30 fps", "Supports Dual-view video shooting"] },
      ],
    },
    {
      title: "Network & AMP; Connectivity",
      rows: [
        { label: "SIM", value: ["Nano-SIM card", "Nano-USIM card"] },
        { label: "Wi-Fi", value: ["Yes"] },
        { label: "Bluetooth", value: ["5.2"] },
        { label: "GPS", value: ["Supported"] },
        { label: "NFC", value: ["Unsupported"] },
        { label: "USB", value: ["USB Type-C"] },
        { label: "OTG", value: ["Supported"] },
      ],
    },
    {
      title: "OS",
      rows: [
        { label: "Operating System", value: ["realme UI on Android 16"] },
      ],
    },
    {
      title: "Features",
      rows: [
        { label: "Fingerprint", value: ["Side-Mounted"] },
        { label: "Sensors", value: ["Proximity sensor", "Ambient light sensor", "E-compass", "Accelerometer", "Gyroscope", "Side fingerprint sensor"] },
      ],
    },
    {
      title: "Battery",
      rows: [
        { label: "Type", value: ["7000mAh(Typical)", "6820mAH(Rated)"] },
        { label: "Fast Charging", value: ["Supports(Max): 15W，5V 3A", "Compatible with:15W PD，13.5W QC，10W DCP"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["166.48mm*78.23mm*8.38mm"] },
        { label: "Weight", value: ["208 Grams"] },
        { label: "Colors", value: ["Dawn Purple, Dusk Gray"] },
      ],
    },
  ],

  description: {
    title: "Realme C100i (4/128GB)",
    blocks: [
      {
        paragraphs: [
          "Looking for a budget smartphone that offers more storage, long battery life, and smooth everyday performance. The Realme C100i (4/128GB) is designed for users who want extra space and reliability without spending too much. With its large display, efficient processor, and massive battery, this device is a perfect companion for daily use, entertainment, and staying connected.",
        ],
      },
      {
        heading: "Immersive 6.8-inch Display with 120Hz Smoothness",
        paragraphs: [
          "The Realme C100i comes with a large 6.8-inch LCD display that delivers a comfortable viewing experience for videos, browsing, and social media. The HD+ resolution (720×1570 pixels) ensures decent clarity for everyday use, while the 120Hz refresh rate provides smoother scrolling and a more responsive feel. With up to 900 nits brightness, the display remains visible even in bright outdoor conditions.",
        ],
      },
      {
        heading: "Reliable T7250 Processor for Daily Performance",
        paragraphs: [
          "Powered by the T7250 octa-core processor, the Realme C100i ensures stable and efficient performance for your everyday tasks. Whether you're switching between apps, watching videos, or playing light games, the device runs smoothly with the support of 4GB RAM. The Mali-G57 GPU further enhances graphics performance for a better visual experience.",
        ],
      },
      {
        heading: "Expanded 128GB Storage for More Freedom",
        paragraphs: [
          "With 128GB of internal storage, this variant gives you more room to store your photos, videos, apps, and documents. It’s an excellent choice for users who need extra space for media and files without constantly worrying about storage limits.",
        ],
      },
      {
        heading: "Simple Yet Functional Camera Setup",
        paragraphs: [
          "The 8MP rear camera is designed to capture everyday moments with clarity. It features autofocus support and an f/2.0 aperture for decent shots in good lighting conditions. You can record videos in 1080p at 30fps, and creative features like time-lapse, dual-view video, and up to 10x digital zoom add more versatility.",
        ],
      },
      {
        heading: "5MP Front Camera for Daily Selfies and Calls",
        paragraphs: [
          "The 5MP front camera is suitable for selfies and video calls, offering clear visuals for your everyday communication needs. It also supports dual-view video, allowing you to capture moments from both front and rear cameras.",
        ],
      },
      {
        heading: "Massive 7000mAh Battery for Long-Lasting Usage",
        paragraphs: [
          "One of the standout features of the Realme C100i is its huge 7000mAh battery. This ensures extended usage throughout the day, whether you're streaming, browsing, or using apps. With 15W fast charging support, you can quickly power up your device and get back to your activities.",
        ],
      },
      {
        heading: "Modern Software Experience with Android 16",
        paragraphs: [
          "Running on realme UI based on Android 16, the device offers a clean and user-friendly interface. It provides smooth navigation, updated features, and enhanced security, making your smartphone experience more enjoyable.",
        ],
      },
      {
        heading: "Connectivity and Practical Features",
        paragraphs: [
          "The Realme C100i supports dual Nano-SIM cards, making it convenient for users who manage personal and work numbers. It includes Wi-Fi, Bluetooth 5.2, GPS, and USB Type-C connectivity. OTG support allows you to connect external devices easily, adding more flexibility to your usage.",
        ],
      },
      {
        heading: "Secure Design with Modern Look",
        paragraphs: [
          "The side-mounted fingerprint sensor ensures quick and secure unlocking. The device also comes with essential sensors like accelerometer, gyroscope, and proximity sensor for improved usability. With a slim profile of 8.38mm and a weight of 208g, it offers a comfortable grip. The stylish Daen Purple and Dusk Gray color options give it a modern and attractive appearance.",
        ],
      },
      {
        heading: "Buying the realme C100i (4/128GB) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
