/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/realme-15-pro-5g.jpeg";
import img2 from "@/images/products/realme-15-pro-5g/02-realme-15-pro-5g-1.jpg-1802.jpeg";
import img3 from "@/images/products/realme-15-pro-5g/03-realme-15-pro-5g-1.jpg-2968.jpeg";
import img4 from "@/images/products/realme-15-pro-5g/04-realme-15-pro-5g-1.jpg-330.jpeg";
import img5 from "@/images/products/realme-15-pro-5g/05-realme-15-pro-5g-1.jpg-4218.jpeg";
import img6 from "@/images/products/realme-15-pro-5g/06-realme-15-pro-5g-1.jpg-5794.jpeg";

export const realme15Pro5g: ProductDetail = {
  breadcrumb: [
    { label: "Phones", slug: "phone" },
    { label: "realme", slug: "realme-mobile-phone" },
  ],
  gallery: [img1, img2, img3, img4, img5, img6],
  inStock: true,

  highlights: [
    "Display : 6.8 inches, 144Hz HyperGlow 4D Curve+",
    "Processor: Qualcomm Snapdragon R7 Gen 4",
    "Camera: 50 MP + 50 MP + 50 MP",
    "Features: In-display optical fingerprint sensor",
  ],

  colors: [
    { name: "Flowing Silver", hex: "#E1E5E9", image: img1 },
    { name: "Velvet Green", hex: "#30745A", image: img4 },
  ],

  emi: { months: 12, perMonth: 5000 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["realme"] },
        { label: "Model Name", value: ["15 Pro"] },
      ],
    },
    {
      title: "Display",
      rows: [
        { label: "Size", value: ["6.8 inches"] },
        { label: "Type", value: ["144Hz HyperGlow 4D Curve+ Display"] },
        { label: "Resolution", value: ["1280*2800"] },
        { label: "Refresh Rate", value: ["Up to 144Hz"] },
        { label: "Brightness", value: ["1800nit (HBM) / 6500nit Peak Brightness"] },
        { label: "Protection", value: ["Corning Gorilla Glass 7i"] },
        { label: "Features", value: ["Screen-to-body Ratio: 94%", "Contrast Ratio: 5,000,000:1", "Screen Colors: 1.07 billion (10bit)", "Dimming: 4608Hz PWM Dimming"] },
      ],
    },
    {
      title: "Processor",
      rows: [
        { label: "Chipset", value: ["Qualcomm SnapdragonR7 Gen 4"] },
        { label: "CPU Type", value: ["4nm Process, Octa-core, Up to 2.8GHz"] },
        { label: "GPU", value: ["AdrenoTM GPU@1150MHz"] },
      ],
    },
    {
      title: "Memory",
      rows: [
        { label: "RAM", value: ["12 GB"] },
        { label: "ROM", value: ["256 GB"] },
      ],
    },
    {
      title: "Rear Camera",
      rows: [
        { label: "Resolution", value: ["50 MP + 50 MP"] },
        { label: "Features", value: ["PHOTO, VIDEO, PORTRAIT, AI LANDSCAPE, NIGHT, HI-RES, PRO, PANO, STREET, FILM, SLO-MO, TIME-LAPSE, LONG EXPOSURE, DUAL-VIDEO, UNDERWATER, TEXT SCANNER, BREENO SCAN, STARRY MODE, TILT-SHIFT, Googlen Lens"] },
        { label: "Video Recording", value: ["4K 60fps, 4K 30fps, 1080 P 60fps, 1080 P 30fps, 720P, 60fps, 720P 30fps", "Video anti-shake support: 4K 60fp, 4K 30fps, 1080 P 60fps, 1080 P 30fps, 720P 60fps, 720P 30fps", "Support video zoom shooting", "Video slow motion support: 720P 240fps, 720P 120fps, 1080 P 120fps", "Cinematic mode support: 4K 30fps", "Time lapse photography support: 4K 30fps, 1080 P 30fps", "Support dual-video video shooting", "Supports HDR video shooting"] },
      ],
    },
    {
      title: "Front Camera",
      rows: [
        { label: "Resolution", value: ["50 MP"] },
        { label: "Features", value: ["PHOTO, VIDEO, PORTRAIT, NIGHT,HI-RES, PANO, TIM", "DUAL-VIDEO, UNDERWATER"] },
        { label: "Video Recording", value: ["Support: 4K 60fps, 4K 30fps, 1080 P 60fps, 1080 P 30 default, turn on beauty ), 720P 30fps", "Video eis support: 4K 60fps, 4K 30fps, 1080 P 60fps, 30fps (default, turn on beauty), 720P 30fps", "Support video zoom shooting", "Support dual-video video shooting"] },
      ],
    },
    {
      title: "Network & AMP; Connectivity",
      rows: [
        { label: "SIM", value: ["2 Nano SIM Card Slots"] },
        { label: "Network", value: ["2G, 3G, 4G, 5G"] },
        { label: "Wi-Fi", value: ["Support 2.4/5GHz Wi-Fi", "Support Wi-Fi 5 / Wi-Fi 6"] },
        { label: "Bluetooth", value: ["5.4"] },
        { label: "GPS", value: ["Single band: Beidou, GPS, GLONASS, Galileo, QZSS"] },
        { label: "USB", value: ["Type-C Port"] },
        { label: "Audio Jack", value: ["USB Type-C"] },
      ],
    },
    {
      title: "OS",
      rows: [
        { label: "Operating System", value: ["Based on Android 15 (Realme UI 6.0)"] },
      ],
    },
    {
      title: "Features",
      rows: [
        { label: "Fingerprint", value: ["In-display optical fingerprint sensor"] },
        { label: "Sensors", value: ["Proximity sensor", "Ambient light sensor", "Color temperature sensor", "E-compass, Accelerometer", "Gyroscope", "In-display optical fingerprint sensor", "Infrared remote control"] },
        { label: "IP Rating", value: ["IP69"] },
      ],
    },
    {
      title: "Battery",
      rows: [
        { label: "Type", value: ["Li-Ion (Lithium Ion) 7000mAh Titan Battery"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["Flowing Silver: 162.26×76.15×7.79 mm", "Velvet Green: 162.26×76.15×7.84 mm"] },
        { label: "Weight", value: ["187g"] },
        { label: "Body Material", value: ["Rear cover is crafted from eco-leather", "Frame is made of plastic"] },
        { label: "Colors", value: ["Flowing Silver, Velvet Green"] },
      ],
    },
  ],

  description: {
    title: "realme 15 Pro 5G (12/256GB)",
    blocks: [
      {
        paragraphs: [
          "The realme 15 Pro 5G (12/256GB) is engineered to deliver flagship-level performance, immersive visuals, and long-lasting reliability for everyday use. Combining cutting-edge 5G connectivity, a massive 144Hz HyperGlow 4D Curve+ AMOLED display, and a robust 7000mAh battery, this smartphone is designed for multitaskers, gamers, and content creators alike. Its sleek design and premium materials ensure that it not only performs exceptionally but also feels comfortable and luxurious in your hand.",
        ],
      },
      {
        heading: "realme 15 Pro 5G Specifications",
        paragraphs: [
          "The realme 15 Pro 5G (12/256GB) delivers flagship performance with the Dimensity 7300+ 5G chipset and 12GB RAM for smooth multitasking and gaming. Its 6.8-inch 144Hz HyperGlow 4D Curve+ AMOLED display offers vibrant, immersive visuals, while dual 50MP rear cameras capture stunning photos and 4K videos. With a 7000mAh battery and 80W SuperVOOC fast charging, sleek eco-leather design, and IP69 dust and water resistance, it’s powerful, stylish, and built to last.",
          "Size: 6.8 inches",
          "Type: 144Hz HyperGlow 4D Curve+ Display",
          "Resolution: 1280 × 2800 pixels",
          "Refresh Rate: Up to 144Hz",
          "Brightness: 1800 nits (HBM) / 6500 nits Peak",
          "Protection: Corning Gorilla Glass 7i",
          "Screen-to-body ratio: 94%",
          "Contrast ratio: 5,000,000:1",
          "1.07 billion colors (10-bit)",
          "4608Hz PWM Dimming",
          "Chipset: Qualcomm Snapdragon R7 Gen 4",
          "CPU: 4nm Octa-core, up to 2.8GHz",
          "GPU: Adreno GPU @1150MHz",
          "RAM: 12GB",
          "Storage (ROM): 256GB",
          "Rear Camera: Resolution: 50 MP + 50 MP dual camera",
          "Front Camera: Resolution: 50 MP",
          "Supports: Video zoom and dual-video recording",
          "SIM: 2 Nano SIM slots",
          "GPS: Beidou, GPS, GLONASS, Galileo, QZSS",
          "USB: Type-C port",
          "OS: Android 15 (realme UI 6.0)",
          "Fingerprint Sensor: In-display optical",
          "IP69 (Water and dust resistant)",
          "Type: Lithium-Ion 7000mAh Titan Battery",
        ],
      },
      {
        heading: "Next-Level Performance with Dimensity 7300+ 5G",
        paragraphs: [
          "Under the hood, the realme 15 Pro 5G is powered by the MediaTek Dimensity 7300+ 5G chipset, built on an advanced 4nm process. This octa-core processor ensures lightning-fast speed and efficiency, making gaming, streaming, and multitasking smooth and responsive. Paired with the Arm Mali-G615 GPU, it delivers rich graphics performance for high-end games and multimedia content. With 12GB RAM and 256GB storage, you get ample space and performance for all your apps, files, and creative projects.",
        ],
      },
      {
        heading: "Immersive 144Hz HyperGlow 4D Curve+ AMOLED Display",
        paragraphs: [
          "Experience visuals like never before with the 6.8-inch HyperGlow 4D Curve+ AMOLED display. Its Full HD+ resolution provides crisp and vibrant visuals, while the 144Hz refresh rate ensures silky-smooth scrolling and fluid gameplay. With ultra-bright 6500-nit peak brightness and a 94% screen-to-body ratio, the display is perfect for outdoor use and immersive viewing. Every video, game, and photo comes alive with rich colors and sharp details that elevate your mobile experience.",
        ],
      },
      {
        heading: "Dual 50MP Cameras for Stunning Photography",
        paragraphs: [
          "Capture life’s moments in breathtaking clarity with the dual 50MP rear cameras of the realme 15 Pro 5G. Whether it’s bright daylight or low-light environments, the AI-enhanced camera system ensures sharp, vibrant shots. Video enthusiasts will enjoy 4K recording at 30fps with advanced stabilization, while cinematic features like SLO-MO and dual-view video enable creative storytelling. The front camera is perfect for high-quality selfies and video calls, keeping you ready for any occasion.",
        ],
      },
      {
        heading: "All-Day Battery with Fast Charging",
        paragraphs: [
          "The 7000mAh Titan battery ensures that the realme 15 Pro 5G keeps up with your busy lifestyle. From gaming marathons to back-to-back work calls, you’ll have power that lasts all day. With 80W SuperVOOC fast charging, you can quickly recharge and get back to action without interruption. The battery’s intelligent management system optimizes power usage, so you can enjoy extended performance without compromise.",
        ],
      },
      {
        heading: "Premium Design and Durable Build",
        paragraphs: [
          "The realme 15 Pro 5G combines style and durability with its eco-leather rear cover and plastic frame, delivering a comfortable grip and a luxurious feel. Slim and lightweight, it fits perfectly in your hand while remaining resistant to scratches and minor impacts. The IP69 rating ensures robust protection against dust and water, making this phone reliable for various environments and everyday adventures.",
        ],
      },
      {
        heading: "Smart Features for Effortless Use",
        paragraphs: [
          "Running on realme UI 6.0 based on Android 15, the realme 15 Pro 5G offers a clean, intuitive interface with smart multitasking and enhanced security. Features like the side-mounted fingerprint sensor, AI-assisted optimizations, and immersive display interactions make daily use smooth and convenient. Every aspect of the device is designed to keep your digital life efficient, responsive, and secure.",
        ],
      },
      {
        heading: "Buying the realme 15 Pro 5G (12/256GB) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
