/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/xiaomi-redmi-pad-2-9-7-inch-4gb-128gb.jpeg";
import img2 from "@/images/products/redmi-pad-2-9-7-inch-4gb-128gb/02-redmi-pad-2-9-7-inch-4g-gray.jpeg";

export const redmiPad297Inch4gb128gb: ProductDetail = {
  breadcrumb: ["Tablets", "Xiaomi"],
  gallery: [img1, img2],
  inStock: true,

  highlights: [
    "Display Type: 9.7\" 2K 120Hz crystal-clear display",
    "Processor: Snapdragon 6s 4G Gen 2 Mobile Platform",
    "Battery Capacity: 7600mAh (typ)",
    "Camera: 8MP + 5MP",
  ],

  colors: [
    { name: "Graphite Gray", hex: "#4B4E53", image: img2 },
    { name: "Silver", hex: "#ededed", image: img1 },
  ],

  emi: { months: 12, perMonth: 1833 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["REDMI"] },
        { label: "Model Name", value: ["Pad 2"] },
      ],
    },
    {
      title: "Main Feature",
      rows: [
        { label: "Display Type", value: ["crystal-clear display"] },
        { label: "Size", value: ["9.7\""] },
        { label: "Resolution", value: ["2048 x 1280"] },
        { label: "RAM", value: ["4GB"] },
        { label: "Storage", value: ["128GB"] },
        { label: "Processor", value: ["Snapdragon 6s 4G Gen 2 Mobile Platform"] },
        { label: "Operating System", value: ["Xiaomi HyperOS 3"] },
        { label: "Audio", value: ["Immersive stereo speakers", "Supports audio formats: MP3, FLAC, AAC, OGG, WAV, AMR, AWB", "Hi-Res Audio", "3.5mm headphone jack"] },
        { label: "Others", value: ["IPv6", "AI face unlock", "6nm manufacturing process", "CPU: 8-core", "GPU: Adreno 610", "Refresh rate: 120Hz", "Brightness: 500 nits (typ), 600 nits (Outdoor mode)"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimensions", value: ["226.51 mm*147.97 mm*7.4 mm"] },
        { label: "Weight", value: ["406g"] },
        { label: "Color", value: ["Graphite Gray, Silver"] },
      ],
    },
    {
      title: "Camera",
      rows: [
        { label: "Front Camera", value: ["5MP"] },
        { label: "Rear Camera", value: ["8MP"] },
        { label: "Video", value: ["Rear camera video recording: 1080P 1920 x 1080 30fps 720P 1280 x 720 30fps", "Front camera video recording: 1080P 1920 x 1080 30fps720P 1280 x 720 30fps"] },
      ],
    },
    {
      title: "Battery",
      rows: [
        { label: "Type", value: ["7600mAh (typ)"] },
        { label: "Charging", value: ["18W Fast charging (In box 15W)"] },
      ],
    },
    {
      title: "Special Features",
      rows: [
        { label: "Sensors", value: ["Virtual ambient light sensor", "Accelerometer", "Hall sensor"] },
        { label: "Bluetooth", value: ["5.0"] },
        { label: "WLAN", value: ["Wi-Fi 5 capability"] },
        { label: "GPS", value: ["GPS: L1", "A-GPS supplementary positioning"] },
        { label: "USB", value: ["USB Type-C"] },
      ],
    },
  ],

  description: {
    title: "REDMI Pad 2 9.7\" (4/128GB)",
    blocks: [
      {
        paragraphs: [
          "The REDMI Pad 2 9.7\" (4/128GB) is a powerful and stylish tablet built for entertainment, learning, and everyday productivity. With its smooth 120Hz display, reliable Snapdragon processor, and long-lasting battery, it delivers an exceptional experience for users looking for the best budget tablet in Bangladesh.",
        ],
      },
      {
        heading: "Immersive 9.7\" Crystal-Clear Display",
        paragraphs: [
          "Enjoy stunning visuals on the 9.7-inch display with a crisp 2048 × 1280 resolution. The 120Hz refresh rate ensures smooth scrolling and fluid animations, making it perfect for watching videos, reading, and gaming. With brightness up to 600 nits, the display remains clear even in outdoor conditions.",
        ],
      },
      {
        heading: "Powerful Performance with Snapdragon Processor",
        paragraphs: [
          "Powered by the Snapdragon 6s 4G Gen 2 chipset built on a 6nm process, the REDMI Pad 2 offers efficient performance and seamless multitasking. The octa-core CPU paired with Adreno 610 GPU ensures smooth app usage, gaming, and streaming. With 4GB RAM and 128GB storage, you get ample space and speed for daily tasks.",
        ],
      },
      {
        heading: "All-Day Battery Life with Fast Charging",
        paragraphs: [
          "Equipped with a massive 7600mAh battery, this tablet is designed to last throughout the day. Whether you're studying, working, or streaming content, you can rely on its long battery life. It supports 18W fast charging, allowing you to quickly recharge and stay productive.",
        ],
      },
      {
        heading: "Smart Features & Smooth HyperOS Experience",
        paragraphs: [
          "Running on Xiaomi HyperOS 3, the REDMI Pad 2 provides a clean, responsive, and user-friendly interface. Features like AI face unlock enhance convenience and security, while connectivity options such as Bluetooth 5.0, Wi-Fi 5, and USB Type-C ensure seamless device integration.",
        ],
      },
      {
        heading: "Slim, Lightweight & Premium Design",
        paragraphs: [
          "With a sleek thickness of just 7.4mm and a lightweight body of 406g, the tablet is easy to carry and comfortable to use for extended periods. Its modern design, available in Graphite Gray and Silver, adds a premium touch.",
        ],
      },
      {
        heading: "Capture & Connect with Dual Cameras",
        paragraphs: [
          "The REDMI Pad 2 comes with an 8MP rear camera and a 5MP front camera, perfect for video calls, online classes, and basic photography. Both cameras support 1080p video recording, ensuring clear visuals. Experience rich and immersive sound with stereo speakers and Hi-Res Audio support. The inclusion of a 3.5mm headphone jack ensures flexibility for personal listening, making it a great tablet for music and entertainment lovers.",
        ],
      },
      {
        heading: "Buying the REDMI Pad 2 9.7\" (4/128GB) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
