/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/samsung-galaxy-s26-ultra-clear-magnet-case.jpeg";
import img2 from "@/images/products/samsung-galaxy-s26-ultra-clear-magnet-case/02-samsung-galaxy-s26-ultra-clear-magnet-case-clear-1.jpeg";
import img3 from "@/images/products/samsung-galaxy-s26-ultra-clear-magnet-case/03-samsung-galaxy-s26-ultra-clear-magnet-case-clear-2.jpeg";

export const samsungGalaxyS26UltraClearMagnetCase: ProductDetail = {
  breadcrumb: [
    { label: "Cases & Protectors", slug: "cases-screen-protectors" },
    { label: "Samsung", slug: "samsung-cases-accessories" },
    { label: "Galaxy S26 Ultra", slug: "galaxy-s26-ultra-cases-screen-protectors" },
  ],
  gallery: [img1, img2, img3],
  inStock: true,

  highlights: [
    "Clear protection & Comfortable grip.",
    "Anti-yellowing & anti-fingerprint coating.",
    "Maintaining phone's original design without smudges or discoloration over time.",
    "Built-in magnets in the Clear Magnet Case help align Galaxy S26 Ultra for fast wireless charging.",
  ],

  colors: [
    { name: "Clear", hex: "#CDCCCD", image: img1 },
  ],

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["Samsung"] },
        { label: "Model Name", value: ["Clear Magnet"] },
        { label: "MPN/ Part No", value: ["EF-CS948CTEGWW"] },
      ],
    },
    {
      title: "Product Specifications",
      rows: [
        { label: "Compatible Devices", value: ["Galaxy S26 Ultra"] },
        { label: "Material", value: ["Thermoplastic Polyurethane (TPU)"] },
        { label: "Special Feature", value: ["anti-yellowing and anti-fingerprint coating", "maintaining a sleek, natural grip", "maintaining phone's original design"] },
        { label: "Dimensions", value: ["80 x 165.5 x 13.2 mm"] },
        { label: "Weight", value: ["24g"] },
        { label: "Color", value: ["Clear"] },
      ],
    },
  ],

  description: {
    title: "Samsung Galaxy S26 Ultra Clear Magnet Case",
    blocks: [
      {
        paragraphs: [
          "Show off the true beauty of your smartphone with the Samsung Galaxy S26 Ultra Clear Magnet Case, designed to protect your device while keeping its original look intact. This slim, transparent case delivers everyday durability with a clean, minimalist style—perfect for users who want protection without hiding their phone’s premium design.",
        ],
      },
      {
        heading: "Crystal Clear Design with Anti-Yellowing Technology",
        paragraphs: [
          "Crafted from high-quality Thermoplastic Polyurethane (TPU), this clear case features advanced anti-yellowing coating that keeps it looking fresh and transparent over time. Unlike ordinary clear cases, it resists discoloration and maintains the original aesthetics of your Galaxy S26 Ultra. Precisely engineered for the Samsung Galaxy S26 Ultra, this case offers accurate cutouts and responsive button covers. It provides reliable protection against scratches, dust, and minor impacts while allowing full access to all features.",
        ],
      },
      {
        heading: "Magnetic Compatibility for Easy Charging",
        paragraphs: [
          "The built-in magnet system ensures smooth compatibility with wireless chargers and magnetic accessories. You can enjoy effortless charging without removing the case, making it a practical choice for modern smartphone users who rely on fast and convenient charging solutions.",
        ],
      },
      {
        heading: "Slim, Lightweight & Comfortable Grip",
        paragraphs: [
          "With a sleek profile (80 x 165.5 x 13.2 mm) and lightweight build (only 24g), this case adds minimal bulk to your phone. The anti-fingerprint coating helps keep the surface clean, while the natural grip design ensures a secure and comfortable hold throughout the day.",
        ],
      },
      {
        heading: "Buying the Samsung Galaxy S26 Ultra Clear Magnet Case from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
