/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/samsung-60w-pd-fast-charger.jpeg";
import img2 from "@/images/products/samsung-60w-pd-fast-charger/02-samsung-60w-pd-fast-charger-1.jpeg";
import img3 from "@/images/products/samsung-60w-pd-fast-charger/03-samsung-60w-pd-fast-charger-2.jpeg";
import img4 from "@/images/products/samsung-60w-pd-fast-charger/04-samsung-60w-pd-fast-charger-3.jpeg";

export const samsung60wPdFastCharger: ProductDetail = {
  breadcrumb: [
    { label: "Phone Accessories", slug: "mobile-phone-accessories" },
    { label: "Charger & Adapter", slug: "charger-adapters" },
    { label: "Adapter", slug: "adapter" },
  ],
  gallery: [img1, img2, img3, img4],
  inStock: true,

  highlights: [
    "Interface: USB Type-C",
    "60W PD Charger",
    "Input Voltage 100-240 V",
    "Plug: 2 Pin",
  ],

  colors: [
    { name: "Black", hex: "#000000", image: img1 },
  ],

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["Samsung"] },
        { label: "Model Name", value: ["EP-T6010"] },
      ],
    },
    {
      title: "Product specifications",
      rows: [
        { label: "Type", value: ["Charger Adapter"] },
        { label: "Interface", value: ["Type-C"] },
        { label: "Others", value: ["PD 3.1", "GaN Technology"] },
        { label: "Weight", value: ["149g"] },
        { label: "Color", value: ["Black"] },
      ],
    },
  ],

  description: {
    title: "Samsung 60W PD Fast Charger Adapter (without cable)",
    blocks: [
      {
        paragraphs: [
          "The Samsung 60W PD Fast Charger Adapter (without cable) is a powerful USB-C charging solution designed to keep your compatible smartphones, tablets, laptops, and other USB-C devices charged quickly and efficiently. Featuring advanced Power Delivery (PD) 3.1 technology and GaN (Gallium Nitride) architecture, this compact charger delivers high-speed performance while maintaining excellent energy efficiency. Whether you're at home, in the office, or traveling, it's an ideal everyday charging companion.",
        ],
      },
      {
        heading: "Fast and Efficient 60W USB-C Charging",
        paragraphs: [
          "Equipped with a USB Type-C port and supporting the latest PD 3.1 fast-charging standard, the Samsung EP-T6010 provides up to 60W of power for compatible devices. GaN technology helps reduce heat generation while allowing the charger to remain compact, efficient, and reliable during extended use.",
        ],
      },
      {
        heading: "Compact Design with Wide Compatibility",
        paragraphs: [
          "Weighing only 149g, this charger is easy to carry and works seamlessly with Samsung Galaxy smartphones, Galaxy Tab series, USB-C laptops, earbuds, power banks, and other Power Delivery-enabled devices. Simply pair it with a compatible USB-C charging cable to enjoy fast and safe charging.",
        ],
      },
      {
        heading: "Buying the Samsung 60W PD Fast Charger Adapter (without cable) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
