/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/sony-srs-ult50-portable-wireless-speaker.jpeg";
import img2 from "@/images/products/sony-srs-ult50-portable-wireless-speaker/02-sony-srs-ult50-portable-wireless-speaker-1736.jpeg";
import img3 from "@/images/products/sony-srs-ult50-portable-wireless-speaker/03-sony-srs-ult50-portable-wireless-speaker-2666.jpeg";

export const sonySrsUlt50PortableWirelessSpeaker: ProductDetail = {
  breadcrumb: [
    { label: "Headphone & Speaker", slug: "headphone-speaker" },
    { label: "Speaker", slug: "speakers" },
    { label: "Sony", slug: "sony-speaker" },
  ],
  gallery: [img1, img2, img3],
  inStock: true,

  highlights: [
    "360° Immersive Sound",
    "Extra Bass & Live Sound Mode",
    "IP67 Waterproof & Dustproof",
    "Multi-Speaker Party Connect",
  ],

  colors: [
    { name: "Black", hex: "#000000", image: img1 },
  ],

  emi: { months: 12, perMonth: 3667 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["Sony"] },
        { label: "Model Name", value: ["SRS-ULT50"] },
      ],
    },
    {
      title: "Main Features",
      rows: [
        { label: "Connection Type", value: ["Wireless"] },
        { label: "Bluetooth Version", value: ["Bluetooth Version 5.3"] },
        { label: "Battery Life", value: ["Up to 25 hours continuous playback"] },
        { label: "Charging Type", value: ["USB Type-C charging"] },
        { label: "Battery charge time", value: ["3 hours"] },
        { label: "Output power (W)", value: ["100W (combined)"] },
        { label: "Others", value: ["360° Reality Audio, Extra Bass, Live Sound Mode, Party Connect multi-speaker link, built-in microphone for hands-free calls, voice assistant support (Google Assistant & Siri)"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["(Approx): 17 × 43 × 17 cm"] },
        { label: "Weight", value: ["6.0 kg"] },
      ],
    },
  ],

  description: {
    title: "Sony SRS-ULT50 Wireless Bluetooth Speaker",
    blocks: [
      {
        paragraphs: [
          "The Sony SRS-ULT50 Wireless Bluetooth Speaker is built for those who crave deep bass, long battery life, and rugged durability in one stylish portable package. This compact yet powerful speaker delivers Sony’s signature ULT Power Sound with rich, immersive audio that stays clear and punchy whether you’re indoors or outdoors. With stunning LED lighting, Bluetooth 5.3 connectivity, and exceptional waterproofing, it’s made for music lovers who want premium sound anywhere.",
        ],
      },
      {
        heading: "Sony SRS-ULT50 Wireless Bluetooth Speaker Specifications",
        paragraphs: [
          "Sony SRS-ULT50 Wireless Bluetooth Speaker delivers powerful ULT bass, rich audio clarity, and long-lasting performance in a compact, travel-friendly design. With Bluetooth 5.3, LDAC support, and up to 25 hours of battery life, it ensures high-quality sound wherever you go. Its IP66/IP67 water and dust resistance make it perfect for outdoor adventures, while Party Connect and stereo pairing let you expand your soundstage anytime. The USB-C in/out port even works as a power bank, making the SRS-ULT50 an ideal companion for music lovers on the move.",
        ],
      },
      {
        heading: "ULT Power Sound with Dual Bass Modes",
        paragraphs: [
          "The Sony SRS-ULT50 features Sony’s advanced ULT Power Sound technology, offering two bass modes—ULT1 for balanced heavy bass and ULT2 for deep, thunderous low-end performance. It transforms your listening experience with dynamic beats that make your music feel alive. This wireless Bluetooth speaker keeps the party running with up to 25 hours of nonstop playback. Even when you're outdoors all day, the long-lasting battery ensures your music never stops. Fast charging support lets you get hours of usage in just a few minutes.",
        ],
      },
      {
        heading: "Rugged IP66 / IP67 Water and Dust Protection",
        paragraphs: [
          "Built for travel and outdoor adventures, the SRS-ULT50 is both IP66 and IP67 rated. It can survive splashes, rain, beach sand, poolside spills, and even brief submersion, making it an ideal speaker for camping, hiking, and beach trips.",
        ],
      },
      {
        heading: "Crystal-Clear Bluetooth 5.3 + LDAC High-Resolution Audio",
        paragraphs: [
          "Enjoy stable wireless performance with Bluetooth 5.3 and experience high-resolution audio through LDAC support. Whether you're streaming music or watching content, the connection stays smooth with premium sound detail and clarity. Expand your soundstage by linking multiple Sony speakers using Party Connect. Whether you're hosting a house party or creating an immersive stereo setup, the SRS-ULT50 integrates seamlessly with compatible Sony models. With a versatile USB-C port, you can charge the speaker or use it as a power bank for your smartphone. This makes the Sony SRS-ULT50 a perfect travel companion when you’re on the move and need portable power.",
        ],
      },
      {
        heading: "Buying the Sony SRS-ULT50 Wireless Bluetooth Speaker from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
