/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/spigen-ultra-hybrid-magfit-case-for-galaxy-s26-ultra.jpeg";
import img2 from "@/images/products/spigen-ultra-hybrid-magfit-case-for-galaxy-s26-ultra/02-spigen-ultra-hyrbird-magfit-case-for-galaxy-s26-ultra-3.jpeg";
import img3 from "@/images/products/spigen-ultra-hybrid-magfit-case-for-galaxy-s26-ultra/03-spigen-ultra-hyrbird-magfit-case-for-galaxy-s26-ultra-6.jpeg";

export const spigenUltraHybridMagfitCaseForGalaxyS26Ultra: ProductDetail = {
  breadcrumb: ["Cases & Protectors", "Samsung", "Galaxy S26 Ultra"],
  gallery: [img1, img2, img3],
  inStock: true,

  highlights: [
    "Qi2 Certified - Fast wireless charging enabled",
    "Clear and simple to showcase the look and color of the new Galaxy",
    "Mil-grade certified drop protection with Air Cushion Technology",
    "Hard shell back remains clear with zero yellowing over time",
  ],

  colors: [
    { name: "Clear White", hex: "#F7F7F7", image: img2 },
    { name: "Matte Black", hex: "#2D2D2D", image: img3 },
    { name: "Frost Black", hex: "#757575", image: img1 },
  ],

  specs: [
    {
      title: "Product Specifications",
      rows: [
        { label: "Compatible Devices", value: ["Galaxy S26 Ultra"] },
        { label: "Color", value: ["Clear White, Matte Black, Frost Black"] },
        { label: "MagSafe Compatibility", value: ["Yes"] },
        { label: "Special Feature", value: ["Qi2 Certified - Fast wireless charging enabled.", "Clear and simple to showcase the look and color of the new Galaxy.", "Mil-grade certified drop protection with Air Cushion Technology.", "Hard shell back remains clear with zero yellowing over time.", "Extra raise around the cameras to keep off flat surfaces.", "Metal Ring integrated for Magnetic compatibility."] },
      ],
    },
  ],

  description: {
    title: "Spigen Ultra Hybrid MagFit Case for Galaxy S26 Ultra",
    blocks: [
      {
        paragraphs: [
          "The Spigen Ultra Hybrid MagFit Case for Galaxy S26 Ultra is built for users who want strong protection while showing off the premium design of their smartphone. With its crystal-clear back and durable hybrid construction, this case protects your device without hiding its original beauty. It also supports magnetic accessories and fast wireless charging, making it a perfect everyday case for your Galaxy S26 Ultra.",
        ],
      },
      {
        heading: "Key Features of Spigen Ultra Hybrid MagFit Case for Galaxy S26 Ultra",
        paragraphs: [
          "The Spigen Ultra Hybrid MagFit Case for Galaxy S26 Ultra features a transparent hard back that keeps the natural color and design of your phone visible. Its minimalist look offers a clean and modern style while maintaining reliable protection. The durable back panel is designed to resist discoloration, helping it stay clear and fresh even after long-term use. Protection is at the core of this Spigen case. It is military-grade certified, meaning it has been tested to withstand drops and daily impacts. The built-in Air Cushion Technology absorbs shock during accidental falls, reducing the risk of damage. In addition, the slightly raised edges around the camera module help prevent scratches when the phone is placed on flat surfaces. This case comes with an integrated metal ring that supports MagFit magnetic accessories, allowing easy attachment to magnetic mounts and chargers. It is also Qi2 certified, enabling fast and stable wireless charging without removing the case. The design ensures your Galaxy S26 Ultra remains fully functional and convenient to use every day.",
        ],
      },
      {
        heading: "Buying the Spigen Ultra Hybrid MagFit Case for Galaxy S26 Ultra from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
