/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/spigen-liquid-air-magfit-case-for-galaxy-s26-ultra.jpeg";
import img2 from "@/images/products/spigen-liquid-air-magfit-case-for-galaxy-s26-ultra/02-spigen-liquid-air-magfit-case-for-galaxy-s26-ultra.jpeg";
import img3 from "@/images/products/spigen-liquid-air-magfit-case-for-galaxy-s26-ultra/03-spigen-liquid-air-magfit-case-for-galaxy-s26-ultra-grey.jpeg";

export const spigenLiquidAirMagfitCaseForGalaxyS26Ultra: ProductDetail = {
  breadcrumb: [
    { label: "Cases & Protectors", slug: "cases-screen-protectors" },
    { label: "Samsung", slug: "samsung-cases-accessories" },
    { label: "Galaxy S26 Ultra", slug: "galaxy-s26-ultra-cases-screen-protectors" },
  ],
  gallery: [img1, img2, img3],
  inStock: true,

  highlights: [
    "Slim and grip-friendly for everyday use",
    "Flexible and shock-absorbent layer",
    "Ridiculously precise and responsive buttons",
    "Mil-grade certified protection with Air Cushion Technology",
  ],

  colors: [
    { name: "Abyss Green", hex: "#394545", image: img1 },
    { name: "Matte Black", hex: "#2D2D2D", image: img2 },
    { name: "Marble Gray", hex: "#6A6866", image: img3 },
  ],

  specs: [
    {
      title: "Product Specifications",
      rows: [
        { label: "Compatible Devices", value: ["Galaxy S26 Ultra"] },
        { label: "Color", value: ["Abyss Green, Matte Black"] },
        { label: "MagSafe Compatibility", value: ["Yes"] },
        { label: "Special Feature", value: ["Slim and grip-friendly for everyday use.", "Flexible and shock-absorbent layer.", "Ridiculously precise and responsive buttons.", "Mil-grade certified protection with Air Cushion Technology.", "Compatible with wireless and reverse charging.", "Built-in magnets for compatibility with MagFit magnetic accessories and more."] },
      ],
    },
  ],

  description: {
    title: "Spigen Liquid Air (MagFit) Case for Galaxy S26 Ultra",
    blocks: [
      {
        paragraphs: [
          "The Spigen Liquid Air (MagFit) Case for Galaxy S26 Ultra is designed for users who prefer a slim yet protective case for everyday use. With its lightweight design, textured grip, and reliable drop protection, this case keeps your smartphone safe without adding unnecessary bulk. Built with magnetic compatibility and wireless charging support, it delivers both convenience and durability for your Galaxy S26 Ultra.",
        ],
      },
      {
        heading: "Key Features of Spigen Liquid Air (MagFit) Case for Galaxy S26 Ultra",
        paragraphs: [
          "The Spigen Liquid Air (MagFit) Case for Galaxy S26 Ultra features a slim profile that fits comfortably in your hand and pocket. Its textured surface enhances grip, helping prevent accidental slips while maintaining a clean and modern look. This lightweight design makes it ideal for users who want protection without compromising the sleek feel of their device. Crafted from a flexible and shock-absorbent material, the case helps protect your Galaxy S26 Ultra from everyday drops and impacts. It is military-grade certified, thanks to Air Cushion Technology integrated into the corners, which effectively absorbs shock and reduces damage during accidental falls. This case includes built-in magnets that support MagFit magnetic accessories, allowing seamless attachment to magnetic mounts and compatible chargers. It also supports wireless charging and reverse charging, so you can power up your phone or share battery without removing the case. The precisely engineered tactile buttons provide a responsive and natural press for volume and power controls. Every detail is carefully designed to maintain the original functionality of the Galaxy S26 Ultra while ensuring easy and comfortable operation.",
        ],
      },
      {
        heading: "Buying the Spigen Liquid Air (MagFit) Case for Galaxy S26 Ultra from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
