/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/starlink-standard-kit.jpeg";
import img2 from "@/images/products/starlink-standard-kit/02-starlink-standard-kit-7418.jpeg";
import img3 from "@/images/products/starlink-standard-kit/03-starlink-standard-kit-9248.jpeg";
import img4 from "@/images/products/starlink-standard-kit/04-starlink-standard-kit-1968.jpeg";
import img5 from "@/images/products/starlink-standard-kit/05-starlink-standard-kit-8643.jpeg";
import img6 from "@/images/products/starlink-standard-kit/06-starlink-standard-kit-10643.jpeg";
import img7 from "@/images/products/starlink-standard-kit/07-starlink-standard-kit-2576.jpeg";
import img8 from "@/images/products/starlink-standard-kit/08-starlink-standard-kit-334.jpeg";
import img9 from "@/images/products/starlink-standard-kit/09-starlink-standard-kit-4993.jpeg";

export const starlinkStandardKit: ProductDetail = {
  breadcrumb: ["Networking", "Starlink"],
  gallery: [img1, img2, img3, img4, img5, img6, img7, img8, img9],
  inStock: false,

  highlights: [
    "Antenna: Electronic Phased Array",
    "Frequency: Tri-Band 4 x 4 MU-MIMO, Wi-Fi 6",
    "Coverage: Up to 297 m&sup2; (3,200 ft&sup2;), Connect up to 235 Devices",
    "Ethernet Ports: 2x Latching Ethernet LAN ports with removable cover",
    "Condition: The kit must be activated within 24 hours of receiving.",
  ],

  emi: { months: 6, perMonth: 8250 },

  specs: [
    {
      title: "Main Features",
      rows: [
        { label: "Antenna", value: ["Electronic Phased Array"] },
        { label: "Frequency", value: ["Tri Band 4 x 4 MU-MIMO"] },
        { label: "Network Standard", value: ["802.11 a/b/g/n/ac/ax"] },
        { label: "Wireless", value: ["WiFi 6"] },
        { label: "Encryption", value: ["WPA2"] },
        { label: "Ports", value: ["2x Latching Ethernet LAN ports with removable cover"] },
        { label: "Others", value: ["Field of View: 110 °", "Orientation: Software Assisted Manual Orienting", "Environmental Rating: IP67 Type 4", "Wind Speed: Operational: 96 kph+ (60 mph+)", "Snow Melt Capability: Up to 40 mm / hour (1.5 in / hour)", "Coverage: Up to 297 m² (3,200 ft²)", "Environmental Rating: Meeting IP56 (Water Resistant), configured for indoor use", "Power Indicator: LED | face plate, lower left corner of router", "Mesh Compatibility: Compatible with Starlink Gen 2 and Gen 3 Mesh nodes, up to 3 Starlink Mesh Nodes. *Not compatible with 3rd party mesh systems", "Devices: Connect up to 235 devices"] },
      ],
    },
    {
      title: "Power Source",
      rows: [
        { label: "Power Mode", value: ["100-240V ~ 2.5A 50 - 60 Hz"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["594 x 383 x 39.7 mm (23.4 x 15.07 x 1.5 in) (Starlink)", "43.4 x 298.6 x 120.4 mm (1.7 in x 11.76 in x 4.74 in) (Router)", "173 x 93 x 35.75 mm (6.8 in x 3.66 in x 1.4 in) (Power Supply)", "652.4 x 451.7 x 97.9 mm (25.69 x 17.78 x 3.84 in) (Package)"] },
        { label: "Weight", value: ["2.9 kg (6.4 lb) (Starlink)", "3.2 kg (7 lb) with Kickstand (Starlink)", "3.8 kg (8.3 lb) with Kickstand & Cable (Starlink)", "0.57 kg (1.25 lbs) (Router)", "0.65 kg (1.43 lbs) (Power Supply)", "6.73 kg (14.83 lbs) (Package)"] },
        { label: "Color", value: ["White"] },
      ],
    },
  ],

  description: {
    title: "Starlink Standard Kit",
    blocks: [
      {
        heading: "Starlink Standard Kit Specification",
        paragraphs: [
          "The Starlink Standard Kit is built with WiFi 6 and Tri-Band 4x4 MU-MIMO—meaning it delivers stronger, faster connections to more devices, all at once. Perfect for homes, remote offices, or digital nomads, it handles everything from streaming 4K content to hosting virtual meetings without lag or buffering.",
          "Antenna: Electronic Phased Array",
          "Frequency: Tri Band 4 x 4 MU-MIMO",
          "Network Standard: 802.11 a/b/g/n/ac/ax",
          "Wireless: WiFi 6",
          "Encryption: WPA2",
          "Ports: 2x Latching Ethernet LAN ports with removable cover",
          "Field of View: 110°",
          "Orientation: Software Assisted Manual Orienting",
          "Environmental Rating (Antenna): IP67 Type 4",
          "Environmental Rating (Router): IP56 (Water Resistant), configured for indoor use",
          "Wind Speed Tolerance: Operational at 96 kph+ (60 mph+)",
          "Snow Melt Capability: Up to 40 mm/hour (1.5 in/hour)",
          "Coverage Area: Up to 297 m&sup2; (3,200 ft&sup2;)",
          "Power Indicator: LED on face plate, lower left corner of router",
          "Mesh Compatibility: Supports Starlink Gen 2 and Gen 3 Mesh Nodes (up to 3 nodes)",
          "Device Capacity: Connect up to 235 devices",
          "Power Mode: 100-240V ~ 2.5A, 50 - 60 Hz",
        ],
      },
      {
        heading: "Advanced Antenna for Maximum Coverage",
        paragraphs: [
          "At the core of the system is an electronic phased array antenna, a powerful piece of technology engineered to track Starlink satellites in real-time. Combined with a 110° field of view and software-assisted manual orienting, the antenna ensures consistent, high-speed connectivity in nearly any weather condition.",
        ],
      },
      {
        heading: "Built for Harsh Conditions",
        paragraphs: [
          "This kit is ready for the outdoors and extreme environments. With an IP67 rating, it’s water- and dust-resistant, operates smoothly in wind speeds over 96 kph (60 mph), and features snow melt capability of up to 40mm/hour. That means uninterrupted performance even during heavy snowfall or storms.",
        ],
      },
      {
        heading: "Massive Coverage and Device Support",
        paragraphs: [
          "If you’re looking to cover a large home or office, the Starlink Standard Kit delivers with up to 297 m&sup2; (3,200 ft&sup2;) of coverage. You can also connect up to 235 devices, making it a powerhouse for smart homes, small businesses, or shared living spaces.",
        ],
      },
      {
        heading: "Mesh-Ready for Seamless Expansion",
        paragraphs: [
          "The router included in the Starlink Standard Kit supports Starlink Gen 2 and Gen 3 mesh nodes, allowing you to expand your network across multiple rooms or buildings. Keep in mind, however, that third-party mesh systems are not supported—this ensures maximum stability and performance within the Starlink ecosystem.",
        ],
      },
      {
        heading: "Dual Ethernet Ports for Wired Speed",
        paragraphs: [
          "Unlike the Mini version, the Standard Kit comes with two latching Ethernet LAN ports—perfect for gamers, streamers, or anyone who needs direct-wired connections for extra speed and stability. The removable port cover allows easy setup without compromising the design.",
        ],
      },
      {
        heading: "Buying the Starlink Standard Kit from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
