/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/tecno-camon-air.jpeg";
import img2 from "@/images/products/tecno-camon-air/02-tecno-camon-air-red.jpeg";
import img3 from "@/images/products/tecno-camon-air/03-tecno-camon-air-red-1.jpeg";
import img4 from "@/images/products/tecno-camon-air/04-tecno-camon-air-red-2.jpeg";
import img5 from "@/images/products/tecno-camon-air/05-tecno-camon-air-red-3.jpeg";
import img6 from "@/images/products/tecno-camon-air/06-tecno-camon-air-black.jpeg";
import img7 from "@/images/products/tecno-camon-air/07-tecno-camon-air-black-1.jpeg";
import img8 from "@/images/products/tecno-camon-air/08-tecno-camon-air-black-2.jpeg";
import img9 from "@/images/products/tecno-camon-air/09-tecno-camon-air-black-3.jpeg";
import img10 from "@/images/products/tecno-camon-air/10-tecno-camon-air-black-4.jpeg";
import img11 from "@/images/products/tecno-camon-air/11-tecno-camon-air-blue-1.jpeg";
import img12 from "@/images/products/tecno-camon-air/12-tecno-camon-air-blue-2.jpeg";
import img13 from "@/images/products/tecno-camon-air/13-tecno-camon-air-blue-3.jpeg";
import img14 from "@/images/products/tecno-camon-air/14-tecno-camon-air-blue-4.jpeg";
import img15 from "@/images/products/tecno-camon-air/15-tecno-camon-air-green.jpeg";

export const tecnoCamonAir: ProductDetail = {
  breadcrumb: ["Phones", "TECNO"],
  gallery: [img1, img2, img3, img4, img5, img6, img7, img8, img9, img10, img11, img12, img13, img14, img15],
  inStock: true,

  highlights: [
    "Display: 6.78'' AMOLED 144Hz 1.5K",
    "Processor: MediaTek Dimensity G200 Ultimate Processor",
    "Camera: 50 MP + 32 MP",
    "Features: Fingerprint (under display, optical)",
  ],

  colors: [
    { name: "Burgundy Red", hex: "#430917", image: img2 },
    { name: "Prism Black", hex: "#161616", image: img6 },
    { name: "Van Gogh Blue", hex: "#4795C3", image: img1 },
    { name: "Jungle Green", hex: "#00755D", image: img15 },
  ],

  emi: { months: 12, perMonth: 3750 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["TECNO"] },
        { label: "Model Name", value: ["Camon Air"] },
      ],
    },
    {
      title: "Display",
      rows: [
        { label: "Size", value: ["6.78 inches (6.39mm)"] },
        { label: "Type", value: ["AMOLED"] },
        { label: "Resolution", value: ["1224*2720"] },
        { label: "Refresh Rate", value: ["144Hz"] },
      ],
    },
    {
      title: "Processor",
      rows: [
        { label: "Chipset", value: ["MediaTek Dimensity G200 Ultimate Processor"] },
      ],
    },
    {
      title: "Memory",
      rows: [
        { label: "RAM", value: ["8GB"] },
        { label: "ROM", value: ["128GB"] },
      ],
    },
    {
      title: "Rear Camera",
      rows: [
        { label: "Resolution", value: ["50MP"] },
      ],
    },
    {
      title: "Front Camera",
      rows: [
        { label: "Resolution", value: ["32MP"] },
      ],
    },
    {
      title: "Audio",
      rows: [
        { label: "Speaker", value: ["Dolby Atmos"] },
      ],
    },
    {
      title: "Network & Connectivity",
      rows: [
        { label: "SIM", value: ["Dual Sim"] },
        { label: "Network", value: ["2G/3G/4G"] },
        { label: "Wi-Fi", value: ["WiFi, BT, FM, GPS, NFC"] },
        { label: "USB", value: ["Type-C Port"] },
      ],
    },
    {
      title: "OS",
      rows: [
        { label: "Operating System", value: ["HiOS 16.3"] },
      ],
    },
    {
      title: "Features",
      rows: [
        { label: "Fingerprint", value: ["Fingerprint (under display, optical)"] },
        { label: "Sensors", value: ["Geomagnetic Sensor", "A+G Sensor", "The ambient light and distance sensor", "Infrared Remote Control", "Electronic compass"] },
        { label: "IP Rating", value: ["IP69/IP68"] },
      ],
    },
    {
      title: "Battery",
      rows: [
        { label: "Type", value: ["6000mAh"] },
        { label: "Fast Charging", value: ["60W Ultra Charge"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["162.8x77.7x6.39mm"] },
        { label: "Weight", value: ["167g"] },
        { label: "Colors", value: ["Burgundy Red, Prism Black, Van Gogh Blue"] },
      ],
    },
  ],

  description: {
    title: "TECNO Camon Air (8/128GB)",
    blocks: [
      {
        paragraphs: [
          "The TECNO Camon Air (8/128GB) is designed for smartphone users who want an impressive display, capable camera system, dependable battery life and smooth everyday performance without moving into the premium flagship price range. The verified 8GB/128GB configuration associated with this listing features a 6.78-inch 144Hz AMOLED display, MediaTek Helio G200 Ultimate processor, 50MP OIS main camera with an 8MP ultra-wide camera, 32MP front camera, 6500mAh battery and 45W fast charging.",
          "For buyers searching for a TECNO phone in Bangladesh that combines camera performance, a high-refresh-rate AMOLED screen and long battery endurance, this 8GB RAM and 128GB storage configuration offers a well-balanced everyday smartphone experience. It is suitable for social media, photography, video streaming, communication, productivity and casual gaming.",
        ],
      },
      {
        heading: "Why Choose TECNO Camon Air (8/128GB)?",
        paragraphs: [
          "The biggest advantage of the TECNO Camon Air (8/128GB) is its balanced hardware package. Instead of focusing on only one specification, the phone brings together a high-refresh-rate AMOLED display, 8GB RAM, a modern MediaTek chipset, OIS-assisted photography, a large battery and 45W charging.",
          "The 8GB RAM helps keep frequently used apps responsive, while 128GB internal storage provides practical space for photos, videos, applications and documents. For users who spend considerable time on Facebook, Instagram, TikTok, YouTube, messaging apps and mobile photography, this combination makes the phone a versatile daily companion.",
        ],
      },
      {
        heading: "TECNO Camon Air (8/128GB) Display",
        paragraphs: [
          "The phone features a large 6.78-inch AMOLED display with a sharp 1208 × 2644 resolution and a fast 144Hz refresh rate. The high refresh rate makes scrolling, animations and supported games feel noticeably smoother, while AMOLED technology delivers rich contrast and vibrant visuals.",
        ],
      },
      {
        heading: "Why the 144Hz AMOLED Display Matters",
        paragraphs: [
          "Smoother scrolling through social media and websites",
          "More fluid animations and interface navigation",
          "Immersive viewing for YouTube, Netflix and other video platforms",
          "Responsive visual experience for compatible games",
          "AMOLED contrast for deeper blacks and vivid colours",
          "If display quality is important to you, the high-refresh-rate AMOLED panel is one of the strongest reasons to consider this TECNO smartphone.",
        ],
      },
      {
        heading: "TECNO Camon Air (8/128GB) Camera",
        paragraphs: [
          "Photography is a major part of the Camon family experience, and this configuration is built around a 50MP main camera with OIS and an 8MP ultra-wide camera. The main camera uses optical image stabilisation to help reduce the effect of hand movement when taking photos.",
          "The ultra-wide camera is useful when you need to fit more into a single frame, making it practical for landscapes, group photos, architecture and travel photography. The camera system also supports AI-assisted photography features designed to make everyday image capture more convenient.",
        ],
      },
      {
        heading: "32MP Front Camera for Selfies and Video Calls",
        paragraphs: [
          "A 32MP front camera gives the phone plenty of resolution for selfies, social media posts and video calls. For users who regularly create content for Facebook, Instagram, TikTok or other social platforms, the front camera adds useful flexibility to the overall camera package.",
        ],
      },
      {
        heading: "MediaTek Dimensity G200 Ultimate Performance with 8GB RAM",
        paragraphs: [
          "The MediaTek Dimensity G200 Ultimate chipset is paired with 8GB RAM to provide a capable platform for everyday multitasking, communication, entertainment and casual gaming. The chipset uses a 6nm manufacturing process and an octa-core CPU configuration, while Mali-G57 MC2 handles graphics processing.",
          "For everyday users, this means you can move between messaging, browsing, social media, streaming and productivity apps without relying on an entry-level hardware platform. Performance will naturally vary by application and workload, so demanding games should be played with graphics settings appropriate to the title.",
        ],
      },
      {
        heading: "Is 8GB RAM Enough for Everyday Use?",
        paragraphs: [
          "Yes. 8GB RAM is a practical amount for most smartphone users in 2026. It is suitable for multitasking across social media, browsers, messaging, streaming and productivity applications while giving the phone enough memory headroom for regular daily use.",
        ],
      },
      {
        heading: "6500mAh Battery with 45W Fast Charging",
        paragraphs: [
          "The 6500mAh battery is another standout feature of the TECNO Camon Air (8/128GB). A high-capacity battery is particularly useful for people who spend long hours browsing, watching videos, using mobile data, navigating or communicating throughout the day. The phone also supports 45W wired fast charging for quicker top-ups than standard charging solutions.",
          "Whether you are commuting, working outside, attending classes or simply using your phone heavily throughout the day, the large battery reduces the need to constantly search for a charger.",
        ],
      },
      {
        heading: "Premium Everyday Features",
        paragraphs: [
          "The TECNO Camon Air (8/128GB) goes beyond the basic smartphone essentials with features designed to improve everyday usability.",
          "Under-display optical fingerprint sensor: Provides convenient biometric unlocking.",
          "Stereo speakers: Deliver a more immersive audio experience than a typical single-speaker setup.",
          "Dolby Atmos: Enhances the compatible audio experience for supported content.",
          "NFC: Provides additional convenience for compatible contactless and connectivity functions.",
          "USB Type-C: Offers a modern charging and data-transfer connection.",
          "HiOS 16: TECNO's software interface built on Android 16.",
          "Infrared remote control: Adds practical remote-control functionality for compatible devices.",
        ],
      },
      {
        heading: "Who Should Buy TECNO Camon Air (8/128GB)?",
        paragraphs: [
          "This TECNO smartphone is a strong option for buyers who want a camera-focused phone with a high-quality display and long battery life. It is particularly suitable for:",
          "Students who need a reliable phone for classes, browsing and entertainment",
          "Professionals who regularly use communication and productivity apps",
          "Social media users who prioritise photography and selfies",
          "Content creators who want a capable smartphone camera setup",
          "Streaming fans who want a large AMOLED display",
          "Users who prefer long battery endurance",
          "Buyers looking for a feature-rich TECNO phone in Bangladesh",
        ],
      },
      {
        heading: "Is TECNO Camon Air (8/128GB) Good for Gaming?",
        paragraphs: [
          "The MediaTek Helio G200 Ultimate, 8GB RAM and 144Hz display provide a capable foundation for casual and mainstream mobile gaming. The high refresh rate can make supported games feel smoother, while the large battery is useful for longer sessions.",
          "For demanding 3D games, performance will depend on the game's optimisation and graphics settings. Users who prioritise competitive gaming should compare chipset and GPU performance with dedicated gaming-focused smartphones before buying.",
        ],
      },
      {
        heading: "Related Categories",
        paragraphs: [
          "Browse All Smartphones",
          "Explore Tecno Devices",
          "Shop Mobile Accessories",
          "Explore Power Banks",
          "Shop Headphones & Speakers",
        ],
      },
      {
        heading: "How much RAM and storage does TECNO Camon Air have?",
        paragraphs: [
          "The configuration covered here has 8GB RAM and 128GB internal storage, making it suitable for everyday multitasking, apps, photos, videos and general smartphone use.",
        ],
      },
      {
        heading: "Does TECNO Camon Air (8/128GB) have an AMOLED display?",
        paragraphs: [
          "Yes. The matching TECNO Camon 50 configuration features a 6.78-inch AMOLED display with a 144Hz refresh rate.",
        ],
      },
      {
        heading: "What camera does TECNO Camon Air (8/128GB) have?",
        paragraphs: [
          "The phone features a 50MP main camera with OIS and an 8MP ultra-wide camera on the rear, along with a 32MP front camera.",
        ],
      },
      {
        heading: "Does TECNO Camon Air support fast charging?",
        paragraphs: [
          "Yes. The matching Camon 50 configuration supports 45W wired fast charging and comes with a 6500mAh battery.",
        ],
      },
      {
        heading: "Is TECNO Camon Air good for everyday use?",
        paragraphs: [
          "Yes. With 8GB RAM, a MediaTek Helio G200 Ultimate processor, 128GB storage, a 144Hz AMOLED display and a large battery, it is designed as an all-round smartphone for communication, entertainment, photography, browsing and everyday productivity.",
        ],
      },
      {
        heading: "Does TECNO Camon Air support 5G?",
        paragraphs: [
          "The matching Camon 50 8GB/128GB specification is listed as a 4G smartphone, not a 5G model.",
        ],
      },
      {
        heading: "Does TECNO Camon Air have an under-display fingerprint sensor?",
        paragraphs: [
          "Yes. The matching configuration uses an under-display optical fingerprint sensor.",
        ],
      },
      {
        heading: "What operating system does TECNO Camon Air use?",
        paragraphs: [
          "The matching TECNO Camon 50 configuration runs HiOS 16 based on Android 16. Current listings also indicate support for up to three major Android upgrades.",
        ],
      },
      {
        heading: "Buying the TECNO Camon Air (8/128GB) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
