/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/tecno-spark-50-pro.jpeg";
import img2 from "@/images/brands/tecno-spark-50-pro-4gb-128gb.jpeg";
import img3 from "@/images/brands/tecno-spark-50-pro-8gb-128gb.jpeg";
import img4 from "@/images/products/tecno-spark-50-pro/04-tecno-spark-50-pro-blue.jpeg";

export const tecnoSpark50Pro: ProductDetail = {
  breadcrumb: [
    { label: "Phones", slug: "phone" },
    { label: "TECNO", slug: "tecno-mobile-phone" },
  ],
  gallery: [img1, img2, img3, img4],
  inStock: true,

  highlights: [
    "Display: 6.78'' HD+ Display, 120 Hz",
    "Processor: Mediatek Helio G100 Ultimate (6 nm)",
    "Camera: 50 MP + 8 MP",
    "Features: Side Fingerprint Sensor",
  ],

  colors: [
    { name: "Ink Black", hex: "#37373B", image: img2 },
    { name: "Titanium Grey", hex: "#ACADB4", image: img1 },
    { name: "Dynamic Orange", hex: "#DA6047", image: img3 },
    { name: "Midnight Blue", hex: "#40485D", image: img4 },
  ],

  emi: { months: 12, perMonth: 2250 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["Tecno"] },
        { label: "Model Name", value: ["SPARK 50 Pro"] },
      ],
    },
    {
      title: "Display",
      rows: [
        { label: "Size", value: ["6.78''"] },
        { label: "Type", value: ["HD+ Display"] },
        { label: "Resolution", value: ["720*1576"] },
        { label: "Refresh Rate", value: ["120Hz"] },
      ],
    },
    {
      title: "Processor",
      rows: [
        { label: "Chipset", value: ["Mediatek Helio G100 Ultimate (6 nm)"] },
        { label: "CPU Type", value: ["Octa-core (2x2.2 GHz Cortex-A76 & 6x2.0 GHz Cortex-A55)"] },
        { label: "GPU", value: ["Mali-G52 MC2"] },
      ],
    },
    {
      title: "Memory",
      rows: [
        { label: "RAM", value: ["6GB"] },
        { label: "ROM", value: ["128GB"] },
      ],
    },
    {
      title: "Rear Camera",
      rows: [
        { label: "Resolution", value: ["50MP+AI"] },
        { label: "Features", value: ["Single Flash"] },
      ],
    },
    {
      title: "Front Camera",
      rows: [
        { label: "Resolution", value: ["8MP"] },
        { label: "Features", value: ["Single Flash"] },
      ],
    },
    {
      title: "Audio",
      rows: [
        { label: "Speaker", value: ["Dual Speakers"] },
        { label: "Audio Features", value: ["DTS Sound"] },
      ],
    },
    {
      title: "Network & AMP; Connectivity",
      rows: [
        { label: "SIM", value: ["Nano-SIM + Nano-SIM"] },
        { label: "Wi-Fi", value: ["WIFI 2.4+5GHz"] },
        { label: "Bluetooth", value: ["BT 5.4"] },
        { label: "GPS", value: ["Yes"] },
        { label: "USB", value: ["USB Type-C"] },
        { label: "OTG", value: ["Yes"] },
      ],
    },
    {
      title: "OS",
      rows: [
        { label: "Operating System", value: ["Android 16, HIOS 16"] },
      ],
    },
    {
      title: "Features",
      rows: [
        { label: "Fingerprint", value: ["Side fingerprint Sensor"] },
        { label: "Sensors", value: ["Ambient light sensor", "Proximity sensor", "G-Sensor", "E-compass", "Virtual gyroscope"] },
      ],
    },
    {
      title: "Battery",
      rows: [
        { label: "Type", value: ["6000mAh"] },
        { label: "Fast Charging", value: ["60W Super Charging"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["167.8*79.2*7.8mm"] },
        { label: "Colors", value: ["Ink Black, Titanium Grey, Midnight Blue, Dynamic Orange"] },
      ],
    },
  ],

  description: {
    title: "Tecno SPARK 50 Pro (6/128GB)",
    blocks: [
      {
        paragraphs: [
          "The Tecno SPARK 50 Pro (6/128GB) is a stylish and feature-packed smartphone designed for users who want premium experiences without paying flagship prices. Featuring a stunning 120Hz IPS LCD display, powerful MediaTek Helio G100 processor, advanced AI camera system, and a long-lasting 6000mAh battery with fast charging, this smartphone delivers exceptional value for students, professionals, content creators, and mobile gamers in Bangladesh.",
          "Whether you're looking for a smartphone for social media, photography, streaming, gaming, or productivity, the Tecno SPARK 50 Pro offers a balanced combination of performance, design, and battery life that exceeds expectations in its price segment.",
        ],
      },
      {
        heading: "Premium 120Hz IPS LCD Display for Immersive Viewing",
        paragraphs: [
          "One of the biggest highlights of the Tecno SPARK 50 Pro is its large 6.78-inch IPS LCD display. The Full HD+ resolution delivers crisp visuals, vibrant colors, and deeper blacks, making everything from movies to social media content look more engaging.",
          "The 120Hz refresh rate ensures smoother scrolling, fluid animations, and responsive touch interactions. Whether you're browsing Facebook, watching YouTube, or playing games, the display offers a noticeably premium experience.",
        ],
      },
      {
        heading: "Benefits of the IPS LCD Screen",
        paragraphs: [
          "Rich color reproduction",
          "Enhanced outdoor visibility",
          "Smooth 120Hz performance",
          "Better multimedia experience",
          "Premium flagship-like viewing quality",
        ],
      },
      {
        heading: "Powerful Helio G100 Performance for Daily Multitasking",
        paragraphs: [
          "Powered by the MediaTek Helio G100 chipset, the Tecno SPARK 50 Pro is built to handle modern smartphone demands efficiently. From multitasking and social networking to gaming and content consumption, the device delivers reliable performance throughout the day.",
          "The combination of 6GB RAM and 128GB storage allows users to run multiple applications smoothly while storing photos, videos, documents, and apps without constantly worrying about space.",
        ],
      },
      {
        heading: "Ideal for Everyday Users",
        paragraphs: [
          "Social media browsing",
          "Online classes and meetings",
          "YouTube and Netflix streaming",
          "Casual and competitive gaming",
          "Photography and content creation",
        ],
      },
      {
        heading: "50MP AI Camera for Detailed Photography",
        paragraphs: [
          "Capture everyday moments with confidence using the advanced 50MP AI rear camera. The camera system is designed to produce detailed photos with improved color accuracy and enhanced dynamic range.",
          "AI-powered enhancements automatically optimize scenes, helping users take attractive photos without needing advanced photography skills.",
        ],
      },
      {
        heading: "Camera Features Users Love",
        paragraphs: [
          "High-resolution 50MP photography",
          "AI scene recognition",
          "Portrait photography modes",
          "Night photography optimization",
          "Social-media-ready images",
        ],
      },
      {
        heading: "8MP Selfie Camera for Content Creators",
        paragraphs: [
          "The front-facing 8MP camera delivers clear selfies and smooth video calling experiences. Whether you're creating content for TikTok, Facebook, Instagram, or attending virtual meetings, the camera helps you stay connected with confidence.",
        ],
      },
      {
        heading: "6000mAh Battery with 60W Fast Charging",
        paragraphs: [
          "Battery anxiety becomes a thing of the past thanks to the large 6000mAh battery. Designed to keep up with busy lifestyles, the Tecno SPARK 50 Pro easily powers through a full day of usage.",
          "When it's time to recharge, the 60W fast charging technology helps reduce downtime, allowing you to get back to work, entertainment, or gaming quickly.",
        ],
      },
      {
        heading: "Real-Life Battery Benefits",
        paragraphs: [
          "All-day usage on a single charge",
          "Extended video streaming sessions",
          "Long gaming hours",
          "Fast charging convenience",
          "Reliable travel companion",
        ],
      },
      {
        heading: "Elegant Design with Premium Feel",
        paragraphs: [
          "Tecno has designed the SPARK 50 Pro to stand out. Its slim profile, modern camera module, and refined finish provide a premium look that rivals many higher-priced smartphones.",
          "The ergonomic design ensures comfortable one-handed use while maintaining a stylish appearance suitable for students, professionals, and trend-conscious users.",
        ],
      },
      {
        heading: "Why Buy Tecno SPARK 50 Pro (6/128GB) in Bangladesh?",
        paragraphs: [
          "If you're searching for the best smartphone under a competitive budget in Bangladesh, the Tecno SPARK 50 Pro is an excellent choice. It combines premium display technology, reliable performance, long battery life, and capable cameras into one attractive package.",
          "Compared to many smartphones in the same category, it delivers a flagship-inspired experience with modern features that matter most to everyday users.",
        ],
      },
      {
        heading: "Who Should Buy the Tecno SPARK 50 Pro?",
        paragraphs: [
          "Students looking for a reliable smartphone",
          "Professionals needing all-day battery life",
          "Content creators on a budget",
          "Mobile gamers seeking smooth performance",
          "Users upgrading from older Android devices",
        ],
      },
      {
        heading: "Is the Tecno SPARK 50 Pro good for gaming?",
        paragraphs: [
          "Yes. The MediaTek Helio G100 processor, 120Hz IPS LCD display, and ample RAM provide smooth gaming performance for popular mobile games.",
        ],
      },
      {
        heading: "Does the Tecno SPARK 50 Pro support fast charging?",
        paragraphs: [
          "Yes. The smartphone supports 60W fast charging technology for quicker battery top-ups.",
        ],
      },
      {
        heading: "How much storage does the Tecno SPARK 50 Pro offer?",
        paragraphs: [
          "This variant comes with 128GB internal storage and 6GB RAM, offering sufficient space for apps, photos, videos, and files.",
        ],
      },
      {
        heading: "Is the AMOLED display better than LCD?",
        paragraphs: [
          "Yes. AMOLED displays typically provide richer colors, deeper blacks, better contrast, and a more premium viewing experience compared to traditional LCD panels.",
        ],
      },
      {
        heading: "Is the Tecno SPARK 50 Pro worth buying in Bangladesh?",
        paragraphs: [
          "Absolutely. It offers an excellent balance of display quality, battery life, performance, design, and camera capabilities, making it one of the best value-for-money smartphones in its category.",
        ],
      },
      {
        heading: "Internal Linking Opportunities",
        paragraphs: [
          "Tecno Smartphones",
          "Shop All Smartphones",
          "Mobile Accessories Collection",
          "Power Banks",
          "Protective Phone Cases",
          "Fast Chargers & Adapters",
        ],
      },
      {
        heading: "Buying the Tecno SPARK 50 Pro (6/128GB) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
