/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/tecno-watch-3-active-smart-watch.jpeg";
import img2 from "@/images/products/tecno-watch-3-active-smart-watch/02-tecno-watch-3-active-smart-watch-1-1780986150324.jpeg";
import img3 from "@/images/products/tecno-watch-3-active-smart-watch/03-tecno-watch-3-active-smart-watch-2-1780986149539.jpeg";
import img4 from "@/images/products/tecno-watch-3-active-smart-watch/04-tecno-watch-3-active-smart-watch-3-1780986148702.jpeg";

export const tecnoWatch3ActiveSmartWatch: ProductDetail = {
  breadcrumb: ["Watches", "Smart Watch", "Tecno"],
  gallery: [img1, img2, img3, img4],
  inStock: true,

  highlights: [
    "Display: 2.02\" IPS HD Large Screen, AI Voice Assistant",
    "Bluetooth Calling, Up to 12 Days of Battery Life",
    "Heart Rate Tracking, Blood Oxygen Level Tracking",
    "High-Density Metal Watch Case & Ultra-Hard Glass",
  ],

  colors: [
    { name: "Black", hex: "#000000", image: img1 },
  ],

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["TECNO"] },
        { label: "Model Name", value: ["Watch 3"] },
      ],
    },
    {
      title: "Main Features",
      rows: [
        { label: "Sensors", value: ["Accelerometer, gyro, heart rate, blood gxygen, SpO2"] },
        { label: "Battery", value: ["Non-removable Li-Ion Battery"] },
        { label: "Battery Life", value: ["Up to 12Days of Battery Life"] },
        { label: "Special Features", value: ["Enhanced bluetooth call", "150+ watch faces", "100+ exercise modes", "AI voice assistant", "Built-in Mini Games"] },
      ],
    },
    {
      title: "Display",
      rows: [
        { label: "Dial Shape", value: ["Square"] },
        { label: "Dial Size", value: ["2.02\""] },
        { label: "Technology", value: ["IPS HD"] },
      ],
    },
    {
      title: "Connectivity",
      rows: [
        { label: "Bluetooth", value: ["5.3"] },
      ],
    },
    {
      title: "Physical Dimension",
      rows: [
        { label: "Material", value: ["High-Density Metal Watch Case", "Ultra-Hard Glass", "Rotating Crown"] },
        { label: "Color", value: ["Black"] },
      ],
    },
  ],

  description: {
    title: "TECNO Watch 3 Active Smart Watch",
    blocks: [
      {
        paragraphs: [
          "The TECNO Watch 3 Active Smart Watch is designed for users who want a stylish, feature-packed smartwatch at an affordable price. With a large IPS HD display, Bluetooth calling, advanced health tracking, and up to 12 days of battery life, this smartwatch is perfect for everyday fitness, work, and entertainment.",
        ],
      },
      {
        heading: "Large 2.02\" IPS HD Display for Clear Viewing",
        paragraphs: [
          "Enjoy a bigger and brighter screen with the 2.02-inch IPS HD large display. The square dial design gives it a modern and premium look, while the ultra-hard glass ensures durability against scratches and daily wear. Whether you are checking notifications, tracking workouts, or answering calls, the high-resolution screen delivers sharp visuals and smooth touch responsiveness. The rotating crown adds a classic touch while making navigation easier and more intuitive.",
        ],
      },
      {
        heading: "Enhanced Bluetooth Calling with AI Voice Assistant",
        paragraphs: [
          "Stay connected directly from your wrist with enhanced Bluetooth calling powered by Bluetooth 5.3. Make and receive calls without taking your phone out of your pocket. The stable connection ensures clear voice quality and smooth performance. With the built-in AI voice assistant, you can control functions, check information, or manage tasks using simple voice commands. It makes daily activities more convenient and hands-free.",
        ],
      },
      {
        heading: "Advanced Health Monitoring Features",
        paragraphs: [
          "The TECNO Watch 3 Active Smart Watch comes equipped with essential health sensors, including a heart rate monitor, blood oxygen (SpO2) tracker, accelerometer, and gyro sensor. Monitor your heart rate in real-time and keep track of your blood oxygen level to stay informed about your overall wellness. These smart health features make it an excellent choice for fitness enthusiasts and health-conscious users looking for a reliable smartwatch in Bangladesh.",
        ],
      },
      {
        heading: "100+ Exercise Modes for Active Lifestyles",
        paragraphs: [
          "Whether you love running, cycling, walking, or gym workouts, this smartwatch supports over 100 exercise modes. It accurately records your activity data, helping you analyze performance and improve your fitness goals. The built-in mini games also add a fun element, making it more than just a fitness tracker. It is a complete smart companion for both productivity and entertainment.",
        ],
      },
      {
        heading: "Premium Build with High-Density Metal Case",
        paragraphs: [
          "Crafted with a high-density metal watch case and protected by ultra-hard glass, this smartwatch combines durability with elegance. The square dial and premium finishing make it suitable for both casual and formal occasions. With over 150+ watch faces available, you can easily customize the look of your smartwatch to match your outfit or mood.",
        ],
      },
      {
        heading: "Up to 12 Days of Battery Life",
        paragraphs: [
          "Powered by a non-removable Li-Ion battery, the TECNO Watch 3 Active offers up to 12 days of battery life on a single charge. You do not have to worry about charging it every day. This long battery backup makes it perfect for travel, busy work schedules, and extended outdoor activities.",
        ],
      },
      {
        heading: "Buying the TECNO Watch 3 Active Smart Watch from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
