/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/torras-install-master-screen-protector-for-galaxy-s26-ultra.jpeg";
import img2 from "@/images/products/torras-install-master-screen-protector-for-galaxy-s26-ultra/02-torras-install-master-screen-protectors-for-galaxy-s26-1.jpeg";
import img3 from "@/images/products/torras-install-master-screen-protector-for-galaxy-s26-ultra/03-torras-install-master-screen-protectors-for-galaxy-s26-3.jpeg";
import img4 from "@/images/products/torras-install-master-screen-protector-for-galaxy-s26-ultra/04-torras-install-master-screen-protectors-for-galaxy-s26-2.jpeg";

export const torrasInstallMasterScreenProtectorForGalaxyS26Ultra: ProductDetail = {
  breadcrumb: [
    { label: "Cases & Protectors", slug: "cases-screen-protectors" },
    { label: "Samsung", slug: "samsung-cases-accessories" },
    { label: "Galaxy S26 Ultra", slug: "galaxy-s26-ultra-cases-screen-protectors" },
  ],
  gallery: [img1, img2, img3, img4],
  inStock: true,

  highlights: [
    "Compatible Devices: Galaxy S26 Ultra",
    "Type: Screen Protectors",
    "Display quality with HD clear transparency",
    "Installation and long-lasting durability",
  ],

  colors: [
    { name: "Clear", hex: "#CDCCCD", image: img1 },
  ],

  specs: [
    {
      title: "Product Specifications",
      rows: [
        { label: "Compatible Devices", value: ["Galaxy S26 Ultra"] },
        { label: "Type", value: ["Screen Protectors"] },
      ],
    },
  ],

  description: {
    title: "TORRAS Install Master Screen Protector for Galaxy S26 Ultra",
    blocks: [
      {
        paragraphs: [
          "Keep your display crystal clear and fully protected with the TORRAS Install Master Screen Protector for Galaxy S26 Ultra, designed for effortless installation and long-lasting durability. This premium screen protector combines advanced protection with a bubble-free application system, making it perfect for users who want a flawless finish without hassle.",
        ],
      },
      {
        heading: "Perfect Fit for Galaxy S26 Ultra Display",
        paragraphs: [
          "Engineered specifically for the Galaxy S26 Ultra, this screen protector offers precise edge-to-edge coverage while maintaining compatibility with cases. It ensures full touch sensitivity and a smooth user experience without affecting display clarity.",
        ],
      },
      {
        heading: "Easy Install Master Technology",
        paragraphs: [
          "The highlight of this protector is its Install Master technology, allowing quick and accurate application. Even if you’re not experienced, you can achieve a perfectly aligned, bubble-free installation in seconds.",
        ],
      },
      {
        heading: "High-Definition Clarity & Touch Sensitivity",
        paragraphs: [
          "Enjoy your phone’s original display quality with HD clear transparency. This screen protector preserves brightness, colors, and responsiveness, ensuring a seamless viewing and gaming experience. Made from durable tempered glass, it provides reliable protection against scratches, drops, and daily wear. It acts as a shield against keys, dust, and accidental impacts, keeping your Galaxy S26 Ultra screen safe.",
        ],
      },
      {
        heading: "Buying the TORRAS Install Master Screen Protector for Galaxy S26 Ultra from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
