/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/tp-link-archer-ax73-dual-band-gigabit-router.jpeg";
import img2 from "@/images/products/tp-link-archer-ax73-dual-band-gigabit-router/02-tp-link-archer-ax73-dual-band-gigabit-router.jpg-1582.jpeg";
import img3 from "@/images/products/tp-link-archer-ax73-dual-band-gigabit-router/03-tp-link-archer-ax73-dual-band-gigabit-router.jpg-2854.jpeg";
import img4 from "@/images/products/tp-link-archer-ax73-dual-band-gigabit-router/04-tp-link-archer-ax73-dual-band-gigabit-router.jpg-3780.jpeg";

export const tpLinkArcherAx73DualBandGigabitRouter: ProductDetail = {
  breadcrumb: ["Networking", "Router", "Tp-Link"],
  gallery: [img1, img2, img3, img4],
  inStock: true,

  highlights: [
    "Est Range/SqF: Up to 3000 square feet",
    "Supports 4x4 MU-MIMO and OFDMA",
    "6x high-performance antennas",
    "Wi-Fi Standard: Wi-Fi 6",
  ],

  colors: [
    { name: "Black", hex: "#000000", image: img1 },
  ],

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["TP-Link"] },
        { label: "Model Name", value: ["Archer AX73 AX5400"] },
      ],
    },
    {
      title: "Main Features",
      rows: [
        { label: "Data Rate", value: ["AX5400", "5 GHz: 4804 Mbps (802.11ax, HE160)", "2.4 GHz: 574 Mbps (802.11ax)"] },
        { label: "Antenna", value: ["6× Fixed High-Performance Antennas"] },
        { label: "Button", value: ["Wi-Fi On/Off Button", "Power On/Off Button", "LED On/Off Button", "WPS Button", "Reset Button"] },
        { label: "Frequency", value: ["2.4GHz and 5GHz"] },
        { label: "Network Standard", value: ["Wi-Fi 6", "IEEE 802.11ax/ac/n/a 5 GHz", "IEEE 802.11ax/n/b/g 2.4 GHz"] },
        { label: "Interface", value: ["1× USB 3.0 Port"] },
        { label: "Encryption", value: ["WPA", "WPA2", "WPA3", "WPA/WPA2-Enterprise (802.1x)"] },
        { label: "Ports", value: ["1× Gigabit WAN Port", "4× Gigabit LAN Ports", "Static Link Aggregation (LAG) available with 2× LAN ports"] },
        { label: "Operating System Support", value: ["Internet Explorer 11+, Firefox 12.0+, Chrome 20.0+, Safari 4.0+, or other JavaScript-enabled browser", "Cable or DSL Modem (if needed)", "Subscription with an internet service provider (for internet access)"] },
        { label: "Others", value: ["Network Security:", "SPI Firewall", "Access Control", "IP & MAC Binding", "Application Layer Gateway", "HomeShield Security:", "Real-Time IoT Protection", "Malicious Site Blocker", "Intrusion Prevention System", "DDoS Attack Prevention", "Home Network Scanner"] },
      ],
    },
    {
      title: "Power Source",
      rows: [
        { label: "Power Mode", value: ["12 V ⎓ 2.5 A"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["10.7 × 5.8 × 1.9 in", "(272.5 × 147.2 × 49.2 mm)"] },
        { label: "Color", value: ["Black"] },
      ],
    },
  ],

  description: {
    title: "TP-Link Archer AX73 AX5400 Dual-Band Gigabit Wi-Fi Router",
    blocks: [
      {
        paragraphs: [
          "Experience ultra-fast, reliable, and secure connectivity with the TP-Link Archer AX73 AX5400 Dual-Band Gigabit Wi-Fi Router. Designed for modern homes and high-demand users, this router delivers next-generation Wi-Fi 6 performance, ensuring smooth streaming, lag-free gaming, and fast downloads across all your devices. The TP-Link Archer AX73 offers blazing-fast speeds up to 5400 Mbps, combining 4804 Mbps on the 5GHz band and 574 Mbps on the 2.4GHz band. This means you can enjoy 4K streaming, online gaming, and heavy file transfers simultaneously without slowdowns. Powered by Wi-Fi 6 technology, it ensures better efficiency and reduced latency for all connected devices.",
        ],
      },
      {
        heading: "Key Features of TP-Link Archer AX73 Dual-Band Gigabit Router",
        paragraphs: [
          "Equipped with six high-performance antennas, beamforming, and OFDMA technology, the Archer AX73 provides strong, stable Wi-Fi coverage for every corner of your home. Whether you’re in the living room, bedroom, or backyard, experience seamless connectivity with consistent signal strength.",
        ],
      },
      {
        heading: "Powerful Gigabit Connections",
        paragraphs: [
          "Take advantage of full Gigabit ports for wired connections that maximize speed for smart TVs, gaming consoles, and PCs. Perfect for households with multiple users, this router handles demanding bandwidth needs effortlessly, making it ideal for smart homes and heavy internet usage. Keep your network safe with TP-Link HomeShield, offering advanced protection against cyber threats, parental controls, and real-time network monitoring. You can easily manage everything through the intuitive TP-Link Tether app.",
        ],
      },
      {
        heading: "Buying the TP-Link Archer AX73 AX5400 Dual-Band Gigabit Wi-Fi Router from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
