/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/tp-link-deco-s7-router-3-pack.jpeg";
import img2 from "@/images/products/tp-link-deco-s7-router-3-pack/02-tp-link-deco-s7-router-3-pack-new.jpg-1759.jpeg";
import img3 from "@/images/products/tp-link-deco-s7-router-3-pack/03-tp-link-deco-s7-router-3-pack-new.jpg-2236.jpeg";
import img4 from "@/images/products/tp-link-deco-s7-router-3-pack/04-tp-link-deco-x7-router-3-pack.jpg-3897.jpeg";

export const tpLinkDecoS7Router3Pack: ProductDetail = {
  breadcrumb: [
    { label: "Networking", slug: "networking" },
    { label: "Router", slug: "router" },
    { label: "Tp-Link", slug: "tp-link-router" },
  ],
  gallery: [img1, img2, img3, img4],
  inStock: true,

  highlights: [
    "Est Range/SqF: Up to 6000 square feet",
    "Frequency: Dual-Band (2.4GHz & 5GHz)",
    "WiFi Speeds: Up to 1900 Mbps, TP-Link Mesh Technology",
    "Wi-Fi Standard: Wi-Fi 5",
  ],

  colors: [
    { name: "White", hex: "#ffffff", image: img1 },
  ],

  specs: [
    {
      title: "Main Features",
      rows: [
        { label: "Data Rate", value: ["5 GHz: 1300 Mbps (802.11ac)", "2.4 GHz: 600 Mbps (802.11n)"] },
        { label: "Antenna", value: ["3× Antennas (Internal)"] },
        { label: "Button", value: ["Reset Button"] },
        { label: "Frequency", value: ["Dual Band (2.4GHz & 5GHz)"] },
        { label: "Network Standard", value: ["IEEE 802.11ac/n/a 5 GHz", "IEEE 802.11n/b/g 2.4 GHz"] },
        { label: "Interface", value: ["3× Gigabit Ports"] },
        { label: "Encryption", value: ["SPI Firewall", "Access Control", "WPA-Personal", "WPA2-Personal"] },
        { label: "Others", value: ["TP-Link Mesh Technology", "Beamforming", "MU-MIMO", "Working Modes:", "Router Mode", "Access Point Mode"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["6.4 × 3.6 × 3.6 in", "(162.3 × 90.7 × 90.7 mm)"] },
        { label: "Color", value: ["White"] },
      ],
    },
  ],

  description: {
    title: "TP-Link Deco S7 Mesh Router (3 Pack)",
    blocks: [
      {
        paragraphs: [
          "With the TP-Link Deco S7 Mesh Router (3 Pack) experience next-level Wi-Fi coverage and performance — a powerful whole-home mesh system built to eliminate dead zones and deliver lightning-fast internet throughout your home. Whether you’re streaming 8K videos, gaming online, or managing smart home devices, the Deco S7 ensures seamless connectivity in every corner.",
        ],
      },
      {
        heading: "Key Features of TP-Link Deco S7 Mesh Router",
        paragraphs: [
          "With three high-performance units working together, the Deco S7 Mesh System creates a unified network that covers up to 7,000 square feet. Forget buffering and signal drops — Deco’s intelligent mesh technology automatically connects your devices to the strongest node, ensuring uninterrupted Wi-Fi no matter where you are. Powered by the latest Wi-Fi 6 technology, the TP-Link Deco S7 delivers faster speeds, greater efficiency, and reduced network congestion. Enjoy up to 5400 Mbps combined speed, perfect for demanding online activities like 4K streaming, video calls, and gaming across multiple devices simultaneously. The advanced OFDMA and MU-MIMO features allow more devices to connect without slowing down your network.",
        ],
      },
      {
        heading: "Smart and Secure Networking",
        paragraphs: [
          "The Deco S7 Mesh Router ensures top-tier protection with TP-Link HomeShield, offering enhanced security features to safeguard your network and devices from cyber threats. It also includes robust parental controls, letting you manage online time and filter content for safer browsing. Setting up the Deco S7 is quick and easy with the TP-Link Deco app. Simply follow the step-by-step instructions to get your system running in minutes. You can monitor connected devices, run speed tests, and manage your home network remotely — all from your smartphone.With its sleek and modern aesthetic, the Deco S7 Mesh Router (3 Pack) blends beautifully into any home decor. Compact yet powerful, it’s designed to perform as good as it looks.",
        ],
      },
      {
        heading: "Buying the TP-Link Deco S7 AC1900 Dual Band Mesh Router (3-Pack) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
