/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/products/uag-exclusive-pathfinder-magsafe-case-for-iphone-17-pro.jpeg";
import img2 from "@/images/products/uag-exclusive-pathfinder-magsafe-case-for-iphone-17-pro/02-uag-exclusive-pathfinder-magsafe-case-for-iphone-17-pro-1782.jpeg";
import img3 from "@/images/products/uag-exclusive-pathfinder-magsafe-case-for-iphone-17-pro/03-uag-exclusive-pathfinder-magsafe-case-for-iphone-17-pro-2504.jpeg";
import img4 from "@/images/products/uag-exclusive-pathfinder-magsafe-case-for-iphone-17-pro/04-uag-exclusive-pathfinder-magsafe-case-for-iphone-17-pro-3982.jpeg";

export const uagExclusivePathfinderMagsafeCaseForIphone17Pro: ProductDetail = {
  breadcrumb: ["Cases & Protectors", "Apple", "iPhone 17 Pro"],
  gallery: [img1, img2, img3, img4],
  inStock: true,

  highlights: [
    "Featherlight and Durable",
    "Enhanced Impact Resistance",
    "Lanyard Anchor Points",
    "18 ft. Drop Protection",
  ],

  colors: [
    { name: "Orange", hex: "#FF5E00", image: img1 },
  ],

  emi: { months: 3, perMonth: 2333 },

  specs: [
    {
      title: "Product Specifications",
      rows: [
        { label: "Compatible Devices", value: ["iPhone 17 Pro"] },
        { label: "Color", value: ["Orange"] },
        { label: "MagSafe Compatibility", value: ["Yes"] },
        { label: "Special Feature", value: ["Featherlight and Durable.", "Enhanced Impact Resistance.", "Lanyard Anchor Points.", "18 ft. Drop Protection.", "MagSafe Compatible.", "Eco-Friendly Construction."] },
        { label: "Dimensions", value: ["Length-6.15 in", "Width-3.07 in", "Depth-0.65 in"] },
        { label: "Weight", value: ["0.09 lb"] },
      ],
    },
  ],

  description: {
    title: "UAG Exclusive Pathfinder MagSafe Case for iPhone 17 Pro",
    blocks: [
      {
        paragraphs: [
          "UAG Exclusive Pathfinder MagSafe Case for iPhone 17 Pro is built for users who demand serious protection without adding bulk. With a rugged yet modern design, this exclusive Pathfinder case delivers dependable defense, MagSafe convenience, and a lightweight feel that’s perfect for everyday use.",
        ],
      },
      {
        heading: "Key Features of UAG Exclusive Pathfinder MagSafe Case",
        paragraphs: [
          "The UAG Exclusive Pathfinder MagSafe Case for iPhone 17 Pro is engineered to be featherlight while remaining incredibly durable. Its advanced construction keeps your iPhone protected without weighing it down, making it ideal for long days, frequent travel, and one-handed use. The slim profile fits comfortably in your pocket while maintaining UAG’s signature tough look. Designed to exceed everyday protection needs, this case offers enhanced impact resistance with up to 18 feet of drop protection. It effectively absorbs shock from accidental drops and impacts, helping protect your iPhone 17 Pro from damage during daily use. Whether you’re commuting or exploring outdoors, this case is built to handle it all. Enjoy fast, reliable charging with full MagSafe compatibility. The UAG Exclusive Pathfinder MagSafe Case for iPhone 17 Pro ensures strong magnetic alignment with MagSafe chargers and accessories, so you don’t have to remove the case to power up. It’s designed to work smoothly with your MagSafe ecosystem for added convenience. Integrated lanyard anchor points give you more control over how you carry your phone. Attach a wrist strap or lanyard to keep your iPhone 17 Pro secure and easily accessible, especially during travel, outdoor activities, or busy workdays. This case is crafted with eco-friendly materials, combining strong protection with a more responsible approach to design. You get premium durability while supporting a product made with sustainability in mind, without compromising performance or style.",
        ],
      },
      {
        heading: "Buying the UAG Exclusive Pathfinder MagSafe Case for iPhone 17 Pro from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
