/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/vivo-y31d-4gb-128gb.jpeg";
import img2 from "@/images/products/vivo-y31d-4gb-128gb/02-vivo-y31d-8gb-128gb-6.jpeg";
import img3 from "@/images/products/vivo-y31d-4gb-128gb/03-vivo-y31d-8gb-128gb-7.jpeg";
import img4 from "@/images/products/vivo-y31d-4gb-128gb/04-vivo-y31d-8gb-128gb-8.jpeg";
import img5 from "@/images/products/vivo-y31d-4gb-128gb/05-vivo-y31d-8gb-128gb-9.jpeg";

export const vivoY31d4gb128gb: ProductDetail = {
  breadcrumb: [
    { label: "Phones", slug: "phone" },
    { label: "Vivo", slug: "vivo" },
  ],
  gallery: [img1, img2, img3, img4, img5],
  inStock: true,

  highlights: [
    "Display: 6.75 inches LCD",
    "Processor : Snapdragon 6s Gen 2 4G Mobile Platform",
    "Camera : 50 MP + 2 MP + 8 MP",
    "Features: Side-mounted capacitive fingerprint sensor",
  ],

  colors: [
    { name: "Red", hex: "#FF0000", image: img1 },
  ],

  emi: { months: 12, perMonth: 2292 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["Vivo"] },
        { label: "Model Name", value: ["Y31d"] },
      ],
    },
    {
      title: "Display",
      rows: [
        { label: "Size", value: ["6.75 inches"] },
        { label: "Type", value: ["LCD"] },
        { label: "Resolution", value: ["1570 × 720"] },
        { label: "Refresh Rate", value: ["Up to 120 Hz"] },
        { label: "Brightness", value: ["1235 nits"] },
        { label: "Features", value: ["Color Gamut: 83% NTSC", "Pixel Density: 256 PPI", "Light-Emitting Material: LED", "Touch Screen: Capacitive multi-touch"] },
      ],
    },
    {
      title: "Processor",
      rows: [
        { label: "Chipset", value: ["Snapdragon 6s Gen 2 4G Mobile Platform"] },
        { label: "CPU Speed", value: ["CPU Clock Speed: 4 × 2.9 GHz + 4 × 1.9 GHz"] },
      ],
    },
    {
      title: "Memory",
      rows: [
        { label: "RAM", value: ["4GB"] },
        { label: "ROM", value: ["128GB"] },
      ],
    },
    {
      title: "Rear Camera",
      rows: [
        { label: "Resolution", value: ["50 MP + 2 MP"] },
        { label: "Features", value: ["f/2.0 (50 MP) + f/2.4 (2 MP), Rear flash, Photo, Night, Portrait, Video, Live Photo, Slo-mo, Time-lapse, Pro, Pano, Documents, 50 MP, Dual View, Underwater Photography"] },
      ],
    },
    {
      title: "Front Camera",
      rows: [
        { label: "Resolution", value: ["8 MP"] },
        { label: "Features", value: ["f/2.05 (8 MP), Photo, Night, Portrait, Video, Live Photo, Dual View"] },
      ],
    },
    {
      title: "Audio",
      rows: [
        { label: "Audio Features", value: ["AAC, WAV, MP3, MIDI, VORBIS, APE, FLAC"] },
      ],
    },
    {
      title: "Network & Connectivity",
      rows: [
        { label: "SIM", value: ["2 nano SIMs, Dual SIM Dual Standby (DSDS)"] },
        { label: "Network", value: ["2G GSM, 3G WCDMA, 4G TD-LTE, 4G FDD-LTE"] },
        { label: "Wi-Fi", value: ["2.4 GHz / 5 GHz"] },
        { label: "Bluetooth", value: ["Bluetooth 5.1"] },
        { label: "GPS", value: ["Supported"] },
        { label: "USB", value: ["USB 2.0"] },
        { label: "OTG", value: ["Supported"] },
      ],
    },
    {
      title: "OS",
      rows: [
        { label: "Operating System", value: ["OriginOS 6 Android 16"] },
      ],
    },
    {
      title: "Features",
      rows: [
        { label: "Fingerprint", value: ["Side-mounted capacitive fingerprint sensor"] },
        { label: "Sensors", value: ["Accelerometer", "Ambient Light Sensor", "E-compass", "Proximity Sensor", "Motor", "Gyroscope", "Infrared blaster"] },
        { label: "IP Rating", value: ["IP68 & IP69"] },
      ],
    },
    {
      title: "Battery",
      rows: [
        { label: "Type", value: ["Li-ion battery (7200 mAh (TYP))"] },
        { label: "Fast Charging", value: ["44W"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["166.64 × 78.43 × 8.39 mm (Red)"] },
        { label: "Weight", value: ["219g"] },
        { label: "Body Material", value: ["Back Cover Material: Composite plastic sheet"] },
        { label: "Colors", value: ["Red"] },
      ],
    },
  ],

  description: {
    title: "Vivo Y31d (4/128GB)",
    blocks: [
      {
        paragraphs: [
          "The Vivo Y31d (4/128GB) is a practical and budget-friendly smartphone built for users in Bangladesh who need dependable performance, long battery life, and ample storage. Designed for everyday use, it delivers smooth multitasking, a large immersive display, and efficient power management—making it ideal for students, professionals, and first-time smartphone users. If you're looking for a value-for-money smartphone that handles daily tasks effortlessly, the Vivo Y31d is a smart choice.",
        ],
      },
      {
        heading: "Why Choose Vivo Y31d (4/128GB) in Bangladesh?",
        paragraphs: [
          "Many budget smartphone users face common problems like slow performance, limited storage, and frequent charging. The Vivo Y31d (4/128GB) addresses these issues with optimized software, sufficient RAM, and a battery designed for all-day use. It’s a well-balanced device for communication, entertainment, and productivity.",
        ],
      },
      {
        heading: "4GB RAM for Smooth Multitasking",
        paragraphs: [
          "Switch between apps like Facebook, YouTube, WhatsApp, and browsing without noticeable lag. The 4GB RAM ensures stable everyday performance.",
        ],
      },
      {
        heading: "128GB Storage for More Space",
        paragraphs: [
          "Store your photos, videos, apps, and documents without worrying about running out of space. Ideal for users who need long-term storage flexibility.",
        ],
      },
      {
        heading: "Large Display for Better Viewing",
        paragraphs: [
          "Enjoy watching videos, scrolling social media, and reading on a spacious screen designed for comfortable viewing.",
        ],
      },
      {
        heading: "Long-Lasting Battery Life",
        paragraphs: [
          "Stay connected throughout the day without frequent charging. Perfect for heavy users who rely on their phone for work and entertainment.",
        ],
      },
      {
        heading: "AI Camera for Daily Photography",
        paragraphs: [
          "Capture clear photos and videos for social media, video calls, and everyday moments with optimized camera features.",
        ],
      },
      {
        heading: "Sleek & Comfortable Design",
        paragraphs: [
          "The lightweight and modern design makes it easy to carry and comfortable to use all day.",
        ],
      },
      {
        heading: "For Students",
        paragraphs: [
          "Attend online classes, browse educational content, and stay connected with friends without performance issues.",
        ],
      },
      {
        heading: "For Social Media & Entertainment",
        paragraphs: [
          "Watch YouTube, scroll Facebook, and enjoy TikTok with smooth performance and a large display.",
        ],
      },
      {
        heading: "For Office & Business Use",
        paragraphs: [
          "Handle emails, calls, and basic productivity tasks efficiently throughout the day.",
        ],
      },
      {
        heading: "For Everyday Communication",
        paragraphs: [
          "Make calls, send messages, and use apps like WhatsApp and Messenger without interruptions.",
        ],
      },
      {
        heading: "Vivo Y31d vs Other Budget Smartphones",
        paragraphs: [
          "Compared to many entry-level smartphones in Bangladesh, the Vivo Y31d (4/128GB) offers a better balance of storage and battery life. While some alternatives provide only 64GB storage, this model ensures more space for long-term use. Its optimized system also delivers smoother performance for daily tasks.",
        ],
      },
      {
        heading: "Buying Guide: Should You Buy Vivo Y31d?",
        paragraphs: [
          "The Vivo Y31d is a great choice if you need:",
          "A budget smartphone with reliable daily performance",
          "Large 128GB storage for apps and media",
          "Long battery life for all-day usage",
          "A big display for entertainment and browsing",
          "If your priority is value, reliability, and usability, this smartphone is worth considering.",
        ],
      },
      {
        heading: "Related Products",
        paragraphs: [
          "Explore More Vivo Products",
          "Browse All Smartphones",
          "Shop Mobile Accessories",
          "Cases & Protectors",
        ],
      },
      {
        heading: "Is Vivo Y31d good for daily use?",
        paragraphs: [
          "Yes, it is designed for smooth everyday usage including calls, browsing, and social media.",
        ],
      },
      {
        heading: "Is 128GB storage enough for long-term use?",
        paragraphs: [
          "Yes, it provides ample space for most users to store apps, photos, and videos.",
        ],
      },
      {
        heading: "How long does the battery last?",
        paragraphs: [
          "The battery is optimized for all-day use depending on your usage pattern.",
        ],
      },
      {
        heading: "Who should buy Vivo Y31d?",
        paragraphs: [
          "It’s ideal for students, first-time smartphone users, and anyone looking for a reliable budget smartphone in Bangladesh.",
        ],
      },
      {
        heading: "Buying the Vivo Y31d (4/128GB) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
