/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/vivo-v70-fe-5g-12gb-256gb.jpeg";
import img2 from "@/images/products/vivo-v70-fe-5g-12gb-256gb/02-vivo-v70-fe-5g-purple.jpeg";

export const vivoV70Fe5g12gb256gb: ProductDetail = {
  breadcrumb: [
    { label: "Phones", slug: "phone" },
    { label: "Vivo", slug: "vivo" },
  ],
  gallery: [img1, img2],
  inStock: true,

  highlights: [
    "Display: 6.83 inches AMOLED",
    "Processor: Mediatek Dimensity 7360-Turbo",
    "Camera: 200 MP + 8 MP + 32 MP",
    "Features: Fingerprint (under display, optical)",
  ],

  colors: [
    { name: "Blue", hex: "#035BBC", image: img1 },
    { name: "Purple", hex: "#800080", image: img2 },
  ],

  emi: { months: 12, perMonth: 5250 },

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["Vivo"] },
        { label: "Model Name", value: ["V70 FE"] },
      ],
    },
    {
      title: "Display",
      rows: [
        { label: "Size", value: ["6.83″ (17.35 cm)"] },
        { label: "Type", value: ["AMOLED"] },
        { label: "Resolution", value: ["2800 × 1260"] },
      ],
    },
    {
      title: "Processor",
      rows: [
        { label: "Chipset", value: ["Mediatek Dimensity 7360-Turbo"] },
        { label: "CPU Type", value: ["Octa-core (4x2.5 GHz Cortex-A78 & 4x2.0 GHz Cortex-A55)"] },
        { label: "CPU Speed", value: ["4×2.5GHz+4×2.0GHz"] },
        { label: "GPU", value: ["Mali-G615 MC2"] },
      ],
    },
    {
      title: "Memory",
      rows: [
        { label: "RAM", value: ["12GB"] },
        { label: "ROM", value: ["256GB"] },
      ],
    },
    {
      title: "Rear Camera",
      rows: [
        { label: "Resolution", value: ["200 MP+ 8 MP"] },
        { label: "Features", value: ["f/1.9, 24mm (wide), 1/1.56\", PDAF, OIS", "f/2.2, 120˚ (ultrawide), 1/4.0\""] },
        { label: "Video Recording", value: ["4K, 1080p, gyro-EIS, OIS"] },
      ],
    },
    {
      title: "Front Camera",
      rows: [
        { label: "Resolution", value: ["32 MP"] },
        { label: "Features", value: ["f/2.2, 22mm (wide), 1/3.1\", 0.7µm"] },
        { label: "Video Recording", value: ["4K, 1080p"] },
      ],
    },
    {
      title: "Audio",
      rows: [
        { label: "Audio Features", value: ["AAC, WAV, MP3, MIDI, VORBIS, APE, FLAC"] },
      ],
    },
    {
      title: "Network & AMP; Connectivity",
      rows: [
        { label: "SIM", value: ["Dual Nano SIM"] },
        { label: "Wi-Fi", value: ["2.4G", "5G"] },
        { label: "Bluetooth", value: ["Bluetooth 5.4"] },
        { label: "GPS", value: ["Supported"] },
        { label: "NFC", value: ["Not Supported"] },
        { label: "USB", value: ["USB 2.0"] },
        { label: "OTG", value: ["Supported"] },
      ],
    },
    {
      title: "OS",
      rows: [
        { label: "Operating System", value: ["OriginOS 6"] },
      ],
    },
    {
      title: "Features",
      rows: [
        { label: "Fingerprint", value: ["Fingerprint (under display, optical)"] },
        { label: "Sensors", value: ["Accelerometer", "Ambient Light Sensor", "E-compass", "Proximity Sensor", "Color Temperature Sensor", "Motor", "Gyroscope"] },
      ],
    },
    {
      title: "Battery",
      rows: [
        { label: "Type", value: ["7000 mAh (TYP)"] },
        { label: "Fast Charging", value: ["90W"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["163.70 × 76.20 × 7.59 mm"] },
        { label: "Weight", value: ["200g"] },
        { label: "Body Material", value: ["Plastic composite sheet"] },
        { label: "Colors", value: ["Blue, Purple"] },
      ],
    },
  ],

  description: {
    title: "Vivo V70 FE 5G (12/256GB)",
    blocks: [
      {
        paragraphs: [
          "The Vivo V70 FE 5G (12/256GB) is built for users who want flagship-style features at a more affordable price. With its massive battery, powerful Dimensity chipset, and ultra-high-resolution camera, this smartphone delivers a smooth and reliable experience for daily use, gaming, and content creation. If you're searching for a feature-packed 5G smartphone in Bangladesh with premium performance and long battery life, the Vivo V70 FE 5G is an excellent choice.",
        ],
      },
      {
        heading: "Large 6.83\" AMOLED Display with Stunning Clarity",
        paragraphs: [
          "Enjoy an immersive viewing experience with the 6.83-inch AMOLED display on the Vivo V70 FE 5G. With a sharp 2800 × 1260 resolution, this screen delivers vibrant colors, deep blacks, and excellent contrast, making it perfect for streaming, gaming, and browsing. The large display size enhances multimedia enjoyment, while AMOLED technology ensures better power efficiency and superior visual quality compared to traditional panels.",
        ],
      },
      {
        heading: "Powerful Dimensity 7360-Turbo Performance",
        paragraphs: [
          "At the heart of the Vivo V70 FE 5G is the MediaTek Dimensity 7360-Turbo chipset, designed to deliver efficient and smooth performance. The octa-core processor (4×2.5GHz Cortex-A78 & 4×2.0GHz Cortex-A55) ensures fast app launches, seamless multitasking, and stable gaming performance. With the Mali-G615 MC2 GPU, graphics-intensive tasks and games run smoothly. Combined with 12GB RAM and 256GB storage, this smartphone provides ample speed and space for all your apps, photos, and files.",
        ],
      },
      {
        heading: "200MP Ultra-Clear Camera for Professional Photography",
        paragraphs: [
          "Capture every detail with the powerful 200MP main camera, designed for ultra-high-resolution photography. Whether it’s landscapes or close-up shots, this camera ensures crisp and detailed images with OIS support for stability. The 8MP ultra-wide camera allows you to capture more in a single frame, making it perfect for group shots and scenic photography. With support for 4K video recording, gyro-EIS, and advanced imaging features, the Vivo V70 FE 5G is ideal for content creators.",
        ],
      },
      {
        heading: "32MP Front Camera for Clear Selfies",
        paragraphs: [
          "The 32MP front camera delivers bright and detailed selfies, making it perfect for social media and video calls. With support for 4K video recording, you can also create high-quality vlogs and content with ease.",
        ],
      },
      {
        heading: "Massive 7000mAh Battery with 90W Fast Charging",
        paragraphs: [
          "One of the biggest highlights of the Vivo V70 FE 5G is its 7000mAh battery, ensuring long-lasting usage throughout the day and beyond. Whether you're gaming, streaming, or working, this phone keeps up with your lifestyle. The 90W fast charging support ensures that you can quickly recharge your device, minimizing downtime and keeping you connected.",
        ],
      },
      {
        heading: "Sleek Design with Comfortable Build",
        paragraphs: [
          "Despite its large battery, the Vivo V70 FE 5G maintains a slim profile with just 7.59mm thickness and weighs around 200g, making it comfortable to hold and use. The plastic composite sheet body provides durability while maintaining a stylish and modern appearance.",
        ],
      },
      {
        heading: "Smart Features and Secure Unlock",
        paragraphs: [
          "The Vivo V70 FE 5G comes with an under-display optical fingerprint sensor for fast and secure unlocking. It also includes essential sensors such as accelerometer, gyroscope, proximity sensor, ambient light sensor, and color temperature sensor for a smarter user experience. Running on OriginOS 6, the device offers a smooth and user-friendly interface with enhanced customization options.",
        ],
      },
      {
        heading: "Reliable Connectivity with 5G Support",
        paragraphs: [
          "Stay connected with 5G network support, ensuring faster download speeds and smoother online experiences. The device also features dual nano SIM support, Wi-Fi (2.4GHz & 5GHz), and Bluetooth 5.4 for stable connectivity. With USB 2.0 and OTG support, you can easily transfer data and connect external devices.",
        ],
      },
      {
        heading: "Buying the Vivo V70 FE 5G (12/256GB) from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
