/* Generated by scripts/scrape-catalogue.mjs — do not edit by hand.
   Change the script and re-run it instead. */

import type { ProductDetail } from "../catalog";
import img1 from "@/images/brands/xiaomi-67w-usb-charger.jpeg";
import img2 from "@/images/products/xiaomi-67w-usb-charger/02-xiaomi-67w-usb-charger-white-1.jpeg";

export const xiaomi67wUsbCharger: ProductDetail = {
  breadcrumb: [
    { label: "Phone Accessories", slug: "mobile-phone-accessories" },
    { label: "Charger & Adapter", slug: "charger-adapters" },
    { label: "Cable & Adapter", slug: "cable-adapter" },
  ],
  gallery: [img1, img2],
  inStock: true,

  highlights: [
    "Up to 67W output power",
    "Including a charging cable",
    "Input: 100–240V~, 50/60Hz, 1.7A",
    "Output: 5.0-20.0V 6.2-3.25A (67.0W Max)",
  ],

  colors: [
    { name: "White", hex: "#ffffff", image: img1 },
  ],

  specs: [
    {
      title: "Basic Information",
      rows: [
        { label: "Brand", value: ["Xiaomi"] },
        { label: "Model Name", value: ["67W USB Charger"] },
      ],
    },
    {
      title: "General Information",
      rows: [
        { label: "Plug Type", value: ["USB-A"] },
        { label: "Input Power", value: ["100–240V~, 50/60Hz, 1.7A"] },
        { label: "Output Power", value: ["Fast Output: 5.0-20.0V 6.2-3.25A (67.0W Max)", "Normal Output: 5.0V 3.0A 15.0W"] },
      ],
    },
    {
      title: "Physical Specification",
      rows: [
        { label: "Dimension", value: ["49.3*73*28mm (excl.prongs)"] },
        { label: "Weight", value: ["102g"] },
      ],
    },
  ],

  description: {
    title: "Xiaomi 67W USB Charger with Type C Cable",
    blocks: [
      {
        paragraphs: [
          "The Xiaomi 67W USB Charger with Type C Cable is a powerful and compact charging solution for smartphones, tablets, and other compatible devices. With up to 67W fast charging, wide voltage input support, and a USB Type-C cable included, it is an excellent choice for home, office, and travel use.",
        ],
      },
      {
        heading: "Powerful 67W Fast Charging",
        paragraphs: [
          "Get your compatible devices powered up quickly with a maximum 67W output. The charger supports fast output from 5.0V to 20.0V, with up to 67W maximum power, making it suitable for high-speed charging needs. Designed for flexible everyday use, the charger supports 100–240V AC input at 50/60Hz, making it suitable for different electrical environments. The normal output supports 5V/3A up to 15W when fast charging is not required.",
        ],
      },
      {
        heading: "USB-A Charger with Type-C Cable",
        paragraphs: [
          "The Xiaomi 67W USB Charger features a USB-A output port and comes with a Type-C cable, giving you a convenient charging setup straight out of the box. It is ideal for compatible Xiaomi smartphones and a wide range of other USB-powered devices.",
        ],
      },
      {
        heading: "Compact and Travel-Friendly Design",
        paragraphs: [
          "Despite its powerful charging performance, the charger measures just 49.3 × 73 × 28mm, excluding the prongs, and weighs only 102g. Its compact profile makes it easy to carry in a backpack, laptop bag, or travel pouch.",
        ],
      },
      {
        heading: "Reliable Charging for Everyday Devices",
        paragraphs: [
          "Whether you need a fast phone charger, USB wall charger, or convenient travel adapter, the Xiaomi 67W charger offers dependable performance. Its high-power output makes it a practical option for users who want to reduce charging time without carrying a bulky power adapter.",
        ],
      },
      {
        heading: "Buying the Xiaomi 67W USB Charger with Type C Cable from Unique Mart",
        paragraphs: [
          "Every unit we list is sourced through official channels and intended for this market. Eligible purchases qualify for 0% EMI through partner banks, exchange is available on eligible products, and delivery is nationwide across Bangladesh.",
        ],
      },
    ],
  },
};
